### ISSUE TITLE
上传文件 无法获取到 源文件

### ISSUE THREAD

**Issue by zhoubinbinya** [Tencent/bk-sops#1027]
![1](https://user-images.githubusercontent.com/46210168/64240674-e0e71380-cf34-11e9-8cdc-3c4ccf5bb722.png)
![2](https://user-images.githubusercontent.com/46210168/64240676-e17faa00-cf34-11e9-9fbf-8d7265c9afa3.png)

前端js 没有发送  upload 下面的 URL 请求

然后 点击上传的文件 上传后 点击保存并新建任务时 这个文件就会消失

用的是 master 最新的分支

**Comment by homholueng** [comment]
1. 麻烦提供一下标准运维的版本号
2. 麻烦提供一下上传文件后浏览器捕捉到的请求信息，确认是否发起了请求，或是请求是否出现错误

**Comment by zhoubinbinya** [comment]
> 1. 麻烦提供一下标准运维的版本号
> 2. 麻烦提供一下上传文件后浏览器捕捉到的请求信息，确认是否发起了请求，或是请求是否出现错误
![1](https://user-images.githubusercontent.com/46210168/64243242-a03dc900-cf39-11e9-83d4-345ee8ce3f9e.jpg)
![2](https://user-images.githubusercontent.com/46210168/64243243-a0d65f80-cf39-11e9-92e5-9461b73c3f42.jpg)

版本号： 3.3.20
点击上传后 network 和我的 后端 没有 来自 这个URL的请求

**Comment by fannluo** [comment]
你好，上传文件 Tag 默认没有开启自动上传， 需要在标准插件上传文件配置项中 attrs 对象中添加一个 `auto_upload: true` 配置。

**Comment by zhoubinbinya** [comment]
> 你好，上传文件 Tag 默认没有开启自动上传， 需要在标准插件上传文件配置项中 attrs 对象中添加一个 `auto_upload: true` 配置。

我按照 您 这样添加 成功 发送了请求 但是返回状态码 405

**Comment by zhoubinbinya** [comment]
![1567762865(1)](https://user-images.githubusercontent.com/46210168/64418393-8339ff00-d0cd-11e9-816d-8ef06724f2c8.jpg)

我随便 请求一个不正确URL地址 都响应200 的状态码

**Comment by pagezhou** [comment]
这是因为标准运维对 404 做了拦截，都会转发到 vue 的首页，你按照正常的方式开发你的 API

**Comment by zhoubinbinya** [comment]
> 这是因为标准运维对 404 做了拦截，都会转发到 vue 的首页，你按照正常的方式开发你的 API

在我填写正确的URL 上传文件的时候 无法访问到相应的函数 状态码是 405

**Comment by pagezhou** [comment]
405 是因为你 post 请求没有传 csrftoken，前端实现请参考
```javascript
{
            tag_code: "job_local_files",
            type: "upload",
            attrs: {
                name: gettext("本地文件"),
                auto_upload: true,
                hookable: true,
                url: $.context.site_url + 'pipeline/file_upload/' + $.context.biz_cc_id + '/',
                placeholder: gettext("文件名不能包含中文和特殊字符且大小不能超过500M"),
                headers: {
                    "X-CSRFToken": getCookie("csrftoken")
                }
            },
            methods: {
                handleSuccess: function(response, file, fileList){
                    var file_num = fileList.length;
                    if(response.result){
                        fileList[file_num - 1].time_str = response.time_str;
                    }else{
                        fileList.splice(file_num - 2, 1);
                        show_msg(response.message, 'error');
                    }
                    return true;
                },
                handleError: function(err, file, fileList){
                    var result = JSON.parse(err.message)
                    show_msg(result.message, 'error');
                }
            }
        },
```

后台实现请参考
```python
def file_upload(request, biz_cc_id):
    """
    @summary: 本地文件上传
    @param request:
    @param biz_cc_id:
    @return:
    """
    file_obj = request.FILES['file']
    file_name = file_obj.name
    file_size = file_obj.size
    # 文件名不能包含中文， 文件大小不能大于500M
    if file_size > 500 * 1024 * 1024:
        message = _(u"文件上传失败， 文件大小超过500M")
        response = JsonResponse({'result': False, 'message': message})
        response.status_code = 400
        return response

    if CHINESE_REGEX.findall(file_name):
        message = _(u"文件上传失败，文件名不能包含中文和\\/:*?\"<>|等特殊字符")
        response = JsonResponse({'result': False, 'message': message})
        response.status_code = 400
        return response

    pass
```

**Comment by zhoubinbinya** [comment]
有的 我测试 就是 用的 你们源文件  job_push_local_files.js 这个js  和你这个对应的后端

**Comment by zhoubinbinya** [comment]
将 "X-CSRFToken": getCookie("csrftoken")  换成 "X-CSRFToken": getCookie(window.APP_CODE + "_csrftoken")  这个就可以了  后端需要将 biz_cc_id 转换成 int 类型

**Comment by pagezhou** [comment]
已修改，这个样例中 csrftoken 在当前版本中是 window.APP_CODE + "_csrftoken"；3.1.32版本之前是 csrftoken。感谢你的研究和反馈！
