### ISSUE TITLE
怎么在前端实现tree的菜单？或者引入第三方包

### ISSUE THREAD

**Issue by Linuxlovers** [Tencent/bk-sops#1064]
问题描述
=======

怎么在前端实现tree的菜单？或者引入第三方包
![image](https://user-images.githubusercontent.com/23232806/64574090-a4863e00-d3a0-11e9-805b-77c41aab3dbb.png)

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
请参考 CMDB-新建集群 这个官方插件，tag_code 为 tree
https://github.com/Tencent/bk-sops/blob/master/pipeline_plugins/components/static/components/atoms/cc/cc_create_set.js

**Comment by Linuxlovers** [comment]
3.2.5
版本的还是不行  您用的是什么版本

**Comment by Linuxlovers** [comment]
还有 问一下  输入10个ip,怎么做到每次执行一个ip轮流执行，而不是全部一起并发执行

**Comment by pagezhou** [comment]
不行是什么错误呢？这个 tree 前端 tag 一直都有，没有更新过；“输入10个ip,每次执行一个ip轮流执行”目前官方JOB插件不支持，可以自定义开发插件执行或者通过API多次创建任务实现
