### ISSUE TITLE
周期任务显示创建成功 但是没有执行

### ISSUE THREAD

**Issue by zhoubinbinya** [Tencent/bk-sops#1111]
问题描述
=======

![1568708036(1)](https://user-images.githubusercontent.com/46210168/65023792-2b6d8480-d966-11e9-8cd5-7d099f5b5b5f.jpg)

创建周期任务 显示成功  但是后台并没有 执行

手动执行的话 作业平台是可以看到记录 

关键信息

版本号： 3.3.20

**Comment by pagezhou** [comment]
本地环境还是线上环境，请确保启动了 celery beat 进程
```
python manage.py celery beat -l info
```

**Comment by zhoubinbinya** [comment]
> 本地环境还是线上环境，请确保启动了芹菜beat进程
> 
> ```
> python manage.py celery beat -l info
> ```

启动了这个 本地和线上 都测试了 没有效果

**Comment by zhoubinbinya** [comment]
![1568711597(1)](https://user-images.githubusercontent.com/46210168/65028298-6ffd1e00-d96e-11e9-9d3c-d2997ed8dbe3.jpg)
这个是之前手动执行的记录

**Comment by pagezhou** [comment]
在管理端 admin： http://{APP_HOST}/admin/periodic_task/periodictaskhistory/ 看一下是否有失败记录

**Comment by zhoubinbinya** [comment]
![1568711835(1)](https://user-images.githubusercontent.com/46210168/65028713-0c272500-d96f-11e9-9b84-c00aff83706a.jpg)
并没有什么记录

**Comment by pagezhou** [comment]
发一下 celery worker 的启动命令和启动成功时的console信息

**Comment by zhoubinbinya** [comment]
![1568712193(1)](https://user-images.githubusercontent.com/46210168/65029229-f6662f80-d96f-11e9-92ef-a9892fbb7c94.jpg)
![1568712223(1)](https://user-images.githubusercontent.com/46210168/65029238-fa924d00-d96f-11e9-9b4a-53c73ee1a0d6.jpg)

**Comment by pagezhou** [comment]
升级到 3.3.22 或者替换 https://github.com/Tencent/bk-sops/blob/master/pipeline/celery/settings.py 这个文件

**Comment by zhoubinbinya** [comment]
好的 我试试

**Comment by zhoubinbinya** [comment]
我尝试 更换文件  本地环境和线上环境 都没有效果 我试试升级版本看看

**Comment by zhoubinbinya** [comment]
你好 我刚刚查看了 下 是因为没有 启动 python manage.py celery beat -l info 这个所导致的

**Comment by pagezhou** [comment]
好的，解决了就好
