### ISSUE TITLE
我想将标准运维的最新版本发布现在的社区版5.1上，应该怎样操作？

### ISSUE THREAD

**Issue by kongxiaocong** [Tencent/bk-sops#1120]
问题描述
=======
我想将标准运维的3.3.20最新版本发布现在的社区版5.1上，应该怎样操作？
我想使用远程插件哪个功能。

**Comment by pagezhou** [comment]
按照教程文档打包后上传部署，覆盖官方应用即可，建议打包部署master或者V3.3.X分支的最新代码。

**Comment by kongxiaocong** [comment]
我暂时没有开发环境 能否发个最新的包到我的邮箱834790330@qq.com 十分感谢。还有个小问题 请问最新的版本能在社区版5.0上部署吗

**Comment by pagezhou** [comment]
官方包等待社区版5.1正式对外会同步放到蓝鲸官网和标准运维GitHub的Release页面，敬请期待。最新版本包含了很多新功能，部分依赖社区版5.1的PaaS等原子平台，需要配套使用，不支持直接部署在社区版5.0上。
