### ISSUE TITLE
我已经上3.3.22的源码打了一个包了上传了，但是标准运维中还是没有"管理员入口"的"后台管理页面"这个入口

### ISSUE THREAD

**Issue by kongxiaocong** [Tencent/bk-sops#1124]
问题描述
=======
我已经上3.3.22的源码打了一个包了上传了，但是标准运维中还是没有"管理员入口"的"后台管理页面"这个入口

是否还需要继续配置呢

**Comment by pagezhou** [comment]
管理员入口需要你是PaaS人员角色的管理员身份才能看到，在PaaS的人员管理中修改身份，只有管理员身份的人才能将其他人添加为管理员

**Comment by kongxiaocong** [comment]
在项目的根执行bash scripts/publish/build.sh 里面的src目录为什么是空的

**Comment by kongxiaocong** [comment]
> 管理员入口需要你是PaaS人员角色的管理员身份才能看到，在PaaS的人员管理中修改身份，只有管理员身份的人才能将其他人添加为管理员

我是用admin进去的

**Comment by kongxiaocong** [comment]
![image](https://user-images.githubusercontent.com/31007665/65057552-5d520b80-d9a5-11e9-94d6-d56689d8c39c.png)


执行npm run build -- --SITE_URL="/o/bk_sops" --STATIC_ENV="open/prod" 有报错怎么解决

**Comment by kongxiaocong** [comment]
![image](https://user-images.githubusercontent.com/31007665/65059548-c6874e00-d9a8-11e9-99ca-2a39c2e0316f.png)
执行这个也会报错 大兄弟帮忙瞧瞧

**Comment by kongxiaocong** [comment]
找亲爱的客服解决了
