### ISSUE TITLE
标准运维里的远程数据源请求失败

### ISSUE THREAD

**Issue by tezukaki** [Tencent/bk-sops#1180]
问题描述
=======

标准运维里的远程数据源请求失败 

重现方法
=======

![image](https://user-images.githubusercontent.com/21254254/65762512-c418b700-e153-11e9-8498-9177a6062346.png)
![image](https://user-images.githubusercontent.com/21254254/65762526-cf6be280-e153-11e9-8c86-fd55586050d5.png)
1、在流程里面添加远程数据源(为其它域名获取到的数据)
2、在新建任务里面，提示获取数据失败

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)：3.1.39 
 - [x] 蓝鲸PaaS   版本：3.0.8
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
请确认请求连接是否有登录要求和鉴权，需要在浏览器隐身窗口直接打开可以返回数据，才能作为数据源

**Comment by pagezhou** [comment]
下拉框的数据源目前直接通通过前端请求，可能存在跨域或者其他安全问题，改为后台转发实现

**Comment by tezukaki** [comment]
> 请确认请求连接是否有登录要求和鉴权，需要在浏览器隐身窗口直接打开可以返回数据，才能作为数据源

已确认在隐私模式下是可以直接返回数据的，并且curl不传参也能正确返回数据;从报错信息来看确实是跨域问题，后台转发是指在蓝鲸的nginx上做一层转发还是？

**Comment by pagezhou** [comment]
这个已经列入需求，后续会在标准运维代码中修改逻辑；目前建议在数据源服务器添加下访问策略，允许跨域访问

**Comment by tezukaki** [comment]
> 这个已经列入需求，后续会在标准运维代码中修改逻辑；目前建议在数据源服务器添加下访问策略，允许跨域访问

好的，谢谢
