### ISSUE TITLE
pipeline处理异常信息可以通过应用层自定义

### ISSUE THREAD

**Issue by selinagyan** [Tencent/bk-sops#1259]
问题描述
=======
在pipeline执行的过程中，会抛出异常，当前pipeline会将异常信息存储在DB，做静默处理，上层应用无法及时货值

重现方法
=======
-- 网关分支不符合条件的时候

期望解决方案
=======
-- 处理异常信息可以应用层自定义

关键信息
=======

请提供以下信息:

 - [x] bk-sops   所有版本

**Comment by homholueng** [comment]
已实现
