### ISSUE TITLE
二次开发部署上线问题

### ISSUE THREAD

**Issue by decemberfelic** [Tencent/bk-sops#1342]
问题描述
=======
二次开发bk_sops，覆盖上线一直显示 “正在上传”，上线不了。

重现方法
=======
![1](https://user-images.githubusercontent.com/51948611/68007676-40ed0280-fcb7-11e9-8e95-4bb0b3c515cc.png)
![2](https://user-images.githubusercontent.com/51948611/68007712-5e21d100-fcb7-11e9-9b8f-352b545307fc.png)

关键信息
=======
后来查询，得到图下的错误，少了一个bk_sops.png
![3](https://user-images.githubusercontent.com/51948611/68007806-beb10e00-fcb7-11e9-9ae3-aa42a7eed643.png)

按照大佬的要求，我在src文件下添加了。然后重新打包压缩成  .tar.gz格式
![4](https://user-images.githubusercontent.com/51948611/68007863-eacc8f00-fcb7-11e9-857b-2f3832a48815.png)

大佬让我看下图这个文件 utils.py 
![5](https://user-images.githubusercontent.com/51948611/68007964-30895780-fcb8-11e9-988c-ce5466f5a9ad.png)

结果没找到 utils.py ，只有utils.pyc
![6](https://user-images.githubusercontent.com/51948611/68008028-68909a80-fcb8-11e9-8af9-84856991757c.png)
大佬跟我说这是编译了，无伤大雅。

紧接着大佬让我  停止 再重新启动进程（下面三行命令）
./bkcec stop paas
./bkcec initdata paas
./bkcec start paas

启动之后，让我再次部署上线试试，可是依然是不成功，也没有显示 “部署失败” ，只剩下那个图一直在转动。
![7](https://user-images.githubusercontent.com/51948611/68008134-d2a93f80-fcb8-11e9-9522-4fa45ea5629f.png)

一直在麻烦大佬很多天了，到现在还没能够解决，希望能够帮我解决这个问题，谢谢大家！

请提供以下信息:

 - [ ] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [x] bk_sops 异常日志：

**Comment by pagezhou** [comment]
二次开发后怎么打包的？是按照打包说明操作的吗？
https://github.com/Tencent/bk-sops/blob/master/docs/install/upload_pack_deploy.md

**Comment by decemberfelic** [comment]
> 二次开发后怎么打包的？是按照打包说明操作的吗？？
> https://github.com/Tencent/bk-sops/blob/master/docs/install/upload_pack_deploy.md

将你的代码文件先压缩成 tar 再将tar这个压缩成 gz格式。然后部署上线的时候，选择添加就行了

**Comment by decemberfelic** [comment]
> 二次开发后怎么打包的？是按照打包说明操作的吗？？
> https://github.com/Tencent/bk-sops/blob/master/docs/install/upload_pack_deploy.md

**Comment by pagezhou** [comment]
你压缩的是github源码？还是从社区版拿的可部署的版本包？

**Comment by decemberfelic** [comment]
> 你压缩的是github源码？还是从社区版拿的可部署的版本包？

github源码

**Comment by pagezhou** [comment]
github源码不能直接压缩部署，请参考 https://github.com/Tencent/bk-sops/blob/master/docs/install/upload_pack_deploy.md 这个文档一步步来，尤其是打包需要在 CentOS 服务器上打包

**Comment by decemberfelic** [comment]
还是没能解决
