### ISSUE TITLE
标准插件开发文档已过期

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1366]
问题描述
=======
无法按照 [附录3 标准插件开发](https://docs.bk.tencent.com/product_white_paper/gcloud/term3.html#settings) 文档上写的步骤添加新的插件，很多内容均已过期。

重现方法
=======
如题。

关键信息
=======
简单看了下代码，以下步骤被验证是可行的：

1. 在 `bk-sops/pipeline_plugins/components/collections/sites/open` 目录下新建一个custom.py，按照附录3的文档新建了对应的Service;
2. 在 `bk-sops/static/components/atoms` 目录下新建 `custom_atoms/test.js`，添加对应的前端配置代码

重新部署后发现是可用的：

![image](https://user-images.githubusercontent.com/3972545/68283559-b6414480-00b6-11ea-9a0c-ee406611a89c.png)

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 29f4b4915be42650c2eeee637e0cf798e4066f09
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
我们后续计划文档会全部放在 GitHub 上，白皮书只会在大版本时更新，建议参考 https://github.com/Tencent/bk-sops/blob/master/docs/develop/dev_plugins.md
