### ISSUE TITLE
添加新的标准插件设置为”HTTP请求“时报错

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1379]
问题描述
=======
在界面上操作添加一个标准插件，然后设置该插件为 "HTTP" 请求时报错，界面卡顿在选择配置的部分：

![image](https://user-images.githubusercontent.com/3972545/68443874-29120300-0210-11ea-8443-91b16ce4a4bf.png)

![image](https://user-images.githubusercontent.com/3972545/68443891-3929e280-0210-11ea-9a77-0b1a993dc2c7.png)

重现方法
=======
定义一个新的流程，先定义一个HTTP服务的步骤，随后再在后面添加一个新的步骤，选择 ”HTTP服务“ 时卡住并发现console会有报错。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 29f4b4915be42650c2eeee637e0cf798e4066f09
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by Colstuwjx** [comment]
经过验证，V3.3.X 分支最新代码也会重现这个问题，我这边线上环境部署的 V3.3.13 版本是没有问题的。

**Comment by fannluo** [comment]
方便提供一下所使用的版本号或者 git tag 吗，我基于 V3.3.X 分支的最新代码测试，没有复现这个问题。

**Comment by Colstuwjx** [comment]
这个 [commit](29f4b4915be42650c2eeee637e0cf798e4066f09) 我这边跑是会有报错的，重现的方式就是：

1、加一个空的标准插件，然后选择一个类型，比如HTTP服务；
2、完成 1 后再在画布上添加一个空的标准插件，然后再选择 1 里面选择的类型，比如HTTP服务，这时候就会报错

*备注1：我这边运行的方式是本地`npm run dev`，还没有验证部署Artifact的方式会否有问题*
*备注2：我这边按照我个人的思路提了这个 [PR](https://github.com/Tencent/bk-sops/pull/1380)，可以看下*

谢谢。

**Comment by Colstuwjx** [comment]
在分支V3.3.X分支下的最新commit e507935e0c478980edd72c2a045cf44c08963593 测试还是依然报错的。

**Comment by Colstuwjx** [comment]
我这边清空 node_modules 然后重新安装了一下依赖，在最新commit测试是没问题了。
抱歉带来困扰了。
