### ISSUE TITLE
能否支持调整插件块的大小

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1384]
问题描述
=======
编辑流程的时候步骤名称过长的话会被省略掉一些文字，用户在执行流程的时候可能不确定当前执行的具体插件，最好能够像一些流程图定义工具那样能够调整块的大小。

重现方法
=======
无。

关键信息
=======
看了下样式，现在是 `.bk-flow-location .node-with-text`设置的固定的`width: 152px; height: 90px;`，是否可以加一个功能，鼠标移到块的右下角时变成 + 号，然后可以调整大小。谢谢。

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： e507935e0c478980edd72c2a045cf44c08963593
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
官方版本目前没有这种规划，插件大小涉及到很多排版和布局功能，动态调整会导致一些功能如自动排版不可用，建议你 fork 后自行开发定制需求

**Comment by Colstuwjx** [comment]
OK.
