### ISSUE TITLE
手动触发执行的插件块应该如何定义

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1385]
问题描述
=======
目前 bk-sops 任务的执行是一口气自动执行的，但是有时候会有这样的需求：某些任务需要手工触发执行，而不是自动执行。这类需求一般是由于自动化程度不够高或者流程顺序视具体执行过程确定等原因导致的，应该如何定义比较好呢？

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： e507935
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
如果是简单的中止等待下一步操作，可以用BK-暂停实现；如果涉及到审批或者复杂权限控制，需要通过 API 实现。

**Comment by Colstuwjx** [comment]
我这边之前想的是插件定义部分能否加一个“是否手动执行”，但是想了想，用 BK-暂停/审批.. + 实际action 的组合也能满足需求，可能最好不要对引擎部分加太多逻辑。

感谢回复！
