### ISSUE TITLE
子流程能否支持跳过

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1388]
问题描述
=======
标准插件目前支持 “跳过” 和 “手动重试” 的操作，但是一个流程里子流程节点没法整个跳过。

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： e507935
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
子流程只能进入后，操作节点，不支持对整个子流程跳过操作，不合理
