### ISSUE TITLE
标准流程全局参数的远程数据源格式问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1414]
问题描述
=======
由于一些全局参数需要通过API从其他系统获取并提供给用户选择，我这边以如下方式创建了一个全局参数：

![image](https://user-images.githubusercontent.com/3972545/68749439-30367800-0639-11ea-98da-7e91fdcb43fe.png)

然后在一个插件节点里引用了该全局参数

![image](https://user-images.githubusercontent.com/3972545/68749588-6f64c900-0639-11ea-92d0-59488de930b4.png)

现在遇到的问题是，上述 `/o/bk_sops/pipeline/cc_search_object_attribute/host/3/` API 后端是能够返回一个有效数据，如下所示：

```
{
  "data": [
    {
      "text": "外网IP",
      "value": "bk_host_outerip"
    },
    {
      "text": "主要维护人",
      "value": "operator"
    },
    {
      "text": "备份维护人",
      "value": "bk_bak_operator"
    },
    {
      "text": "设备SN",
      "value": "bk_sn"
    },
    {
      "text": "备注",
      "value": "bk_comment"
    },
    {
      "text": "所在国家",
      "value": "bk_state_name"
    },
    {
      "text": "所在省份",
      "value": "bk_province_name"
    },
    {
      "text": "所属运营商",
      "value": "bk_isp_name"
    }
  ],
  "result": true
}
```

但是在执行流程时，输入全局参数一步，前端界面展示如下：

![image](https://user-images.githubusercontent.com/3972545/68749954-0d589380-063a-11ea-9a52-f28fc19fdec9.png)

console 窗口看是有成功请求的：

![image](https://user-images.githubusercontent.com/3972545/68750318-a4255000-063a-11ea-8ad5-ca369749b70e.png)

![image](https://user-images.githubusercontent.com/3972545/68749984-1d707300-063a-11ea-9655-5f341e259387.png)

想问一下，全局参数的数据返回格式是否不一样？或者我这边哪里操作不对？
目前没找到相关的这块文档，搞了半天也没头绪，希望能得到回复，谢谢！

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X

**Comment by pagezhou** [comment]
需要直接返回列表类型的数据，上述接口返回的是字典类型
![image](https://user-images.githubusercontent.com/8849151/68750368-b7382000-063a-11ea-8a1c-1dbbbed7e8ca.png)

**Comment by Colstuwjx** [comment]
确实这样是OK了，这个和标准插件里面输入参数的格式定义不一致啊.. 

比如“获取主机属性”这样的API，如果想在全局参数里用这个做远程数据源定义参数的话，就得改格式了。是否考虑和标准插件的输入参数统一一下格式。

**Comment by pagezhou** [comment]
标准插件输入参数是每个插件自行控制的，官方插件的参数也是内部用的；下拉框目的是接入外部数据源，而不是标准运维给内部前端的API

**Comment by Colstuwjx** [comment]
实际和内部系统集成过程中会有一个问题：一般工具服务对外提供的API都需要有一个鉴权操作，而下拉框是在前端界面上定义的，很难做权限认证相关的操作。

如果要对接的话：1、要么改造要接入的工具服务的API，去掉鉴权，并且只保留数据部分（如果出错就直接返回空数据了）；2、在sops项目下新建一个单独的django app，然后集成到sops，这样可以利用sops的settings来配置，缺陷就是需要把第三方的代码部署在sops项目里。

两个方案都存在一些瑕疵。不知道官方有啥推荐的做法不？
谢谢！
