### ISSUE TITLE
参数的表单类型不支持 Switch

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1424]
问题描述
=======
如题，发现在定义全局参数时，类型里不支持简单的True/False的开关表单组件。

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)：V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
目前全局变量还不支持太多复杂表单，但是插件参数可以支持 radio 类型，可以替代 switch；全局变量目前可以使用多选下拉框实现这种需求。

**Comment by fannluo** [comment]
全局变量要实现类似 switch 功能，推荐使用定义单选下拉框的方式来实现。系统内置的全局变量类型是基于满足各类使用场景条件下，按照最小化原则添加的，暂时不支持 swtich。

**Comment by Colstuwjx** [comment]
OK，感谢回复！
