### ISSUE TITLE
pipeline 文档部分有错误

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1431]
问题描述
=======
pipeline的自定义组件文档 **周期性轮询** 部分 [例子](https://github.com/Tencent/bk-sops/blob/master/pipeline/docs/user_guide_custom_component.md#%E5%91%A8%E6%9C%9F%E6%80%A7%E8%BD%AE%E8%AF%A2) 里，关于schedule结果的判断部分原文如下：

```
...
        status = self._poll_status(poll_url)

        if status == 0:
            self.finish_schedule()
        elif status < 0:
            data.outputs.ex_data = 'task failed with code: %s' % status
            return False

        return True
...
```

这块有点问题，这样的话执行失败的逻辑没有做 `self.finish_schedule()`，仍然会schedule去polling。

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X

**Comment by Colstuwjx** [comment]
@homholueng

**Comment by homholueng** [comment]
`schedule` 方法返回 `False` 节点会进入失败状态，引擎是不会再次做调度的。

你那边是出现了这个问题吗？
