### ISSUE TITLE
前端表单输入组件能否支持 Cascader 的类型

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1447]
问题描述
=======
如题，表单输入部分，有时候会存在级联选择的需求，现有情况如果拆开成两个input的话，逻辑会非常难实现（因为它们会有依赖关系，A选择了某个值的话，B只能在A对应的B里面某个子集里选择一个值），因此，能否支持级联式的表单输入组件（ 比如 [Element cascader](https://element.eleme.cn/#/en-US/component/cascader) ）。

谢谢。

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
https://github.com/Tencent/bk-sops/issues/1448
重复Issue，请参考上面的解答。

**Comment by Colstuwjx** [comment]
这个我理解其实不算重复的，就是想问下，官方是否考虑增加一些原生的Tag表单组件，现有的这些表达能力还不太完备，Switch和Cascader是和远程数据源无关的，类似于动态表单的基础组件。

**Comment by pagezhou** [comment]
如果是想实现表单项的联动，目前的功能是支持的，具体请参考 https://github.com/Tencent/bk-sops/blob/V3.4.X/docs/develop/tag_usage_dev.md 中事件的定义，可以做到事件监听并触发兄弟表单项的变动

**Comment by Colstuwjx** [comment]
感谢回复！这个issue，包括 #1424  ，表达的需求是，用户在使用 bk-sops 时应当能使用原生的基础组件表达的，就尽量使用原生组件来定义，所以类似各个框架的UI组件一样，bk-sops 如果能提供一些常见的表单组件的话，是能够减少一些重复改造的过程。

在一个closed  issue里追加comment是粗鲁的做法，官方可以考虑是否reopen这个issue作为tracker，如果暂时没规划的话，可以先忽略，谢谢。

**Comment by pagezhou** [comment]
@fannluo 评估下cascade 和我们的表单事件关联是否冲突？是否合适加入到基础表单中？

**Comment by fannluo** [comment]
@Colstuwjx 对于级联选择的需求，目前我们的 tree 组件能支持类似的交互，不知道是否能满足你的使用场景。新增 cascade 类型组件已列入开发计划，后续可在基础表单组件里选择使用。另外，我们支持开发者自定义开发 Tag 组件，Tag 开发文档参考 https://github.com/Tencent/bk-sops/blob/V3.4.X/docs/develop/tag_usage_dev.md，对于公共类 Tag 组件也非常欢迎提交到我们的官方仓库。

**Comment by pagezhou** [comment]
https://github.com/Tencent/bk-sops/pull/1609
V3.4.X 以上版本已实现，等待社区版适配
