### ISSUE TITLE
输入参数支持多个参数间关联查询

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1448]
问题描述
=======
如题，我这边遇到一个需求，就是在全局变量定义部分，会有比如 A 和 B 两个参数，它们都是定义成远程数据源，其中 A 是直接从远程数据源返回的列表里选择一个值即可，但是 B 则是需要根据 A 选择的值来确定过滤参数，即 B 的远程数据源应当是 /api/v1/list_b?select_a=${a}。

但是直接这样写是不行的：

![image](https://user-images.githubusercontent.com/3972545/69218764-59f91d00-0bac-11ea-8bbd-1a598e9c07be.png)

我想到另外一种实现办法可能是再定义一个标准插件，然后输入参数就是全局变量A的值，然后标准插件实现的逻辑就是消费这个输入参数，然后在输出参数部分输出 B 的可选列表，并作为后续的全局参数。但是好像没办法做到 在标准插件里使用一个全局变量的参数值作为输入参数的**选项**。

请问官方对这样的需求有啥建议吗，关联查询应该是比较常见的需求的。

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by Colstuwjx** [comment]
目前业内动态表单实现这样关联业务逻辑的方案有一些探索，比如 [UForm](https://github.com/alibaba/uform) 是基于 json-schema 协议实现的，它也讨论到了这个问题，见 [FAQ 4和5](https://uformjs.org/#/MpI2Ij/dgSkSmuQ) 以及 [相关 issue提出的RFC](https://github.com/alibaba/uform/issues/105#issuecomment-506671540)。

bk-sops 除了直接去掉多个参数之间的业务逻辑，各自选择值以外，暂时没想到啥好的办法来做这个表单参数输入。可以一起看看，我这边内部也有造类似bk-sops的轮子，但是某些方面感觉bk-sops更通用好用一些，希望这方面功能能再完善一下，谢谢。

**Comment by pagezhou** [comment]
这种场景需要基于现有的tag自行开发新的全局变量，Tag 开发请参考https://github.com/Tencent/bk-sops/blob/V3.4.X/docs/develop/tag_usage_dev.md，自定义变量开发请参考 https://github.com/Tencent/bk-sops/blob/master/pipeline_plugins/variables/collections/common.py
