### ISSUE TITLE
关于第三方认证和权限的集成问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1459]
问题描述
=======
情况是这样的，我这边想单独只使用bk-sops组件，而不使用整个bk paas，那么除开官方内置的一些插件需要disable外，最大的一个问题便是需要集成第三方的 Login authentication 以及权限同步。目前，bk-sops 应该是和蓝鲸的认证体系集成的，我这边想法是：

1、参考 [token认证](https://github.com/Tencent/bk-sops/blob/master/blueapps/account/components/bk_token/middlewares.py#L31) 这块自行定义一套 LoginRequiredMiddleware
2、根据第三方自行定义的权限中心或权限数据源，同步用户角色，并更新[所属组别](https://github.com/Tencent/bk-sops/blob/master/gcloud/core/utils/sites/open/utils.py#L190)

想请问一下，是否这样集成是完备的方式？另外，想问下官方是否考虑过支持这样的可插拔认证和权限的代码组织形式，毕竟这样可以接纳更多的用户群体。

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)：V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
目前不支持独立部署，SaaS 底层都依赖于 PaaS 平台，如果为了独立部署，那么需要额外开发登录系统、权限中心、部署模块，相当于重造一个 PaaS。
