### ISSUE TITLE
本地运行时日志路径错位

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1471]
问题描述
=======
如题，发现日志输出在 `/Users/jacky/Colstuwjx/Projects/IaaS/logs/bk_sops` 下，但是代码是放在 `/Users/jacky/Colstuwjx/Projects/IaaS/bk-sops`

重现方法
=======
如上。

关键信息
=======
发现是由这块 [代码](https://github.com/Tencent/bk-sops/blob/V3.3.X/blueapps/patch/log.py#L25) 控制的，应该去掉 `os.path.dirname` 部分，改成如下内容：

```
    if is_local:
        log_dir = os.path.join(BASE_DIR, 'logs', APP_CODE)
```

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
这里的设计是为了让本地 logs 和线上目录基本一致，logs 目录单独管理所有 SaaS 日志，并且和 SaaS 代码分开，不会误提交到 git 代码仓库。
