### ISSUE TITLE
是否可以支持 logout

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1473]
问题描述
=======
目前没能在UI或者Django admin后台找到 logout 的方式，是否可以支持一下在bk-sops上logout。看了一下，[配置平台](https://github.com/Tencent/bk-cmdb) 是支持在它的界面上注销用户的。

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
目前 SaaS 是集成在 PaaS 上的，登录跳转和校验都是跳转到 PaaS，所以 SaaS 不会单独提供 PaaS 的 logout 功能。
