### ISSUE TITLE
API URL前缀应尽量统一

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1482]
问题描述
=======
比如 appmaker 的请求路径是 `/appmaker/get_appmaker_count/2/?group_by=category`，taskflow 是这样的 `/o/bk_sops/api/v3/taskflow/?limit=3&business__cc_id=3`，建议应当像 [awx](https://github.com/ansible/awx) 这样，API路径统一放到 `/api/...`。

现在这样做的问题是，如果想前后端分离部署到k8s这样的基础设施的话，比较难定义SLB代理上的规则。

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： master

**Comment by pagezhou** [comment]
目前已经是前后端分离的架构了，除了 / 和 static 路由，其余都应该作为后台 API 解析
