### ISSUE TITLE
SQL schema的问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1519]
问题描述
=======
Hi team，我这边遇到一个问题是，我们有内部的DB工具来做SQL审计和自助执行，如果需要部署上生产环境的话，是需要提供SQL文件上传到这个平台，经过自动审计后方能执行。

Django之前我记得是有`sqlall`这个命令来生成当前schema的sql的，但是现在好像被去掉了，取而代之的是sqlmigrate这个命令，但是只能看某次migration的sql，不太能满足需求。

我们是否需要在每次migration的时候维护一份sql文件？像 [ctrip apollo的migration](https://github.com/ctripcorp/apollo/blob/master/scripts/db/migration/configdb/V1.0.0__initialization.sql) 就是这样做的。维护单纯SQL的好处是结构是清晰的，一些键和约束的定义是显式的。

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X

**Comment by pagezhou** [comment]
你好，SQL审计应该是用来审核当前版本变更是否安全吧？你把当前版本和上一个版本的migrations文件用sqlmigrate命令生成SQL，就是当前版本的变更SQL语句。
如果需要审核整个DB的表结构，建议在测试环境升级到当前版本后，使用SQL工具导出当前的表结构，用来审计。

**Comment by Colstuwjx** [comment]
因为我这边发布代码和SQL发布都是走的发布系统，生产环境我是touch不了的，所以我现在的确就是采用你这边的做法，把测试环境的SQL dump出来一份然后在DB平台上做SQL审计和发布，只是觉得这样可能不是太优雅。

如果官方觉得这样做不太可维护的，可以close这个issue的，Django跟Apollo这样的Java应用还是有点不一样，确实也是不太好搞的。。

**Comment by pagezhou** [comment]
目前django都是通过migrations维护数据库变更的，不维护独立sql
