### ISSUE TITLE
轻应用能否支持固化参数

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1525]
问题描述
=======
目前是在职能化认领流程里是可以将全局参数事先定义好，然后交给其他职能人员来具体执行。但是存在一个问题，就是我这边有些流程是定义成比较通用的，比如游戏区服上线这样的流程，可能我这边定义的就是通用的一个“游戏区服上线标准流程”，但是具体各个游戏工作室的职能人员去执行操作时，其实希望一些全局参数是固化的，因为对他们具体的每个工作室来说，这些参数是相对固定的。

现在也可以通过直接定义标准流程，然后写死这些全局参数来实现，但是总归不是太清真。如果轻应用能够支持固化部分全局参数的话，体验会更好（因为轻应用关联的是同一份标准流程的模板，这样“游戏区服上线标准流程”如果更新了步骤的话，各个轻应用也会更新）。

重现方法
=======
如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
目前轻应用其实只是跳转到某一个流程模板的快捷方式，一旦流程模板发生变化，轻应用展示的内容也会发生变化，所以固化参数不太现实，而且增加了轻应用维护的成本。

你所面临的问题可以通过以下方法来解决：

1. 创建一个通用基本模板 A，暴露基本参数。
2. 创建多个工作室使用的模板 B C D....，在其中引用模板 A 作为子流程，并固化特定参数；之后基于 B C D... 来创建轻应用，将维护成本限制在模板范围内。

**Comment by Colstuwjx** [comment]
我现在是通过克隆任务记录来变相复用输入参数的值的。

你提议的方案试了下应该是可行的。
感谢建议！
