### ISSUE TITLE
请问，这是缺少静态文件吗？

### ISSUE THREAD

**Issue by qw1584847921** [Tencent/bk-sops#1540]
问题描述
=======

标准运维3.4.x运行起来访问时，遇到静态文件找不到的问题
INFO "GET / HTTP/1.1" 200 2536 

ERROR "GET /static/dev/dist/js/main.js?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/js/runtime~main.js?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/css/main.css?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/css/vendors.css?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/js/vendors.js?v=3.13 HTTP/1.1" 500 110 

INFO "GET /jsi18n/gcloud/ HTTP/1.1" 200 66571 

ERROR "GET /static/dev/dist/js/jquery.js?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/js/runtime~main.js?v=3.13 HTTP/1.1" 500 110 

INFO "GET /static/core/js/paas_api.js?v=3.13 HTTP/1.1" 200 1044 

ERROR "GET /static/dev/dist/js/vendors.js?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/js/main.js?v=3.13 HTTP/1.1" 500 110 

ERROR "GET /static/dev/dist/js/jquery.js?v=3.13 HTTP/1.1" 500 110 

INFO "GET /static/core/images/bk_sops.png HTTP/1.1" 200 15730 

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 3.4.x

**Comment by pagezhou** [comment]
是的，本地开发请先参考文档进行前端打包 https://github.com/Tencent/bk-sops/blob/V3.4.X/docs/install/dev_deploy.md#%E6%89%93%E5%8C%85%E5%B9%B6%E6%94%B6%E9%9B%86%E5%89%8D%E7%AB%AF%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90
