### ISSUE TITLE
变量名在编辑时发现长度超过限制

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1570]
问题描述
=======
背景是定义了一个变量名，在创建时是不带`${}`的，因此是可以创建出来的，但是在编辑时因为前端默认会给加上`${}`，这时就会发现超过长度限制了。

有时候创建出来之后再改的场景是比较特殊的，比如最开始是默认的输入input，后面有API可以对接了，可以改成远程数据源了，但是这时候发现长度超过限制的话，对用户会有一定困扰，因为这时候已经有标准插件在消费该变量了。

重现方法
=======
如上，先定义一个接近20个字符长度的变量，比如`target_nginx_domain`，创建成功后，点击该变量编辑时会自动加上`${}`，这时候再点保存便会报错说长度超过限制。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
@fannluo 这里看下怎么优化？保持 ${xx} 中 xx 长度不超过20

**Comment by fannluo** [comment]
V3.4.X 版本已修改为由节点配置面板勾选的变量不校验 key 的长度
