### ISSUE TITLE
关于标准插件输入参数的数据类型问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1573]
问题描述
=======
Hi team，之前印象里有看到输入参数scheme相关的PR，不知道现在是否支持相关的功能？我这边场景就是，有一些ID和列表性质的输入参数，比如`6`，`["A", "B", "C"]`，它们是固定值，但是往往标准插件在`data.get_one_of_inputs`去获取具体值的时候发现都变成string了，暂时我这边是通过
`ast.literal_eval`的方式得到具体类型值的。

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
标准运维的全局变量除了整数、下拉框都是字符串类型，插件的参数类型和表单定义有关。建议在自定义插件中需要什么类型时进行转换。
