### ISSUE TITLE
子流程不支持可选步骤的执行计划

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1584]
问题描述
=======
目前bk-sops提供执行计划的功能，定制一些可选步骤的勾选，但是好像这个功能不支持勾选子流程里的可选步骤。

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
这个是不支持的，子流程在父流程中可以看做一个执行单元，所以要么全部执行，要不全部勾掉；
另一个问题就是如果执行方案的可选节点包含了子流程的节点设置，那么用户维护成本和使用成本非常高，比多克隆几个子流程的副本还要麻烦。
所以可选节点在设计上就不支持调整子流程里面的节点。

**Comment by Colstuwjx** [comment]
理解！
