### ISSUE TITLE
标准插件勾选为全局变量功能的一些问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1587]
问题描述
=======
如题，背景是我们这边有些标准插件在一个流程里重复出现的概率非常高（比如一些常规的ansible操作），因此需要在全局变量里定义非常多的“重复”参数，比如一个标准插件需要A、B、C三个参数，那么可能全局变量里需要定义 A1\B1\C1 ~ AnBnCn ( n=插件重复出现的次数 )，针对这个问题有几种解决办法：

1、直接写死到标准插件的参数输入部分；
2、全局变量老实定义m*n个参数；
3、标准插件勾选为全局变量；
4、支持在执行时再针对每个标准插件未补全的参数 **分别展示**  进行进一步补全

对于用户来说，3和4是比较友好的。目前3功能上是有的，但是存在两个不足：

1、用户勾选为全局变量后，**没有明确表示该变量具体是被哪个标准插件引用**，变量多了以后脑子就糊了，搞不清楚了；
2、用户勾选为全局变量后，**无法再继续编辑该变量**，这导致一些功能无法使用，比如希望该变量设置为消费远程数据源的下拉框形式

谢谢。

重现方法
=======

如上。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
1、关于明确展示该变量被哪个插件引用的功能，我们已经列入需求中，不过这里交互比较复杂，到时方案确认后会在这里再次同步
2、用户勾选全局变量，只能继续编辑值，无法改变form类型；因为每个插件的参数类型不一样，不管是否勾选，都不支持用户改变form类型；只有自定义全局变量，才允许用户修改类型
