### ISSUE TITLE
3.4.x的标准运维本地运行问题

### ISSUE THREAD

**Issue by Linuxlovers** [Tencent/bk-sops#1588]
问题描述
=======

3.4.x的标准运维本地运行问题
![image](https://user-images.githubusercontent.com/23232806/70792340-f097b300-1dd3-11ea-809b-7ff4dbf5c016.png)

重现方法
=======

克隆
初始化数据库
运行 发现报错
![image](https://user-images.githubusercontent.com/23232806/70792395-1f158e00-1dd4-11ea-8ea8-74235cc0d2c2.png)

关键信息
=======
bk_sops | 标准运维 | 蓝鲸智云 | 3.4.7

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
V3.4.X 分支暂时不支持社区版部署，需要配合后续的权限中心产品使用。
