### ISSUE TITLE
自定义Tag的问题

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-sops#1590]
问题描述
=======
Hi team,
我这边看了一下仓库里提供的文档：

```
Tag 开发请参考 https://github.com/Tencent/bk-sops/blob/V3.4.X/docs/develop/tag_usage_dev.md
自定义变量开发请参考 https://github.com/Tencent/bk-sops/blob/master/pipeline_plugins/variables/collections/common.py
```

我这边试了一下，有几个问题：

1、vue组件的editor settings能否有个标准然后放到bk-sops的repo，作为开发规范（不知道是不是我这边vscode配置问题，eslint一直报错..）；

2、开发一个完整的使用自定义Tag的全局变量，步骤应该是 `RenderForm\Tags` 里面加一个`TagXXX.vue`，然后在`pipeline_plugins/variables/collections/common.py`里面增加对应的Variable类，并且在`pipeline_plugins/variables/static/variables`里面添加一个atom的配置js文件，**是否一定需要按照这三个步骤来定制全局变量选择时可用的Tag组件呢？**，如果只是在`RenderForm\Tags`定义一份`TagXXX.vue`，是否该组件就只能在标准插件里使用的时候用到？

3、定制组件时，用户如果不想使用element ui或者magicbox-vue的话，该如何引用自己选用的Vue组件库，我看代码里 [这块](https://github.com/Tencent/bk-sops/blob/master/frontend/desktop/src/main.js#L21) 有做全局的配置，是否直接在这里增加自己引用的组件库，以及本地化locales配置就可以了？官方对此有啥建议吗。

谢谢！

重现方法
=======
如题。

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by fannluo** [comment]
非常感谢参与自定义 Tag 的开发，下面是关于所提出问题的解答。

问题1：前端项目对语法和书写规范有统一的 eslint 规则，可以在前端根目录的 .eslintrc.js 文件中查看，vscode 报错的问题，可能需要检查 eslint 插件的配置。

问题2：新增全局变量需要按照你描述的步骤来处理，如果只添加一个 TagXXX.vue 文件，那该组件只能在标准插件引用。前端页面上可使用的全局变量列表，由后台接口定义，全局变量和标准插件都是基于 RenderForm 渲染，所以需要增加 atom 的配置文件，并在全局变量接口新增对应变量类。

问题3：定制组件可以使用任意的库，如何引用以及国际化处理，按照所使用库的开发文档添加即可。

**Comment by Colstuwjx** [comment]
感谢回复！

关于元变量还有一个疑问，比如 [select meta](https://github.com/Tencent/bk-sops/blob/master/pipeline_plugins/variables/static/variables/select.js#L80)，是否是在后端collections里定义了`type = 'meta'`的话，就需要在variables的atom js配置文件定义里实现`meta_transform`方法先行处理一下`metaConfig`，然后再返回一份处理后的atom配置？还有啥其他需要注意的细节吗？

谢谢！

**Comment by fannluo** [comment]
是的。另外，元变量的数据定义部分和数据使用部分的 tag_code 需要区分下。
