### ISSUE TITLE
咨询下如何部署多个实例同一份数据源

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-sops#1792]
问题描述
=======
在paas上怎么可以部署两个bk-sops, 默认负载均衡方式访问两个实例，远程插件同步部署一个实例不会影响sops服务

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
PaaS 部署问题请参考官方文档 https://bk.tencent.com/docs/document/5.1，如果还有疑问可以 QQ咨询(800802001)
