### ISSUE TITLE
标准运维V3.5.3依赖bkiam系统开源怎么解决这个依赖

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-sops#1800]
问题描述
=======
标准运维V3.5.3依赖bkiam系统开源怎么解决这个依赖
据我了解bkiam好像没有开源，如果社区版升级bk_sops, 用户这块怎么获取。

celery定时任务
sync business from cmdb
涉及的接口
/api/c/compapi/v2/usermanage/retrieve_user/

重现方法
=======
[2020-03-01 23:52:00,073: INFO/Worker-1] Start sync business from cmdb...
[2020-03-01 23:52:03,625: ERROR/Worker-1] Request component error, status_code: 404
url=http://paas.xxx.com/api/c/compapi/v2/usermanage/retrieve_user/
Traceback (most recent call last):
  File "/Users/zl/project/bk-sops/packages/blueking/component/base.py", line 48, in __call__
    return self._call(*args, **kwargs)
  File "/Users/zl/project/bk-sops/packages/blueking/component/base.py", line 91, in _call
    raise ComponentAPIException(self, message, resp=resp)
packages.blueking.component.exceptions.ComponentAPIException: Request component error, status_code: 404, resp={"message": "The content does not exist", "data": null, "result": false}

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)：V3.5.3 
 - [x] 蓝鲸PaaS   版本：社区版v5.1自带paas 
 - [ ] bk_sops 异常日志：

**Comment by zhouchengcom** [comment]
所有的组件都依赖这个服务，能否提供这个服务

**Comment by pagezhou** [comment]
V3.4.X 和 V3.5.X 都依赖蓝鲸权限中心 bkiam，暂时不支持部署在社区版，建议等社区版推出带有权限中心版本后再使用新分支，目前只能使用 master和V3.3.X 分支

**Comment by homholueng** [comment]
3.6.X 版本之后会提供 bkiam 社区版，还请耐心等待

**Comment by homholueng** [comment]
社区版 6.0 已发布 https://bk.tencent.com/s-mart/community/question/1357
