### ISSUE TITLE
咨询下pause节点调用回调是否可以支持post一个json data

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-sops#1915]
问题描述
=======

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
官方暂停插件不支持，你可以自己修改逻辑，类似JOB-执行作业插件，在callback时可以传参，并在schedule函数中获取callback_data
