### ISSUE TITLE
标准运维3.4.15版本问题

### ISSUE THREAD

**Issue by zhanghengtao-git** [Tencent/bk-sops#2050]
问题描述
=======

上个版本标准运维用的是3.4.11版本，由于3.4.11版本的邮件通知不能更改负责人且无法上传文件，所以我们升级到了3.4.15版本，当前在3.4.15版本问题更多：
1、在3.4.11版本建的子流程作业，在3.4.15版本没法在全流程上点击更新按钮，更新后全局变量消失，手动新建全局变量不生效；
2、流程的迁入迁出，业务是固定的不会自己变；
3、本地文件和服务器文件都无法传输；
4、在3.4.11版本建的作业，在3.4.15版本做修改后无法保存。

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [x] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
企业版问题有专门运营人员跟进哈，就不在开源仓库重复讨论了
