### ISSUE TITLE
前端本地启动代理到服务器上，页面出现没有权限

### ISSUE THREAD

**Issue by lu-shuai** [Tencent/bk-sops#2125]
问题描述
=======

前端配置好代理，浏览页面，点击菜单栏出现没有权限页面

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
请提供更详细的信息，标准运维版本号，出错页面等
