### ISSUE TITLE
有没有蓝鲸各个组件版本依赖图

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-sops#2174]
问题描述
=======

bk-sops的各个版本依赖什么版本的bk-paas，bk-cmdb等

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
目前暂时没有，从 3.6.X 版本开始会提供

**Comment by homholueng** [comment]
https://bk.tencent.com/docs/document/6.0/156/8602?r=1

请参考此处提供的版本依赖
