### ISSUE TITLE
请问前端的流程组件用的是什么？

### ISSUE THREAD

**Issue by doterme** [Tencent/bk-sops#222]
问题描述
=======

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by fannluo** [comment]
前端流程图工具是基于 jsplumb 封装的。

https://github.com/jsplumb/jsplumb
