### ISSUE TITLE
配置APP_TOKEN 的问题

### ISSUE THREAD

**Issue by boystray** [Tencent/bk-sops#224]
文档中“APP_TOKEN 设置为你的社区版标准运维应用 TOKEN，默认可以访问 http://{BK_PAAS_HOST}/admin/app/app/，找到名为"标准运维"的应用，查看详情获取 Token 字段值。”
我刚刚搭建的paas环境中并没有"标准运维"的应用，该怎么获得这个TOKEN？

**Comment by pagezhou** [comment]
标准运维本地环境部署依赖社区版环境，请先前往蓝鲸官网下载最新蓝鲸智云社区版，在符合要求的服务器部署PaaS和标准运维SaaS，然后从该社区版获取需要的环境变量信息。文档正在添加中，请关注后续更新的本地部署文档。

**Comment by pagezhou** [comment]
是的，标准运维登录和鉴权都依赖于社区版PaaS和配置平台等系统
