### ISSUE TITLE
后续pipeline会提供对打回的支持吗

### ISSUE THREAD

**Issue by uamsunshine** [Tencent/bk-sops#2281]
我用了你们的pipeline作为工作流引擎，可是没有提供打回的接口

**Comment by homholueng** [comment]
@uamsunshine 目前引擎已经支持打回操作，请简单描述您目前的使用方式，我们会提供相关的指引

**Comment by uamsunshine** [comment]
就是我流程要跳转到之前的某个节点，我看你们提供的是跳过当前节点的接口

**Comment by homholueng** [comment]
打回不是通过引擎的接口来实现，而是在构造流程的时候构造出环状结构，并通过分支网关来控制走向

**Comment by uamsunshine** [comment]
谢谢你的帮助

**Comment by uamsunshine** [comment]
你们的pipeline确实挺好用的，我用它实现了工作流
