### ISSUE TITLE
循环流程怎么绘制

### ISSUE THREAD

**Issue by uamsunshine** [Tencent/bk-sops#2284]
![image](https://user-images.githubusercontent.com/13538425/86885359-bacb6a80-c127-11ea-8c65-76bdd2454a24.png)
这样的分支循环怎么绘制
![image](https://user-images.githubusercontent.com/13538425/86885399-ce76d100-c127-11ea-90ae-97310e7c251a.png)

**Comment by uamsunshine** [comment]
请教大佬

**Comment by homholueng** [comment]
```python
start.extend(act_1).extend(act_2).extend(act_3).extend(gateway)
gateway.connect(act_1, end)
```

**Comment by uamsunshine** [comment]
谢谢您
