### ISSUE TITLE
标准运维3.3.27在高并发时丢失结束节点，导致流程无法正常结束

### ISSUE THREAD

**Issue by charli117** [Tencent/bk-sops#2420]
问题描述
=======
1、故障流程一直处于执行中，查看流程任务实际已经执行到最后一步，如图：
![image](https://user-images.githubusercontent.com/24435100/89252082-524eab00-d64b-11ea-94f0-f5459f685f22.png)

2、查看日志发现在获取步骤状态时失败，在模版中检索该步骤id发现并不存在，如图：
![image](https://user-images.githubusercontent.com/24435100/89252163-888c2a80-d64b-11ea-8666-8bb80db5e5e7.png)

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 ：v3.3.27-ee
 - [x] 蓝鲸PaaS   版本：open_paas 2.8.47、paas_agent 2.5.9
 - [x] bk_sops 异常日志：
![image](https://user-images.githubusercontent.com/24435100/89252163-888c2a80-d64b-11ea-8666-8bb80db5e5e7.png)

**Comment by charli117** [comment]
发现出现这种情况的流程都涉及并行任务，是否跟这个有关呢？

**Comment by homholueng** [comment]
@charli117 请尝试升级到 3.3.30 版本，看看是否还有这个问题，提供的报错日志与这个问题无关，celery 进程的日志麻烦提供一下

**Comment by homholueng** [comment]
过久未回复，暂时关闭待提供更多信息
