### ISSUE TITLE
我想参与到这个项目的前端开发

### ISSUE THREAD

**Issue by PmcFizz** [Tencent/bk-sops#2446]
我目前在公司也是从事的云原生开发, 基于rancher 和 kubesphere项目开发, 不知道你们的前端开源团队还缺不缺贡献者, 我vue贼6 react也很强, 详细了解你们的项目后  很希望能够参与到你们的开源项目中,成为光荣的贡献者之一. 盼复. 谢谢.

**Comment by homholueng** [comment]
@PmcFizz  很抱歉没能及时回复您的信息，目前前端开发需要依赖线上后端服务，当前社区版的版本无法满足 3.5.X 以上版本的开发需求，请关注我们预定于10月发布的新版本；新版本发布后能够提供低成本部署的后端服务环境供开发使用。

**Comment by PmcFizz** [comment]
谢谢 回复，持续关注你们的项目。
