### ISSUE TITLE
分支表达式编辑时删除最后一个字符光标位置错误

### ISSUE THREAD

**Issue by pagezhou** [Tencent/bk-sops#2567]
问题描述
=======

分支表达式编辑时删除最后一个字符光标位置错误，定位到了行首

重现方法
=======

删除前，光标在3后面
![image](https://user-images.githubusercontent.com/8849151/91375876-62bf0380-e84e-11ea-9941-5756e2005b25.png)

删除后，光标在行首，而不是之前3的位置
![image](https://user-images.githubusercontent.com/8849151/91375952-8b46fd80-e84e-11ea-8052-0d0a8a34f71a.png)

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)：3.5.17
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by fannluo** [comment]
感谢 page 反馈，已定位到原因，表达式第一个或最后一个字符为空格的时候会出现这个情况，会尽快修复这个问题。

**Comment by fannluo** [comment]
已修复
