### ISSUE TITLE
进入管理员入口-数据统计，刷新页面，已选中业务丢失

### ISSUE THREAD

**Issue by pagezhou** [Tencent/bk-sops#271]
问题描述
=======

进入管理员入口-数据统计，刷新页面，已选中业务丢失
![image](https://user-images.githubusercontent.com/8849151/56939396-aca0b800-6b3a-11e9-96c7-d55562bb74ed.png)

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： V3.3.X
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by fannluo** [comment]
初步排查原因是，在管理员入口页面刷新时，返回的 html 模版里定义的默认业务 id 不存在对应业务导致。

![image](https://user-images.githubusercontent.com/44999219/57280945-8354ce80-70dc-11e9-9905-a394d26ae401.png)
