### ISSUE TITLE
标准运维复制元素节点的时候，输入参数，输出参数复制带不过去

### ISSUE THREAD

**Issue by Aesthetlc** [Tencent/bk-sops#2807]
问题描述
1.标准运维复制元素节点的时候，输入参数，输出参数复制带不过去

重现方法
如上。

关键信息
请提供以下信息:

 bk-sops 版本 (发布版本号 或 git tag)： V3.3.X
 蓝鲸PaaS 版本：
 bk_sops 异常日志：
![问题](https://user-images.githubusercontent.com/35282196/94238590-2fea5700-ff43-11ea-8955-d668d21febda.gif)

**Comment by homholueng** [comment]
@Aesthetlc 你好，目前 V3.3.X 版本已经不再维护，V3.6.X 版本已经解决该问题，可以尝试升级至蓝鲸社区版 6.0
