### ISSUE TITLE
sops代码正式环境上传部署问题2

### ISSUE THREAD

**Issue by renxianfu** [Tencent/bk-sops#2989]
问题描述
=======

打包前端资源得时候，无前端的文件生成

重现方法
=======

npm run build -- --SITE_URL="/o/bk_sops" --STATIC_ENV="open/prod"
问题，文件夹open/prod是不会产生
导致：frontend/desktop/static/open  文件夹不会产生，打包sops完成后，界面一片空白

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
您好，请提供当前使用的代码分支和标准运维的版本以便我们进一步的帮助您排查问题

**Comment by homholueng** [comment]
该问题没有后续跟进，暂时先关闭，如果您还有问题需要咨询欢迎再次打开反馈
