### ISSUE TITLE
django工程的静态资源最好能提前收集到 static 目录

### ISSUE THREAD

**Issue by pagezhou** [Tencent/bk-sops#30]
问题描述
=======
django工程的静态资源最好能提前收集到 static 目录，通过自动化 CI 执行 collecstatic 依赖 mysql、python 等环境，成本较高

重现方法
=======
python manage.py collectstatic --noinput

**重要提醒**: 请优先尝试部署使用最新发布的版本 (发布清单： https://github.com/Tencent/bk-sops/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=======

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk_sops   V3.3.8

**Comment by vvoody** [comment]
您好，请教为啥 collectstatic 甚至整个 manage.py 都要连接数据库？可以指出定制的地方吗？我们需要在 CI 里每次跑 collectstatic。
