### ISSUE TITLE
蓝鲸如何切换到英文

### ISSUE THREAD

**Issue by rocky-luoqi** [Tencent/bk-sops#3086]
问题描述
=======
蓝鲸支持英文吗？找了很久都没有找到切换到英文的方法

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
@rocky-luoqi  您好，当前版本还不支持国际化
