### ISSUE TITLE
标准运维中的权限管理中配置的提单跟认领角色可以删除流程

### ISSUE THREAD

**Issue by DiaboFong** [Tencent/bk-sops#316]
问题描述
=======

![image](https://user-images.githubusercontent.com/1555855/57691328-7d2f9680-7676-11e9-97a4-104e21d9b5c2.png)
业务的开发角色(标准运维权限管理中配置为新建任务权限)，直接可以删除这个流程。

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
麻烦提供一下标准运维的版本号，便于我们定位问题，版本号能够在开发者中心中查看。

**Comment by DiaboFong** [comment]
我的标准运维版本是：3.1.39

**Comment by homholueng** [comment]
确认是 3.1.39 的 BUG，该 BUG 已在 3.1.40 修复。
