### ISSUE TITLE
发送通知作业携带用户信息

### ISSUE THREAD

**Issue by wykevin** [Tencent/bk-sops#339]
标准运维流程里， 发送通知作业里需要 携带当前 执行流程 的用户。

**Comment by pagezhou** [comment]
这个可以结合之前用户提到的需求，实现更通用的需求：
暴露内置变量让用户引用，如 ${inner_operator}，

**Comment by pagezhou** [comment]
在通知信息中引用 ${_system.operator} 变量即可
