### ISSUE TITLE
导入rsa模块会导致模型component_framework_componentmodel中相应的插件status变为1?

### ISSUE THREAD

**Issue by IvesFeng** [Tencent/bk-sops#3502]
在plugins.py中, 由于需要把密码解密出来, 所以需要导入以下函数
from pipeline.utils.crypt import rsa_decrypt_password
但是导入此函数会导致模型component_framework_componentmodel中相应的插件status变为0。
我去看了这个模块, 里面需要导入base64和rsa。
然后我把pipeline.utils.crypt的代码复制到plugins中, 发现只需要import rsa一行代码就会导致数据库中插件状态变为0, 我删除这一行代码后就自动变为1.

**Comment by IvesFeng** [comment]
我明白了, 导入rsa的时候, 这个模块找不到. 我想问, 代码在哪捕获了这个异常会把插件状态置为0

**Comment by homholueng** [comment]
如果导入插件时插件模块时出现错误插件会导入失败，请关注 `[!] module({module_path}) import failed with err` 字眼的日志
