### ISSUE TITLE
项目级别的环境变量

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#3562]
## 用户故事

作为一名用户
我希望能在标准运维的业务下添加一些业务级别的变量
以便于我在模板中直接引用而不需要重复定义和修改

## 用例

- 定义业务级别的变量
- 在模板中引用业务级别的变量

**开发使用分支：feature_project_scope_constants**

## 设计稿

![image](https://user-images.githubusercontent.com/26020997/118087794-b1bac200-b3f8-11eb-800c-258eb039d70e.png)

**Comment by chenrb** [comment]
![image](https://user-images.githubusercontent.com/27913541/118255476-e86b0800-b4de-11eb-9457-ad3ce9482029.png)

**Comment by homholueng** [comment]
字段调整
`creator` -> `create_by`

**Comment by chenrb** [comment]
![image](https://user-images.githubusercontent.com/27913541/118386680-d0fd5d80-b64b-11eb-98b3-6b17159071bf.png)
![image](https://user-images.githubusercontent.com/27913541/118386691-e83c4b00-b64b-11eb-9c11-2402dd483cc1.png)
![image](https://user-images.githubusercontent.com/27913541/118386697-f4c0a380-b64b-11eb-9daf-dfe0d308f547.png)
![image](https://user-images.githubusercontent.com/27913541/118386705-fc804800-b64b-11eb-8632-761733a44834.png)
接口协议如上，目前变量创建、更新、删除的校验规则还没有完成

**Comment by chenrb** [comment]
变量创建、更新校验：项目内key值唯一；
删除校验：项目内是否使用

**Comment by homholueng** [comment]
> ![image](https://user-images.githubusercontent.com/27913541/118386680-d0fd5d80-b64b-11eb-98b3-6b17159071bf.png)
> ![image](https://user-images.githubusercontent.com/27913541/118386691-e83c4b00-b64b-11eb-9c11-2402dd483cc1.png)
> ![image](https://user-images.githubusercontent.com/27913541/118386697-f4c0a380-b64b-11eb-9daf-dfe0d308f547.png)
> ![image](https://user-images.githubusercontent.com/27913541/118386705-fc804800-b64b-11eb-8632-761733a44834.png)
> 接口协议如上，目前变量创建、更新、删除的校验规则还没有完成

- GET 请求中的 project_id 做成路径参数会更符合 REST 的实践
- PUT 请求中不允许传入 project_id

**Comment by homholueng** [comment]
变量创建、更新校验：项目内key值唯一：🆗
删除校验：项目内是否使用：不需要做后台校验，只需要在删除前前端提示用户就好

**Comment by homholueng** [comment]
已完成
