### ISSUE TITLE
如何更改前端UIUE，整合到对方公司SaaS平台，符合对方公司整改要求的建议

### ISSUE THREAD

**Issue by tianyige21** [Tencent/bk-sops#3578]
> ### 是BUG反馈还是需求提交(Is this a BUG REPORT or FEATURE REQUEST)? (choose one):
> 需求提交
> 
> ### BK-BCS-SaaS 版本(The versions used):
> 最新版本
> 
> ### 发生了什么(What happened):
> 前端UIUE不能在你们的代码里面更改，因为涉及到你们频繁的变更，如果直接拉你们的代码到我们自己的库合代码，出错成本会变大
> 
> ### 期望是什么(What you expected to happen):
> 你们的代码能不能有一个口子，模版我们可以直接修改，修改完能符合我们公司的UIUE规范，里面的文案也能符合
> 
> ### 如何复现(How to reproduce it):
> 随时复闲
> 
> ### 相关的日志详情和截图等(Log & @screenshot):
> 无
> 
> ### 备注(Anything else we need to know):
> 无

**Comment by homholueng** [comment]
这是 BCS 的需求吧？请前往 BCS 仓库提交 issues
