### ISSUE TITLE
【功能】条件并行网关失败处理功能

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#3900]

**Comment by fannluo** [comment]
目前的版本条件并行网关不支持跳过，在模板编辑页面把添加入口隐藏了。

https://github.com/Tencent/bk-sops/blob/5e88865c1b879033fc0cac1a1243323846fc683e/frontend/desktop/src/components/common/TemplateCanvas/NodeTemplate/ShortcutPanel.vue#L87

https://github.com/Tencent/bk-sops/blob/5e88865c1b879033fc0cac1a1243323846fc683e/frontend/desktop/src/components/common/TemplateCanvas/PalettePanel/index.vue#L56

开发这个功能需要把这两个地方的注释取消。
