### ISSUE TITLE
【功能】运营数据维度丰富（含DB重构）catalina_statistics_optimizaition

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#3901]

**Comment by yovafeng** [comment]
### 目标
重构InstanceInPipeline，ComponentInTemplate，ComponentExecuteData三张表，实现在单次数据表查询中获取到“运营数据”所需的所有数据
### 总体设计
BaseTemplate和TaskInstance表重构流程
### 新表字段
**ComponentInTemplate**

集成TaskTemplate、PipelineTemplate、Project的字段

1. template_id：模板id
2. atom_total：插件总数
3. subprocess_total：子流程总数
4. gateway_total：网关总数
5. name：模板名称
6. category：模板类型
7. project_id：所属项目id
8. project_name：所属项目名
9. collector：收藏的人
10. time_out：超时时间（分钟）
11. created_time：创建时间
12. creator：创建者
13. editor：修改者
14. edit_time：修改时间
15. has_subprocess：是否有子流程
16. is_deleted：是否删除

**InstanceInPipeline**
集成TaskFlowInstance、PipelineInstance、Project的字段

1. instance_id：实例id
2. instance_name：实例name
3. creator：创建者
4. create_time：创建时间
5. executor：执行者
6. start_time：启动时间
7. finish_time：结束时间
8. is_started：是否启动
9. is_finished：是否完成
10. is_revoked：是否撤销
11. is_deleted：是否删除
12. is_expired：是否过期
13. atom_total：插件总数
14. subprocess_total：子流程总数
15. gateway_total：网关总数
16. project_id：所属项目id
17. project_name：所属项目名
18. category：任务类型，继承自模板
19. template_id：所属模板id
20. template_source：模板来源
21. create_method：创建方式
22. create_info：创建任务额外信息
23. flow_type：任务流程类型
24. engine_ver：引擎版本

**ComponentExecuteData**
集成TaskFlowInstance、PipelineInstance、Project的部分字段

1. component_code：组件编码
2. instance_id：实例id
3. node_id：节点id
4. project_id：所属项目id
5. project_name：所属项目名
6. is_sub：是否子流程引用
7. subprocess_stack：子流程堆栈
8. started_time：标准插件执行开始时间
9. archived_time：插件执行结束时间
10. elapsed_time：插件执行耗时
11. status：执行是否成功
12. is_skip：是否跳过
13. is_retry：是否重试记录
14. version：插件版本
15. create_time：实例创建时间
16. start_time：实例启动时间
17. finish_time：实例结束时间

### 需要适配新表的运营数据相关逻辑
**1、任务实例模块**
查询不同业务对应的流程数
查询各标准插件被执行次数
查询各标准插件失败次数
查询各标准插件失败率
查询各标准插件平均耗时（不计算子流程）
被引用的任务实例列表
各任务实例执行的标准插件节点个数、子流程节点个数、网关节点数
按起始时间、业务（可选）、类型（可选）、图表类型（日视图，月视图），查询每一天或每一月的执行数量
按分类对任务执行数进行统计
**2、流程模板模块**
按流程模板执行状态查询流程个数
查询不同业务的模板个数
查询不同原子引用的个数
按起始时间、业务（可选）、类型（可选）、标准插件查询被引用的流程模板列表(dataTable)
需要获得符合的查询的对应 template_id 列表
### 平滑数据迁移策略
#### 1、实现以下的小工具，执行数据迁移主逻辑
**ComponentInTemplate**
根据template_id查出对应的TaskTemplate记录
根据TaskTemplate记录查出对应的PipelineTemplate记录和project
将project、pipelineTemplate、TaskTemplate中相关的数据组合成新的记录
将组合好的记录批量插入新的ComponentInTemplate表
**InstanceInPipeline**
根据instance_id查出对应的TaskFlowInstance
根据TaskFlowInstance查出对应的PipelineInstance和project
将project、PipelineInstance、TaskFlowInstance的相关数据组合成新纪录
将新纪录批量插入InstanceInPipeline
**ComponentExecuteData**
根据instance_id查出对应的TaskFlowInstance
根据TaskFlowInstance查出对应的PipelineInstance和project
将project、PipelineInstance、TaskFlowInstance的相关数据组合成新纪录
将新纪录批量插入ComponentExecuteData

#### 2、数据量过大、采用分批次任务迁移，每次任务结束记录当前迁移进行到的数据行主键
将上面提到的“执行迁移主逻辑”设计成一个事务型分批次任务，每次执行一万条的数据迁移。

1、开始迁移之前首先获取旧表中最新的记录主键，然后记录下来

2、执行迁移，每次迁移一万条数据，如果迁移过程遇到迁移失败的情况，直接执行下一条迁移，然后将迁移错误的数据记录下来

3、数据全部迁移完成之后开始处理第二步中得到的迁移错误记录

4、检查新表和旧表一致性

### 运营数据维度扩展
#### 1、流程模板模块

使用流程模板的业务在cc线上业务的占比情况

在ComponentInTemplate表按 group_by = project_id的方式进行聚合查询获取“使用流程模板的业务数量”、通过client实时查询cc线上业务，然后计算占比

新增上次编辑时间（在返回数据中加上ComponentInTemplate.edit_time字段）

#### 2、任务实例模块

**1、执行过任务的业务在cc线上业务的占比情况**
在InstanceInPipeline表按 group_by = project_id的方式进行聚合查询获取“使用流程模板的业务数量”、通过client实时查询cc线上业务，然后计算占比

**2、新增任务执行方式占比和分布（在返回数据中添加InstanceInPipeline.create_method字段）**

**Comment by homholueng** [comment]
1. ComponentInTemplate 和 TemplateInPipeline 合成了一张表？
2. InstanceInPipeline 是否需要那么多字段？
3. 每个模型中多出来的字段用在哪里？
4. 补充数据迁移时序图

**Comment by yovafeng** [comment]
按照运营数据模块分析了各个数据查询方式，对可以加入TemplateInPipeline、InstanceInPipelin、ComponentInTemplate、ComponentExecuteData的字段进行了论证（https://adorable-run-37e.notion.site/d88990afb39c4003abb5c14fc46ce947）

下面是最新的表字段设置方案和数据迁移方案
https://adorable-run-37e.notion.site/83458c6ac9b74f88be588e9c71d0ae06

https://adorable-run-37e.notion.site/598109eb88ae4d6095f1e51e4c3ce36f

**Comment by homholueng** [comment]
1. project_name, template_name 这种可能会发生变化的值不需要记录到 db 中
2. 与 instance 相关的表记录 taskflow_id 与 pipeline_instance_id 
3. ComponentExecuteData 不需要记录 template_id 与 template_name
4. 迁移过程需要考虑到私有化版本，谁来负责实时和跟踪这个过程？

**Comment by yovafeng** [comment]
新的表字段设计
### TemplateInPipeline

1. template_id模版id
2. atom_total标准插件总数
3. subprocess_total子流程总数
4. gateways_total网关总数

---新增

1. project_id项目id
2. category所属分类
3. create_time创建时间
4. creator创建人

### InstanceInPipeline

1. instance_id任务实例id
2. atom_total标准插件总数
3. subprocess_total子流程总数
4. gateways_total网关总数

---新增

1. project_id项目id
2. template_id模板id
3. category所属分类
4. creator创建人
5. create_time创建时间
6. start_time开始时间
7. finish_time完成时间
8. elapsed_time执行耗时
9. create_method实例创建方式

### ComponentInTemplate

1. component_code组件编码
2. template_id模板id
3. node_id节点id
4. is_sub是否子流程引用
5. subprocess_stack子流程堆栈
6. version插件版本

---新增

1. project_id项目id
2. category模板所属分类
3. template_creator模板创建人
4. template_create_time模板创建时间

### ComponentExecuteData

1. component_code组件编码
2. instance_id：pipeline实例id
3. node_id节点id
4. is_sub是否子流程引用
5. subprocess_stack子流程堆栈
6. version插件版本
7. started_time:插件开始执行时间 
8. archived_time插件执行结束时间
9. elapsed_time插件执行耗时
10. status是否执行成功
11. is_skip是否跳过
12. is_retry是否重试记录

---新增

1. instance_create_time：实例创建时间
2. instance_finish_time：实例结束时间
3. instance_start_time：实例启动时间
4. project_id项目id
6. task_instance_id：task实例id

**Comment by homholueng** [comment]
模型名改下：

TemplateInPipeline -> TemplateStatistics
InstanceInPipeline -> TaskflowStatistics
ComponentInTemplate -> TemplateNodeTemplate
ComponentExecuteData - > TaskflowExecutedNodeStatistics
