### ISSUE TITLE
用户能够自行配置变量隐藏的触发逻辑

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4300]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

用户通过一个下拉框变量来控制 DB 变更的类型，对于 Oracle 和 MySQL 类型的 DB，变更是需要上传 SQL 文件（必填），如果用户在填参时选择了不变更 DB，这时候还是需要上传两个 SQL 文件

![image](https://user-images.githubusercontent.com/26020997/138245753-e4a379b5-3bf3-45d9-8f5f-0d087c25f004.png)

重现方法
=======

**Comment by normal-wls** [comment]
### 方案

该功能主要涉及以下页面变动和交互：

1. 变量编辑页面
2. 任务创建参数编辑页面

**变量编辑页面：**

![image-20211108164148047](https://user-images.githubusercontent.com/9864577/140741660-4fb716f8-c21e-46f9-abcc-93684326bced.png)

1. 显示的地方添加"符合条件时支持隐藏"选项，并支持配置条件。

2. 触发条件需增加相关提示，变量值目前均记录为字符串，所以值的类型差异可能会被忽略。重点支持依赖下拉框、文本框和输入框类型的变量。

3. 对于配置了显示类型为"符合条件时支持隐藏"的变量，对应生成的流程数据如下:

   ``` json
   {
     "show_type": "condition",
     "hide_condition": [
       {
         "constant_key": "${xxx}",
         "operator": "=",
         "value": "xxxxx"
       }
     ]
   }
   ```

**任务创建参数编辑页面：**

![image-20211108185746613](https://user-images.githubusercontent.com/9864577/140741725-2c0d648e-3124-4f4c-9867-bf886e50eb46.png)

1. 展示上：如果show_type没有condition的变量，则正常显示；如果有，则需要展示一个“刷新条件隐藏变量”的按钮，供用户进行手动刷新。同时，对于配置了可隐藏的变量，通过字段颜色进行区分，同时增加提示，可供用户快捷查看隐藏条件。
2. 在点击"刷新"按钮之后，前端请求get_constant_preview_result接口，将目前编辑页面中的变量值作为参数传递给接口，接口会基于传参的变量值，计算出所有的变量值返回，前端再基于返回值（需要转成字符串进行匹配），判断是否满足隐藏条件，如果满足，则进行隐藏。
