### ISSUE TITLE
支持用户配置模板列表的默认排序字段

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4354]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======
如题

**Comment by DomineCore** [comment]
#### 新增数据库：UserConfig

支持用户配置模板列表的默认排序字段，本质上是新增一个用户可控的配置项，在后续版本中可能会出现其它类似的用户配置项，所以直接新增一个UserConfig数据库用于保存系统中所有的用户自定义配置项，每次新增一个配置项需在此数据库中新增一个带有default的字段用于存储用户自定义配置信息。

#### 新增接口：get_user_config

新增一个get_user_config接口，前端可根据当前登录用户的username到后台查询此用户的自定义配置信息。

在本次规划中，按照以下的格式进行前后端数据交互：

**POST**：

```
{
	"username":"xxx"
}
```

**Response**:

```python
{
  "template_orderby_field":"template_id"
}
```

**Comment by DomineCore** [comment]
db的设计：每增加一个用户配置都增加一个带有默认值的字段，如图：
![image](https://user-images.githubusercontent.com/50765823/141798049-63d8a38d-d1a8-4962-a03e-e828e14551b0.png)

**Comment by DomineCore** [comment]
新增project_id字段，支持用户在项目级别控制自己的配置项

**Comment by DomineCore** [comment]
@luofann 
1、设置项目级用户配偶API
url: /user/set_userconf/  POST请求
post_body:
`{
    "username":"test",
    "field":"tasktmpl_ordering",
    "value":"-id",
    "project_id":12345
}`
response：
`
{
    "result": true,
    "data": null
}
`

**Comment by DomineCore** [comment]
RESTFUL api

 1、http://{HOST}/api/v4/user_custom_config/{project_id}/get/

根据project_id获取用户自定义配置字段  GET

example response

```python
{
    "result": true,
    "data": {
        "task_template_ordering": [
            {
                "name": "模板ID",
                "value": "id"
            },
            {
                "name": "创建时间",
                "value": "pipeline_template__create_time"
            },
            {
                "name": "修改时间",
                "value": "pipeline_template__edit_time"
            },
            {
                "name": "模板类型",
                "value": "category"
            }
        ]
    },
    "code": 0,
    "message": ""
}
```



2、http://{HOST}/api/v4/user_custom_config/{project_id}/set/

根据project_id设置用户自定义配置字段  POST

example request body：

```python
{
    "task_template_ordering": "-id"
  	# 设置task_template_ordering的值为category
}
```

example response

```python
{
    "result": true,
    "data": {
        "id": 2,
        "task_template_ordering": "-id",
        "username": "admin",
        "project_id": 3
    },
    "code": 0,
    "message": ""
}
```



3、http://{HOST}/api/v4/user_custom_config_options/{project_id}/get/?configs=task_template_ordering

example response

```python
{
    "result": true,
    "data": {
        "task_template_ordering": [
            {
                "name": "模板ID",
                "value": "id"
            },
            {
                "name": "创建时间",
                "value": "pipeline_template__create_time"
            },
            {
                "name": "修改时间",
                "value": "pipeline_template__edit_time"
            },
            {
                "name": "模板类型",
                "value": "category"
            }
        ]
    },
    "code": 0,
    "message": ""
}
```
