### ISSUE TITLE
运营数据-任务统计模块查询优化

### ISSUE THREAD

**Issue by DomineCore** [Tencent/bk-sops#4397]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

![wecom-temp-95f85df15de74fb60052d5c766af9f08](https://user-images.githubusercontent.com/50765823/140017717-b01ef114-f176-4530-91d4-03dc7620967e.png)

重现方法
=======

**Comment by yovafeng** [comment]
### 分项目统计面板

1、优化前后时间对比

- 优化前：0.023900747299194336
- 优化后：0.013646841049194336

2、优化手段

![image](https://user-images.githubusercontent.com/50765823/140017549-3c4e2a7a-5136-44c6-af81-6f32ab272a6a.png)

将taskflow_statistics_data提前用list(taskflow_statistics_data)执行查询，避免在循环中进行IO



### 任务详情面板

1、优化前后时间对比

- 优化前：0.07710099220275879
- 优化后：0.02135896682739257

2、优化手段

![image](https://user-images.githubusercontent.com/50765823/140017594-9f0478f8-980a-4a90-be47-90ef855d7e51.png)



### 分类统计面板

1、优化前后时间对比

- 优化前：0.013824224472045898
- 优化后：0.007786035537719726

2、优化手段

![image](https://user-images.githubusercontent.com/50765823/140017632-8e741f12-94c6-4d67-b17a-aa91bb3d7870.png)


### 分时间统计面板

1、优化前后时间对比

- 优化前：0.04837608337402344
- 优化后：0.01907491683959961

2、优化手段

![image](https://user-images.githubusercontent.com/50765823/140017668-5149cb8f-9e2d-4a72-988f-6ac6aeab0735.png)

**Comment by DomineCore** [comment]
<!DOCTYPE html><h3 cid="n790" mdtype="heading" class="md-end-block md-heading" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.17rem; margin: 0px 0px 1.5rem; font-family: &quot;Lucida Grande&quot;, Corbel, sans-serif; font-weight: bold; clear: both; word-wrap: break-word; padding: 0px; color: rgb(222, 222, 222); line-height: 1.5rem; letter-spacing: -1px; white-space: pre-wrap; position: relative; font-style: normal; font-variant-caps: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">按照当前的方案，将任务量提升到1w+后的查询时间前后对比</span></h3><p cid="n867" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin-top: 0px; margin-bottom: 1.5rem; word-wrap: break-word; white-space: pre-wrap; position: relative; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">其中，group_by_instance_node查询速度提升效果显著（约为20倍）</span></p><figure class="md-table-fig" cid="n796" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(184, 191, 198); color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(54, 59, 64); text-decoration: none;">

接口名 | 优化前(s) | 优化后(s)
-- | -- | --
group_by_project_id | 0.2970511913299560 | 0.1889460086822509
group_by_instance_node✅ | 0.8380658626556396 | 0.0453181266784668
group_by_instance_time | 0.1628129482269287 | 0.1781258583068847
group_by_category | 0.1434879302978515 | 0.1485109329223632

</figure>

**Comment by homholueng** [comment]
3，4 项的优化依据不成立，可打开 sql 日志进行对比
https://stackoverflow.com/questions/650238/how-to-show-the-last-queries-executed-on-mysql
