### ISSUE TITLE
配置子流程时，允许用户选择执行方案

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4418]
对于配置了执行方案的流程来说，如果无法在子流程节点中选择执行方案，那么这些流程作为子流程使用的价值就不大

## 目标

- 配置子流程节点时支持选择子流程的执行方案
- 根据选择的执行方案不同，渲染对应的子流程输入表单
- 执行方案编辑页面需要展示该执行方案被多少个流程引用了
- 被作为子流程引用的执行方案不允许删除

**Comment by wheel-w** [comment]
#### 一、前端选择子流程

1. 请求`api/v3/scheme/?template_id=10&project_id=1`获取子流程执行方案列表

   ```json
   {
     "result": true,
     "data": [
       {
         "id": 12,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
         "name": "方案2"
       },
       {
         "id": 13,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
         "name": "方案1"
       }
     ],
     "code": 0,
     "message": ""
   }
   ```

2. 请求`template/api/form/1/?template_id=10&version=d0ec13f65719f8e8700b001ad085f10d&` 获取需要渲染的表单数据

   ```json
   {
     "result": true,
     "data": {
       "form": {
         "${bk_timing}": {
           "name": "定时时间",
           "key": "${bk_timing}",
           "desc": "",
           "custom_type": "",
           "source_info": {
             "node2f17fb9ee5d08202a276d4400d75": [
               "${bk_timing}"
             ]
           },
           "source_tag": "sleep_timer.bk_timing",
           "value": "",
           "show_type": "show",
           "source_type": "component_inputs",
           "validation": "",
           "index": 0,
           "version": "legacy",
           "form_schema": {
             "type": "input",
             "attrs": {
               "name": "定时时间",
               "placeholder": "秒(s) 或 时间(%Y-%m-%d %H:%M:%S)",
               "hookable": true,
               "validation": [
                 {
                   "type": "required"
                 }
               ]
             }
           },
           "plugin_code": ""
         }
       },
       "outputs": {},
       "version": "d0ec13f65719f8e8700b001ad085f10d"
     },
     "message": "",
     "code": 0
   }
   ```

3. 判断需要渲染的表单变量的来源节点是否在当前执行方案的data数组里，如果在则渲染
   PS：即2的返回结果`data.form.source_info`的key是否在1的返回结果中的`item.data`数组中

4. 执行方案下拉列表位置

![image-20211227164341340](/Users/wheelwang/Library/Application Support/typora-user-images/image-20211227164341340.png)

**Comment by homholueng** [comment]
> #### 一、前端选择子流程
> 1. 请求`api/v3/scheme/?template_id=10&project_id=1`获取子流程执行方案列表
>    ```json
>    {
>      "result": true,
>      "data": [
>        {
>          "id": 12,
>          "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
>          "name": "方案2"
>        },
>        {
>          "id": 13,
>          "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
>          "name": "方案1"
>        }
>      ],
>      "code": 0,
>      "message": ""
>    }
>    ```
> 2. 请求`template/api/form/1/?template_id=10&version=d0ec13f65719f8e8700b001ad085f10d&` 获取需要渲染的表单数据
>    ```json
>    {
>      "result": true,
>      "data": {
>        "form": {
>          "${bk_timing}": {
>            "name": "定时时间",
>            "key": "${bk_timing}",
>            "desc": "",
>            "custom_type": "",
>            "source_info": {
>              "node2f17fb9ee5d08202a276d4400d75": [
>                "${bk_timing}"
>              ]
>            }
>          }
>        },
>        "outputs": {},
>        "version": "d0ec13f65719f8e8700b001ad085f10d"
>      },
>      "message": "",
>      "code": 0
>    }
>    ```
> 3. 判断需要渲染的表单变量的来源节点是否在当前执行方案的data数组里，如果在则渲染
>    PS：即2的返回结果`data.form.source_info`的key是否在1的返回结果中的`item.data`数组中
> 4. 前端将当前选中的执行方案赋值写入`pipeline_tree.activities`对应子流程需要跳过的节点，保存流程的时候一同传给后端
>    ```python
>    pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14.exclude_task_nodes_id = [node_id1,node_id2]
>    ```
> 5. 执行方案下拉列表位置
> 
> <img alt="image-20211227164341340" width="796" src="https://user-images.githubusercontent.com/61050624/147670508-c359037e-cdc4-4c1f-a796-c1a847434fcf.png">
> 
> #### 二、后端新建任务实例时，递归的根据子流程对应的`exclude_task_nodes_id` 过滤节点
> 1. 构造一个方法根据`exclude_task_nodes_id`跳过子流程对应的节点
>    ```python
>      def sub_process_exclude_task_nodes(pipeline_tree)
>      		"""
>      		递归获取pipeline中子流程对应执行方案对应的sub_pipeline
>      		"""
>            node_id = list(pipeline_tree["activities"].keys())[1]
>            sub_pipeline = pipeline_tree["activities"][node_id]["pipeline"]
>            exclude_task_nodes_id = [list(sub_pipeline["activities"].keys())[0]]
>            TaskFlowInstanceManager.preview_pipeline_tree_exclude_task_nodes(sub_pipeline, exclude_task_nodes_id)
>            
>            
>      def create_pipeline_instance(template, **kwargs):
>            pipeline_tree = kwargs["pipeline_tree"]
>            replace_template_id(template.__class__, pipeline_tree)
>            pipeline_template_data = {
>                "name": kwargs["name"],
>                "creator": kwargs["creator"],
>                "description": kwargs.get("description", ""),
>            }
>            PipelineTemplateWebWrapper.unfold_subprocess(pipeline_tree, template.__class__)
>    				
>            # 跳过子流程对应的执行方案
>            sub_process_exclude_task_nodes(pipeline_tree)
>            ...
>    
>            return pipeline_instance
>    ```
> 
> #### 三、需要确认的点
> 1. 引用子流程的父流程保存执行方案保存其方案id还是exclude_task_nodes_id
> 2. 如果直接在模版中存储`exclude_task_nodes_id` ,是否子流程的执行方案删除或者修改都不影响其父流程
> 3. `pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14` 是否可以直接增加字段属性,例如
>    ```python
>    pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14.exclude_task_nodes_id = [node_id1,node_id2]
>    
>    # 或者放到constants里
>    pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14.constants.exclude_task_nodes_id = [node_id1,node_id2]
>    ```

1. 选择执行方案后，应该调用 `gcloud.taskflow3.models.preview_template_tree` 根据执行方案传入剔除掉的节点来生成新的 constants 给到前端渲染新的表单
2. 流程描述 tree 中子流程节点配置存储执行方案 id 还是存储执行方案内节点 id，需要再考虑，存储节点 id 的话，需要考虑到执行方案更新的情况

**Comment by wheel-w** [comment]
#### 一、用户新建或者修改执行方案时,创建快照

1. 避免对之前的功能造成影响，保留原有的data属性，data里面为当前版本的方案数据
2. 新增snapshot属性，在用户更新或者创建执行方案的时候创建快照

```python
class TemplateScheme(models.Model):
    """
    模板执行方案
    """

    template = models.ForeignKey(
        PipelineTemplate, verbose_name=_("对应模板 ID"), null=False, blank=False, on_delete=models.CASCADE
    )
    unique_id = models.CharField(_("方案唯一ID"), max_length=97, unique=True, null=False, blank=True)
    name = models.CharField(_("方案名称"), max_length=64, null=False, blank=False)
    edit_time = models.DateTimeField(_("修改时间"), auto_now=True)
    
    data = CompressJSONField(verbose_name=_("方案数据"))
    
    # 修改数据库增加执行方案的快照，可以为空
    snapshot = models.ForeignKey(
      Snapshot, 
      verbose_name=_("执行方案节点数据"),
      related_name="snapshot_scheme",    
      on_delete=models.DO_NOTHING,
      blank=True,
      null=True,
    )
		
    def create()：
        Snapshot.objects.create_snapshot(structure_data)
    
    def update():
        Snapshot.objects.create_snapshot(structure_data)
    	
    @property
    def version(self):
        return self.snapshot.md5sum
```



#### 二、前端在获取执行方案列表的时候，返回的列表带上版本号

1. 请求`api/v3/scheme/?template_id=10&project_id=1` 返回

   ```json
   {
     "result": true,
     "data": [
       {
         "id": 12,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
         "name": "方案2",
         # 新增版本返回
         "version":"xxxxxx"
       },
       {
         "id": 13,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
         # 新增版本返回
         "version":"xxxxxx"
       }
     ],
     "code": 0,
     "message": ""
   }
   ```

   

#### 三、前端选择子流程

1. 请求`api/v3/scheme/?template_id=10&project_id=1`获取子流程当前最新的执行方案列表

   ```json
   {
     "result": true,
     "data": [
       {
         "id": 12,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
         "version":"xxxxxx"
         "name": "方案2"
       },
       {
         "id": 13,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
         "version":"xxxxxx"
         "name": "方案1"
       }
     ],
     "code": 0,
     "message": ""
   }
   ```

2. 请求`/taskflow/api/preview_task_tree/{project_id}/` 获取preview_task_tree的constants渲染表单变量

   1. 请求体

      ```
      {
        "version": "f9aef24985a56b1061beff8f1edb04e2",
        "template_id": 27,
        "exclude_task_nodes_id": [],
        "template_source": "project"
      }
      ```

   2. 响应体

      ```json
      {
        "result": true,
        "data": {
          "pipeline_tree": {
            "activities": {
              "node50436fe619f23b4d638b95806a92": {
      			...
            "constants": {
              "${bk_timing}": {
                "name": "定时时间",
                "key": "${bk_timing}",
                "desc": "",
                "custom_type": "",
                "source_info": {
                  "node50436fe619f23b4d638b95806a92": [
                    "bk_timing"
                  ]
                },
                "source_tag": "sleep_timer.bk_timing",
                "value": "",
                "show_type": "show",
                "source_type": "component_inputs",
                "validation": "",
                "index": 0,
                "version": "legacy",
                "form_schema": {
                  "type": "input",
                  "attrs": {
                    "name": "定时时间",
                    "placeholder": "秒(s) 或 时间(%Y-%m-%d %H:%M:%S)",
                    "hookable": true,
                    "validation": [
                      {
                        "type": "required"
                      }
                    ]
                  }
                },
                "plugin_code": ""
              }
            },
          "constants_not_referred": {}
        }
      }
      ```

      

   

3. 前端将当前选中的执行方案的对应执行方案的id和版本写入`pipeline_tree.activities`中的对应子流程节点

   ```python
    pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14.scheme ={
             "id":1,
             "version":"f9aef24985a56b1061beff8f1edb04e2"
      }
   ```

   

4. 执行方案下拉列表位置，选择完成之后禁用下拉选框，

   1. 点击重新选择执行方案按钮重新选择执行方案
   2. 同步当前执行方案按钮点击替换当前id对应的方案最新版本
     <img width="798" alt="image-20211231121408494" src="https://user-images.githubusercontent.com/61050624/147803763-eeae4f3f-5367-4a2f-b138-51eaeb6e34c4.png">



#### 四、后端新建任务实例时，递归的根据子流程对应的执行方案id和版本过滤节点

1. 构造一个方法根据`exclude_task_nodes_id`跳过子流程对应的节点

2. 如果该流程没有执行方案相关参数，默认执行全部节点

   ```python
     def sub_process_exclude_task_nodes(pipeline_tree)
     		"""
     		递归获取pipeline中子流程对应执行方案对应的sub_pipeline
     		"""
           node_id = list(pipeline_tree["activities"].keys())[1]
           sub_pipeline = pipeline_tree["activities"][node_id]["pipeline"]
           exclude_task_nodes_id = [list(sub_pipeline["activities"].keys())[0]]
           # 获取执行方案对应版本的节点数据
           task_nodes = TemplateScheme.objects.get(id=scheme.id,version=scheme.version).data
           
           # 如果勾选了使用最新执行方案，获取最新版本的节点数据
           task_nodes = TemplateScheme.objects.get(id=scheme.id).data
          
           # 根据task_nodes获取需要剔除的节点
           exclude_task_nodes_id = task_nodes...
           
           TaskFlowInstanceManager.preview_pipeline_tree_exclude_task_nodes(sub_pipeline,   		       exclude_task_nodes_id)
           
           
     def create_pipeline_instance(template, **kwargs):
           pipeline_tree = kwargs["pipeline_tree"]
           replace_template_id(template.__class__, pipeline_tree)
           pipeline_template_data = {
               "name": kwargs["name"],
               "creator": kwargs["creator"],
               "description": kwargs.get("description", ""),
           }
           PipelineTemplateWebWrapper.unfold_subprocess(pipeline_tree, template.__class__)
   				
           # 跳过子流程对应的执行方案
           sub_process_exclude_task_nodes(pipeline_tree)
           ...
   
           return pipeline_instance
   ```

#### 五、子流程或者执行方案更新

1. 修改流程模版关系,新增子流程引用的scheme_id和version

   ```python
   class TemplateRelationship(models.Model):
       """
       流程模板引用关系：直接引用
       """
   
       ancestor_template_id = models.CharField(_("根模板ID"), max_length=32, db_index=True)
       descendant_template_id = models.CharField(_("子流程模板ID"), max_length=32, null=False, db_index=True)
       subprocess_node_id = models.CharField(_("子流程节点 ID"), max_length=32, null=False)
       version = models.CharField(_("快照字符串的md5"), max_length=32, null=False)
       always_use_latest = models.BooleanField(_("是否永远使用最新版本"), default=False)
       
       # 新增
   		scheme_id = models.IntegerField(_"子流程引用的执行方案id")
       scheme_version = models.IntegerField(_"子流程引用的执行方案版本")
   
       objects = TemplateRelationShipManager()
   ```

2. 修改检查子流程更新的逻辑,如果引用的执行方案有更新，也提醒用户及时更新

   ```python
       def check_templates_subprocess_expired(self, tmpl_and_pipeline_id):
           # fetch all template relationship in template_ids
           pipeline_tmpl_ids = [item["pipeline_template_id"] for item in tmpl_and_pipeline_id]
           subproc_infos = TemplateRelationship.objects.filter(ancestor_template_id__in=pipeline_tmpl_ids)
   
           # get all subprocess reference template's version
           subproc_templ = [info.descendant_template_id for info in subproc_infos]
           tmpl_versions = TemplateCurrentVersion.objects.filter(template_id__in=subproc_templ)
   
           # comparison data prepare
           tmpl_version_map = {ver.template_id: ver.current_version for ver in tmpl_versions}
           tmpl_id_map = {item["pipeline_template_id"]: item["id"] for item in tmpl_and_pipeline_id}
   
           # compare
           subproc_expired_templ = set()
           for info in subproc_infos:
               if info.descendant_template_id not in tmpl_version_map or info.always_use_latest:
                   continue
               if info.version != tmpl_version_map.get(info.descendant_template_id):
                   subproc_expired_templ.add(info.ancestor_template_id)
   
           return [tmpl_id_map[pid] for pid in subproc_expired_templ]
   ```

   

#### 五、说明

   用户选择之后子流程执行方案之后，会取执行方案中的节点数组和子流程全部节点的交集作为要执行的节点，和当前执行方案的概念保持一致

**Comment by wheel-w** [comment]
<!DOCTYPE html><h4 cid="n298" mdtype="heading" class="md-end-block md-heading md-focus" style="box-sizing: border-box; break-after: avoid-page; break-inside: avoid; orphans: 4; font-size: 1.25em; margin-top: 1rem; margin-bottom: 1rem; position: relative; font-weight: bold; line-height: 1.4; cursor: text; white-space: pre-wrap; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-style: normal; font-variant-caps: normal; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;">六、操作影响</span></h4><figure class="md-table-fig" cid="n303" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none;">

模版操作 | 执行方案操作 | 对子流程节点的影响
-- | -- | --
添加节点 | 增加节点 | 1. 把执行方案固化在这个节点上 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，不受子流程更新影响 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：新的执行方案的节点和旧的子流程节点，取交集执行，如果执行方案添加为原来模版的节点，则会执行，添加模版新增的节点不会执行 更新子流程：新的子流程全部节点和新的执行方案取交集执行，执行方案新增节点会执行 3. 记录id和版本 没有更新子流程&&没有更新执行方案版本：按照原来的执行方案和子流程，不影响 没有更新子流程&&更新执行方案版本：旧的子流程和新的执行方案取交集执行，执行方案添加为原来模版的节点，则会执行 更新子流程&&没有更新执行方案版本：按照原来的执行方案执行，不受子流程更新影响 更新子流程&&更新执行方案版本：新的子流程全部节点和新的执行方案版本取交集执行，执行方案新增节点会执行
添加节点 | 删除节点 | 1. 把执行方案固化在这个节点上 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，不受子流程更新影响 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：新的执行方案的节点和旧的子流程节点交集，执行方案删除的节点不会被执行 更新子流程：新的子流程全部节点和新的执行方案取交集执行，执行方案删除的节点不会被执行，模版新增的节点也不会执行 3. 记录id和版本 没有更新子流程&&没有更新执行方案版本：按照原来的执行方案和子流程，不影响 没有更新子流程&&更新执行方案版本：新的执行方案的节点和旧的子流程节点交集，执行方案删除的节点不会被执行 更新子流程&&没有更新执行方案版本：按照原来的执行方案执行，不受子流程更新影响 更新子流程&&更新执行方案版本：新的子流程全部节点和新的执行方案取交集执行，执行方案删除的节点不会被执行，模版新增的节点也不会执行
添加节点 | 无操作 | 1. 把执行方案固化在这个节点上 没有更新子流程：按照原来的执行方案，添加的节点不会执行 更新子流程：按照原来的执行方案，添加的节点不会执行 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：按照原来的执行方案，添加的节点不会执行 更新子流程：按照原来的执行方案，添加的节点不会执行 3. 记录id和版本 没有更新子流程：按照原来的执行方案，添加的节点不会执行 更新子流程：按照原来的执行方案，添加的节点不会执行
删除节点 | 增加节点 | 1. 把执行方案固化在这个节点上 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，子流程删除节点为不会执行 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：新的执行方案的节点和旧的子流程节点，取交集执行，如果执行方案添加节点会执行，模版删除节点也会执行 更新子流程：新的子流程全部节点和新的执行方案取交集执行，执行方案新增节点会执行，模版删除节点不会执行 3. 记录id和版本 没有更新子流程&&没有更新执行方案版本：按照原来的执行方案和子流程，不影响 没有更新子流程&&更新执行方案版本：新的执行方案的节点和旧的子流程节点，取交集执行，如果执行方案添加节点会执行，子流程删除节点也会执行 更新子流程&&没有更新执行方案版本：按照原来的执行方案执行，子流程删除节点为不会执行 更新子流程&&更新执行方案版本：新的子流程全部节点和新的执行方案版本取交集执行，执行方案新增节点会执行，模版删除节点不会执行
删除节点 | 删除节点 | 1. 把执行方案固化在这个节点上 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，子流程删除节点不会执行，执行方案删除的节点会执行 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：新的执行方案的节点和旧的子流程节点，取交集执行，执行方案删除的节点不会执行，模版删除的节点如果在执行方案里则会执行 更新子流程：新的子流程全部节点和新的执行方案取交集执行，执行方案删除的节点和子流程删除的节点都不会执行 3. 记录id和版本 没有更新子流程&&没有更新执行方案版本：按照原来的执行方案和子流程，不影响 没有更新子流程&&更新执行方案版本：新的执行方案的节点和旧的子流程节点，取交集执行，执行方案删除的节点不会执行，模版删除的节点如果在执行方案里则会执行 更新子流程&&没有更新执行方案版本：按照原来的执行方案执行，子流程删除节点不会执行，执行方案删除的节点会执行 更新子流程&&更新执行方案版本：新的子流程全部节点和新的执行方案取交集执行，执行方案删除的节点和子流程删除的节点都不会执行
删除节点 | 无操作 | 1. 把执行方案固化在这个节点上 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，子流程删除节点不会执行 2. 记录 id，直接跟着子流程的执行方案走 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，子流程删除节点不会执行 3. 记录id和版本 没有更新子流程：原有的子流程和原有的执行方案保持不变，不影响 更新子流程：按照原来的执行方案执行，子流程删除节点不会执行
增加变量 | 增加节点 | 1. 把执行方案固化在这个节点上 不更新子流程：不影响 更新子流程：需要填写子流程表单的值，非当前 2. 记录 id，直接跟着子流程的执行方案走 不更新子流程：不影响 更新子流程：需要填写子流程表单的值 3. 记录id和版本 不更新子流程：不影响 更新子流程：需要填写子流程表单的值
增加变量 | 删除节点 | 1. 把执行方案固化在这个节点上 不更新子流程：不影响 更新子流程：需要填写子流程表单的值 2. 记录 id，直接跟着子流程的执行方案走 不更新子流程：不影响 更新子流程：需要填写子流程表单的值 3. 记录id和版本 不更新子流程：不影响 更新子流程：需要填写子流程表单的值
增加变量 | 无操作 | 1. 把执行方案固化在这个节点上 不更新子流程：不影响 更新子流程：需要填写子流程表单的值 2. 记录 id，直接跟着子流程的执行方案走 不更新子流程：不影响 更新子流程：需要填写子流程表单的值 3. 记录id和版本 不更新子流程：不影响 更新子流程：需要填写子流程表单的值
删除变量 | 增加节点 | 1. 把执行方案固化在这个节点上 模版删除变量不影响 子流程不会执行执行方案新增的节点 2. 记录 id，直接跟着子流程的执行方案走 模版删除变量不影响 引用该执行方案的子流程都会执行增加的节点 3. 记录id和版本 模版删除变量不影响 没有更新执行方案版本：执行方案增加节点不会执行 更新执行方案版本：执行方案增加节点会执行
删除变量 | 删除节点 | 1. 把执行方案固化在这个节点上 模版删除变量不影响 子流程还是会执行删除的节点 2. 记录 id，直接跟着子流程的执行方案走 模版删除变量不影响 所有的引用该执行方案的子流程都不会执行删除的节点 3. 记录id和版本 模版删除变量不影响 没有更新执行方案版本：执行方案删除节点会执行 更新执行方案版本：执行方案删除节点不会执行
删除变量 | 无操作 | 1. 把执行方案固化在这个节点上 不影响 2. 记录 id，直接跟着子流程的执行方案走 不影响 3. 记录id和版本 不影响
无操作 | 增加节点 | 1. 把执行方案固化在这个节点上 子流程不会执行执行方案新增的节点 2. 记录 id，直接跟着子流程的执行方案走 引用该执行方案的子流程都会执行增加的节点 3. 记录id和版本 没有更新执行方案版本：执行方案增加节点不会执行 更新执行方案版本：执行方案增加节点会执行
无操作 | 删除节点 | 1. 把执行方案固化在这个节点上 子流程还是会执行删除的节点 2. 记录 id，直接跟着子流程的执行方案走 所有的引用该执行方案的子流程都不会执行删除的节点 3. 记录id和版本 没有更新执行方案版本：执行方案删除节点会执行 更新执行方案版本：执行方案删除节点不会执行
无操作 | 无操作 | 无影响

</figure>

**Comment by wheel-w** [comment]
#### 一、前端选择子流程

1. 选择子流程节点并打开，请求`api/v3/scheme/?template_id=10&project_id=1`获取执行方案列表

   ```json
   {
     "result": true,
     "data": [
       {
         "id": 12,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
         "name": "方案2",
       },
       {
         "id": 13,
         "data": "	       [\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
       }
     ],
     "code": 0,
     "message": ""
   }
   ```

2. 请求`/taskflow/api/preview_task_tree/{project_id}/` 获取preview_task_tree的constants渲染子流程表单作为必填项，constants_not_referred，removed_constants 的字段设置为非必填
   PS: preview_task_tree接口请求新增scheme_id_list执行方案列表
         响应新增removed_constants，删除的变量

   1. 请求体

      ```json
      {
        "version": "f9aef24985a56b1061beff8f1edb04e2",
        "template_id": 27,
        "exclude_task_nodes_id": [],
        # 新增请求体
        "scheme_id_list":[1,2,4]，
        "template_source": "project"
      }
      ```

   2. 响应体，

      ```json
      {
        "result": true,
        "data": {
          "pipeline_tree": {
            "activities": {
              "node50436fe619f23b4d638b95806a92": {
      			...
            "constants": {
              "${bk_timing}": {
                "name": "定时时间",
                "key": "${bk_timing}",
                "desc": "",
                "custom_type": "",
                "source_info": {
                  "node50436fe619f23b4d638b95806a92": [
                    "bk_timing"
                  ]
                },
                "source_tag": "sleep_timer.bk_timing",
                "value": "",
                "show_type": "show",
                "source_type": "component_inputs",
                "validation": "",
                "index": 0,
                "version": "legacy",
                "form_schema": {
                  "type": "input",
                  "attrs": {
                    "name": "定时时间",
                    "placeholder": "秒(s) 或 时间(%Y-%m-%d %H:%M:%S)",
                    "hookable": true,
                    "validation": [
                      {
                        "type": "required"
                      }
                    ]
                  }
                },
                "plugin_code": ""
              }
            },
          "constants_not_referred": {},
          # 新增响应值
           "removed_constants""{}
        }
      }
      ```

   3. 选择执行方案之后，再次请求preview_task_tree重新渲染表单

   4. 保存子流程节点，将执行方案的id列表写入`pipeline_tree.activities`中的对应子流程节点

      ```json
       pipeline_tree.activities.node1353c2ed2aca1fa67dc4bc73ef14.scheme_id_list =[1,2,3,4]
      ```

   5. 原型图
  
<img width="794" alt="wecom-temp-713a9a5b15ec67d8c5c5a9646591adc5" src="https://user-images.githubusercontent.com/61050624/148158374-097243c4-e21d-4cbd-80ab-f968704914d2.png">


#### 二、后端新建任务实例时，递归的根据子流程对应的执行方案id过滤节点

1. 构造一个方法根据`exclude_task_nodes_id`跳过子流程对应的节点

2. 如果该流程没有执行方案相关参数，默认执行全部节点

   ```python
     def sub_process_exclude_task_nodes(pipeline_tree)
     		"""
     		递归获取pipeline中子流程对应执行方案对应的sub_pipeline
     		"""
           node_id = list(pipeline_tree["activities"].keys())[1]
           sub_pipeline = pipeline_tree["activities"][node_id]["pipeline"]
           exclude_task_nodes_id = [list(sub_pipeline["activities"].keys())[0]]
           # 获取执行方案对应版本的节点数据
           task_nodes = TemplateScheme.objects.in_bulk(ids=[1,3,4,5]
          
           # 根据task_nodes获取需要剔除的节点
           exclude_task_nodes_id = task_nodes...
           
           TaskFlowInstanceManager.preview_pipeline_tree_exclude_task_nodes(sub_pipeline,   		       exclude_task_nodes_id)
           
           
     def create_pipeline_instance(template, **kwargs):
           pipeline_tree = kwargs["pipeline_tree"]
           replace_template_id(template.__class__, pipeline_tree)
           pipeline_template_data = {
               "name": kwargs["name"],
               "creator": kwargs["creator"],
               "description": kwargs.get("description", ""),
           }
           PipelineTemplateWebWrapper.unfold_subprocess(pipeline_tree, template.__class__)
   				
           # 跳过子流程对应的执行方案
           sub_process_exclude_task_nodes(pipeline_tree)
           ...
   
           return pipeline_instance
   ```

#### 三、执行方案有子流程引用禁止删除

1. 修改流程模版关系，新增scheme_id_list属性

   ```python
   class TemplateRelationship(models.Model):
       """
       流程模板引用关系：直接引用
       """
   
       ancestor_template_id = models.CharField(_("根模板ID"), max_length=32, db_index=True)
       descendant_template_id = models.CharField(_("子流程模板ID"), max_length=32, null=False, db_index=True)
       subprocess_node_id = models.CharField(_("子流程节点 ID"), max_length=32, null=False)
       version = models.CharField(_("快照字符串的md5"), max_length=32, null=False)
       always_use_latest = models.BooleanField(_("是否永远使用最新版本"), default=False)
       
       # 新增
   		scheme_id_list = models.IntegerField(_"子流程引用的执行方案id列表")
   
       objects = TemplateRelationShipManager()
   ```

2. 保存父流程流程模版的时候，保存对应的scheme_id_list到TemplateRelationship

3. 执行方案编辑页面请求`api/v3/scheme/?template_id=10&project_id=1`获取模版列表时新增子流程引用数返回，引用数`sub_quote_num`大于0则不允许删除执行方案

   ```json
   {
     "result": true,
     "data": [
       {
         "id": 12,
         "data": "[\"nodeee45ba42027ab55da4a1e7fec2bf\"]",
         # 子流程引用数
         "sub_quote_num":22,
         "name": "方案2",
       },
       {
         "id": 13,
         # 子流程引用数
         "sub_quote_num":2,
         "data": "	       [\"nodeee45ba42027ab55da4a1e7fec2bf\",\"node2f17fb9ee5d08202a276d4400d75\"]",
       }
     ],
     "code": 0,
     "message": ""
   }
   ```

4. 执行方案编辑页面修改
  
<img width="629" alt="image-20220105115445532" src="https://user-images.githubusercontent.com/61050624/148158328-27a52520-1803-4412-8b24-ded8e90778bb.png">

**Comment by homholueng** [comment]
> 保存子流程节点，将执行方案的id列表写入pipeline_tree.activities中的对应子流程节点
保存执行方案的 id 即可，不应该保存执行方案的 id 列表
