### ISSUE TITLE
运行python manage.py migrate，报错“ImportError: failed to find libmagic.  Check your installation”

### ISSUE THREAD

**Issue by gaoleizi1986** [Tencent/bk-sops#450]
问题描述
=======

我在git下载标准运维安装包到本地工程目录，依据git上的说明操作，执行到python manage.py migrate这一步的时候，出现报错如下：
  File "C:\gaolei\bk_demo\bk-sops\gcloud\contrib\appmaker\api.py", line 16, in <module>
    import magic
  File "C:\gaolei\bk_demo\venv\lib\site-packages\magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
 

我尝试了网上的方法
pip uninstall python-magic 
pip install python_magic_bin-0.4.14-py2.py3-none-win32.whl  问题依旧出现；
也尝试了如下办法：
pip uninstall python-magic 
pip install python-magic-bin == 0.4.14  依然无解 

我的pip list如下：
(venv) C:\gaolei\bk_demo\bk-sops>pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package               Version
--------------------- -----------
amqp                  1.4.9
anyjson               0.3.3
asn1crypto            0.24.0
billiard              3.3.0.23
celery                3.1.25
certifi               2019.3.9
cffi                  1.12.3
chardet               3.0.4
coverage              4.5.1
cryptography          2.3.1
Django                1.11.11
django-celery         3.2.2
django-guardian       1.4.8
django-haystack       2.4.1
django-nose           1.4.5
django-tastypie       0.13.3
django-timezone-field 3.0
enum34                1.1.6
factory-boy           2.11.1
Faker                 1.0.7
funcsigs              1.0.2
functools32           3.2.3.post2
httplib2              0.9.1
idna                  2.7
ipaddress             1.0.22
jsonschema            2.5.1
kombu                 3.0.37
libmagic              1.0
Mako                  1.0.6
MarkupSafe            1.0
mock                  2.0.0
nose                  1.3.7
pbr                   5.2.1
pip                   19.1.1
pyasn1                0.4.5
pycparser             2.19
PyMySQL               0.9.3
pyparsing             2.2.0
python-dateutil       2.8.0
python-magic          0.4.15
python-mimeparse      1.6.0
pytz                  2016.6.1
redis                 2.10.6
redis-py-cluster      1.3.5
requests              2.20.0
rsa                   3.4.2
setuptools            41.0.1
setuptools-scm        1.11.1
six                   1.12.0
suds                  0.4
text-unidecode        1.2
ujson                 1.35
urllib3               1.24.3
wheel                 0.33.4

**Comment by homholueng** [comment]
麻烦提在 issue 描述中提供一下标准运维的版本号

**Comment by gaoleizi1986** [comment]
标准运维的版本号:3.3.15
Python 版本号:Python 2.7.11
Windows 版本:windows server 2016 datacenter

**Comment by homholueng** [comment]
> 标准运维的版本号:3.3.15
> Python 版本号:Python 2.7.11
> Windows 版本:windows server 2016 datacenter

当前 windows 系统是 32 位还是 64 位，`python_magic_bin` 有针对两种类型的包：https://pypi.org/project/python-magic-bin/0.4.14/#files。

另外，当前的操作是否是在 Python 虚拟环境下进行的？如果不是，请尝试创建一个 Python 虚拟环境并在该虚拟环境下重新进行安装操作。

**Comment by gaoleizi1986** [comment]
> > 标准运维的版本号：3.3.15 
> > Python版本号：Python 2.7.11 
> > Windows版本：windows server 2016 datacenter
> 
> 当前windows系统是32位还是64位，`python_magic_bin`有针对两种类型的包：[https](https://pypi.org/project/python-magic-bin/0.4.14/#files)：//pypi.org/project/python-magic-bin/0.4.14/#files[](https://pypi.org/project/python-magic-bin/0.4.14/#files)
> 
> 参考：[tyiannak / pyAudioAnalysis＃128（评论）](https://github.com/tyiannak/pyAudioAnalysis/issues/128#issuecomment-377873472)
> 
> 另外，当前的操作是否是在Python虚拟环境下进行的？如果不是，请尝试创建一个Python虚拟环境并在该虚拟环境下重新进行安装操作

本地开发环境的py-magic版本要求是0.4.15，你提供的方法行不通，会报错；已经尝试新建python虚拟环境重新操作，问题依旧

**Comment by gaoleizi1986** [comment]
我查资料输入pip install python-libmagic后运行通过此步骤，又报如下错误： 

 File "C:\gaolei\bk_demo\venv_test\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

另外，我仔细对比过 requirements.txt文件，本地环境完全符合符合要求

**Comment by homholueng** [comment]
> > > 标准运维的版本号：3.3.15
> > > Python版本号：Python 2.7.11
> > > Windows版本：windows server 2016 datacenter
> > 
> > 
> > 当前windows系统是32位还是64位，`python_magic_bin`有针对两种类型的包：[https](https://pypi.org/project/python-magic-bin/0.4.14/#files)：//pypi.org/project/python-magic-bin/0.4.14/#files
> > 参考：[tyiannak / pyAudioAnalysis＃128（评论）](https://github.com/tyiannak/pyAudioAnalysis/issues/128#issuecomment-377873472)
> > 另外，当前的操作是否是在Python虚拟环境下进行的？如果不是，请尝试创建一个Python虚拟环境并在该虚拟环境下重新进行安装操作
> 
> 本地开发环境的py-magic版本要求是0.4.15，你提供的方法行不通，会报错；已经尝试新建python虚拟环境重新操作，问题依旧

你指的报错报的是什么错误呢？麻烦提供一下错误信息
