### ISSUE TITLE
Worker 内存占用/泄漏问题排查

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4537]
关键信息
=======

- [ ] bk-sops 版本：3.10.2

**Comment by normal-wls** [comment]
1. 已找到对应触发问题的流程，该流程通过api进行频繁调用，且每个任务中使用ip选择器会加载非常多业务下ip，所以导致worker内存快速增长。
2. 解决方案：1. 目前已将该流程下任务切换至v2引擎，降低v1引擎worker的压力。2. 优化ip选择器，只拉取尽量少的ip。
