### ISSUE TITLE
运营数据支持第三方插件统计

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4541]
1. 运营数据-标准插件统计-插件统计面板支持暂时第三方插件的引用次数
2. 运营数据-标准插件统计-流程引用详情，支持对第三方插件进行过滤
3. 运营数据-标准插件统计-任务执行详情，支持对第三方插件进行过滤

**Comment by DomineCore** [comment]
#### 目前无法实现对第三方插件运营数据统计的原因

##### 1、插件引用次数

保存运营数据-插件数据时未对第三方插件code和version做特殊化保存，而是直接保存了remote_plugin作为第三方插件的code，造成所有的第三方插件都被存储为remote_plugin

##### 2、流程引用详情和任务引用详情

前端下拉框中的数据仅仅获取了系统内置插件的code和version，没有加入第三方插件的



#### 如何解决

##### 1、插件引用次数

**要改进的：**

- 当流程和任务发生post_save动作时对应的保存流程和任务运营数据的task中对pipeline_tree中的第三方插件code和version做特殊处理
- 计算“插件引用次数”的api中要新增：根据第三方插件code获取name的逻辑，补充上对第三方插件执行次数的统计

##### 2、流程引用详情和任务引用详情

**要改进的api：**

- 在/api/v3/component/的返回结果中注入第三方插件的相关信息

**Comment by homholueng** [comment]
建议 TemplateNodeStatistics 与 TaskNodeStatistics 表中增加一个字段来标志来节点使用的是否是第三方插件，因为使用 remote_plugin 前缀 + code 的方式也没办法完全避免内置插件 code 与第三方插件 code 的冲突

**Comment by DomineCore** [comment]
#### 一、数据模型的更改

##### 1、TemplateNodeStatistics

新增is_remote字段，默认值为false，用于标识当前记录是否第三方插件

![image-20211125115656562](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125115656562.png)

##### 2、TaskExecutedNodeStatistics

新增is_remote字段，默认值为false，用于标识当前记录的插件是否第三方插件

![image-20211125115608761](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125115608761.png)

#### 二、运营数据存储逻辑的更改

标准运维插件的运营数据包括两部分：

- 流程引用数据（TemplateNodeStatistics表）
- 任务执行数据（TaskExecutedNodeStatistics表）

这两组数据，分别来自于TaskTemplate的保存动作、TaskFlowInstance的状态更改动作。

这两个关键动作发生后，调起相应的task来更新这两张数据表。

为了适配第三方插件，所以需要更改对应的task存储逻辑，旧的存储逻辑是遍历整个pipeline_tree来扫描到流程/任务中的插件，并进行存储。

**对比内置插件和第三方插件的pipeline_tree:**

![image-20211125122323632](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125122323632.png)

从图中展示的pipeline_tree差异可以看出，我们在解析两种流程数据的时候，需要采用不同的取值策略来取插件的code和version进行存储，按照如下的方案进行适配：

![image-20211125123110528](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125123110528.png)

另外，在代码中除了对code和version的处理，还有对is_remote的处理。

#### 三、插件运营数据计算逻辑的更改（适配插件引用次数统计）

在group_by_atom_cite中，对插件引用次数的计算，需要新增对第三方插件的处理逻辑。

![image-20211125123836778](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125123836778.png)

这一块逻辑负责从TemplateNodeStatistics表中计算出所有插件（code+version）出现的次数，由于我们在前面的存储task中已经做了第三方插件被流程引用数据的存储适配，所以这一块逻辑我们依然保持不变，需要更改的是format_component_name(插件名的格式化)。

插件名如何得到：

- 系统内置插件：从ComponentModel中根据插件的code和version查询出name
- 第三方插件：需调用plugin_client的get_paas_plugin_info接口从paas平台获取插件信息，然后再提取出name

所以，在插件引用次数计算的处理分支中，只需要增加对第三方插件名的获取逻辑。

#### 四、拉取插件resource的API更改（适配下拉框）

拉取插件resource的接口用于在前端展示一个包含所有插件的下拉框，但是目前该api仅仅返回了系统内置插件。

![image-20211125124714583](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125124714583.png)

为了让这里支持用第三方插件进行筛选，我们需要在当前api的返回数据中注入第三方插件的name、code、version。并且加上is_remote=True字段，用于标识第三方插件。

如何获取第三方插件的信息呢？同样使用plugin_client.get_paas_plugin_info来获取。

#### 五、group_by_atom_template和group_by_atom_instance的更改（适配下拉框）

![image-20211125125205350](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211125125205350.png)

以上两个api会在选择“标准插件”下拉框后被调用，它的作用是根据插件的code、version进行筛选插件流程和任务信息。

为了支持对第三方插件的支持（也就是防止出现第三方插件与内置插件code相同的情况），需要在请求参数中加入一个is_remote字段，用来标识是否第三方插件（具体的值从第四条说明的更改中获取）
