### ISSUE TITLE
节点超时及超时后处理策略配置功能

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4554]
## 原型

![image](https://user-images.githubusercontent.com/26020997/143824182-f50d653c-6c1b-4351-96f2-f4b3fb1006fd.png)

## 设计稿

app/JaLz6ifN/specs/design/mDjyJRHQ7

## 功能

- 允许用户配置节点超时时间，单位为秒
- 同时能够配置节点超时后的处理策略【强制失败/强制失败后跳过】
- 节点超时时间达到后，触发超时处理动作

**此处需要注意，超时处理的业务逻辑是否会与失败处理的业务逻辑冲突**

**Comment by normal-wls** [comment]
## 节点执行超时方案设计

**Model**

添加一张超时节点的配置和状态表:

| 字段         | 类型     |
| :----------- | -------- |
| id           | bigint   |
| node_id      | str      |
| create_time  | datetime |
| timeout      | int      |
| is_confirmed | bool     |
| is_timeout   | bool     |

特别说明两个字段：

is_confirmed代表该节点状态是否被确认，为False则需要放入超时候选队列。

is_timeout代表改节点是否已经触发超时条件。



**实现**

总的来说，节点执行超时功能属于延迟事件触发的范畴，目前实现延时队列的几种方案有：消息队列延迟消息、时间轮盘、Redis过期通知、Redis Zset。在这几种方案中，目前拟定采用Redis zset的方案来实现该功能，对比如下：

| 对比方案                 | 理由                                                         |
| ------------------------ | ------------------------------------------------------------ |
| zset vs 消息队列延迟消息 | 功能场景中，存在大量取消延迟事件的操作（如节点正常执行结束），队列不支持直接从队列中撤回消息，所以会导致队列中延迟消息数=正在等待超时节点数。 |
| zset vs 时间轮盘         | 时间轮盘的bucket数不好确定，且对于取消超时消息的情况处理的复杂度和效率也不高。 |
| zset vs Redis过期通知    | Redis过期通知功能默认不开启；如果大量key同时过期，可能会存在阻塞。 |

 通过zset方案，插入、删除的时间都是O(logN)，N为当前正在执行中且未到达超时状态的节点数，效率上是可接受的。



**消息流转**
![image](https://user-images.githubusercontent.com/9864577/145180256-72000906-a55b-4e8d-aa9c-49bfddbe6461.png)
1. 节点执行/执行完毕时，会往数据库更新对应配置及状态，同时更新Redis中节点池(增删)
2. 如果Redis服务故障后恢复，可以从数据库的状态表中进行节点池数据初始化。
3. 通过周期任务定期扫描超时的节点
4. 对于超时节点，首先更新数据库中对应状态(is_timeout)，然后触发超时处理消息，投递到队列，时间处理后续由超时消费者进行消费。



**超时消费**

对于超时节点，通过以下操作进行超时处理：

1. 判断节点对应State状态是否为Running、Process是否正在执行且当前节点为自身。
2. 读取超时策略，根据超时测试进行对应处理。



**超时处理和失败处理逻辑**

超时处理计划支持"强制失败"和"强制失败后跳过"，这个地方不与"失败处理"进行联动。与"自动忽略"和"失败自动重试"功能互斥，这个需要在前端进行校验和提示，后端在创建任务时默认关闭这两个失败处理选项。

****

**Comment by normal-wls** [comment]
pipeline_tree相关节点超时选项格式:
``` python
 "activities": {
      "act_1": {
          "type": "ServiceActivity",
          "timeout_config": {"enable": True, "seconds": 2, "action": "forced_fail"},
      },
      "act_2": {
          "type": "ServiceActivity",
          "timeout_config": {"enable": True, "seconds": 2, "action": "forced_fail_and_skip"},
      },
  }
```
