### ISSUE TITLE
测试环境导出的流程(含子流程)，导入到生产环境选择新建流程，导入报错。

### ISSUE THREAD

**Issue by Chace-wang** [Tencent/bk-sops#4563]
关键信息
=======

- bk-sops 版本：v3.6.33

问题描述
=======
1. 测试环境导出的流程，导入到生产环境选择新建流程，无法导入，出现报错：invalid flow data or error occur,please contact administrator
![image](https://user-images.githubusercontent.com/34097844/142793319-2ebc97d0-2773-4137-9333-16a1b5af37eb.png)
![image](https://user-images.githubusercontent.com/34097844/142793343-652279c2-6a70-4d72-a5dd-e483eaabe1c3.png)

重现方法
=======
1. 测试环境新建一个流程A，导出，然后"点覆盖相同ID"导入到生产环境
2. 测试环境新建一个流程B，选择子流程，引用子流程A，导出，然后点“新建流程”导入到生产环境，即可复现。

[A-覆盖相同ID.dat.docx](https://github.com/Tencent/bk-sops/files/7578077/A-.ID.dat.docx)
[B-新建.dat.docx](https://github.com/Tencent/bk-sops/files/7578078/B-.dat.docx)
（上传不了.dat文件，把docx后缀去掉即可）

**Comment by homholueng** [comment]
请提供有问题的两个 DAT 文件供排查

**Comment by Chace-wang** [comment]
经验证，3.6.49版本已修复该问题
