### ISSUE TITLE
标准运维快速执行脚本的任务强制失败后，job任务链接为空

### ISSUE THREAD

**Issue by Chace-wang** [Tencent/bk-sops#4564]
关键信息
=======

- [ ] bk-sops 版本：3.6.33(新版本也存在)

问题描述
=======
标准运维快速执行脚本的任务强制失败后，job任务链接为空
![image](https://user-images.githubusercontent.com/34097844/142793994-e6282ac6-40dc-4775-8691-54eafe6cd3ba.png)

重现方法
=======
1. 新建一个作业平台快速脚本执行的流程，脚本里sleep 500
2. 新建任务并执行，然后强制失败，查看输出参数为空
看源码，功能未考虑该场景输出job链接
![image](https://user-images.githubusercontent.com/34097844/142794080-f3325f0c-9d38-4db7-8779-2ceceee9b509.png)

**Comment by homholueng** [comment]
强制失败动作执行时，节点动作执行的位置是未知的（JOB 执行脚本的请求可能未提交），故无法保证一定有期望的输出
