### ISSUE TITLE
插件表单面板增加渲染豁免配置选项

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4566]
## 设计稿

app/JaLz6ifN/specs/design/AbqTHTJGa

## 功能描述

- 为每个独立表单项增加一个【渲染豁免】的选项，用户勾选渲染豁免后，该表单项不会在执行时进行模板变量渲染
- 【勾选】与【渲染豁免】两个 checkbox 互斥，不允许同时勾选
- 只需要在 V2 引擎上实现该功能

## 实现细节

- 前端需要向后台传递 need_render 字段来标识该字段是否需要进行渲染
- 后台需要调整 `pipeline.eri.runtime._data_inputs_assemble` 方法中对于 need_render 的赋值逻辑

**Comment by DomineCore** [comment]
_data_inputs_assemble方法的末尾新增从前端传递过来的need_render字段中决定是否render的逻辑
![image](https://user-images.githubusercontent.com/50765823/145175874-2e39eef7-cf26-4925-9b1f-9de9845535b2.png)

**Comment by normal-wls** [comment]
需添加【勾选】与【渲染豁免】冲突情况的后端校验

**Comment by ealldy** [comment]
@homholueng 
请问该功能解决哪些场景下的问题？

**Comment by DomineCore** [comment]
@ealldy 可以考虑如下场景：当前流程中有一个全局变量a，要想在插件中引用全局变量就需要使用${a}，这样会把a的值进行解析并填充。现在有一个需要：在快速执行脚本插件中，有一个和全局变量引用相同的字符串${a}，这个时候我需要按照字符串原本的内容进行输出为`${a}`而不是全局变量a的value。就可以使用该功能，对变量进行渲染豁免即可原样输出。有点类似于python字符串的r前缀的概念。

**Comment by ealldy** [comment]
@DomineCore 
此场景下，是对全局变量a进行渲染豁免吗？
