### ISSUE TITLE
未执行或已完成的任务隐藏【全局变量】按钮

### ISSUE THREAD

**Issue by hlilhuang** [Tencent/bk-sops#4592]
![image](https://user-images.githubusercontent.com/93375471/143198721-b0824e52-bfe9-430b-9701-9f70f93a1c60.png)

**Comment by ywywZhou** [comment]
![image](https://user-images.githubusercontent.com/67539158/143801564-e381a877-2dd8-4825-889c-1ded49fff6c3.png)
