### ISSUE TITLE
get_common_list 和 get_common_template_list 等获取资源列表的 API 增加返回用户对流程拥有哪些操作权限

### ISSUE THREAD

**Issue by jayjiahua** [Tencent/bk-sops#4605]
监控平台会对标准运维的任务列表进行展示，希望能够获取到对哪些流程有查看和执行权限。可类似于Web端API，提供一个auth_actions 字段表示当前用户具有该资源的哪些权限

**Comment by DomineCore** [comment]
### 标准运维注册在蓝鲸权限中心统一管理的资源

1. project：项目
2. flow：流程模板
3. task：任务实例
4. common_flow：公共流程
5. mini_app：轻应用
6. periodic_task：周期任务
7. clocked_task：计划任务



### 标准运维开放于apigw的资源拉取API

1. get_common_template_list （获取公共流程）
2. get_functionalization_task_list （获取职能化任务）
3. get_periodic_task_list （获取周期任务）
4. get_plugin_list（获取插件）
5. get_task_list（获取任务实例）
6. get_template_list （获取流程）
7. get_user_project_list （获取用户有权限的项目）



### 以上两个的交集：需要新增“auth_actions”字段的api

1. get_common_template_list（获取公共流程）
2. get_periodic_task_list（获取周期任务）
3. get_task_list（获取任务实例）
4. get_template_list（获取流程模板）



### 可直接使用的utils

gcloud.iam_auth.utils

1. get_resources_allowed_actions_for_user：获取某个用户对某个资源的操作权限
2. get_flow_allowed_actions_for_user：获取某个用户对某些流程（TaskTemplate）的操作权限
3. get_common_flow_allowed_actions_for_user：获取某个用户对某些公共流程的（CommonTemplate）操作权限



### 要新增的utils

gcloud.iam_auth.utils

1. get_task_allowed_actions_for_user：获取某个用户对某些任务实例（TaskInstance）的操作权限
2. get_periodic_task_allowed_actions_for_user：获取某个用户对某些周期任务（PeriodicTask）的操作权限



### 向api返回结果中注入auth_actions（有权限的操作）

![image-20211207150450672](/Users/fengyafei/Library/Application Support/typora-user-images/image-20211207150450672.png)
