### ISSUE TITLE
画布渲染性能问题排查

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4618]
## 模板

template/edit/5000113/?template_id=26127

## 问题

- 画布拖动帧数较低，拖动操作不跟手
- 打开略缩视图时会卡顿
- 在略缩视图上拖动帧数也比较低

**Comment by luofann** [comment]
- #### 打开缩略图卡顿
![image](https://user-images.githubusercontent.com/44999219/144534097-a42e9437-71a7-4ab8-a320-e4057ea015e5.png)
原因：前端生成图片需要花费一定的时间，如果节点元素比较多的话，等待时间会比较长
解决方案：在交互层面优化，点击缩略图按钮后直接展示弹层，然后加文字说明或者动画效果

- #### 拖动不跟手、缩略图拖动帧数低

原因：画布直接拖动和缩略图拖动是调用的相同处理逻辑，所以原因是相同的。通过浏览器的性能分析面板可以看到，每次拖动画布的时候，浏览器的scritpt 和 rending 的时间占用比较多，大致原因是计算过程占用时间较多，导致浏览器的painting需要等待计算完成才能执行。
![image](https://user-images.githubusercontent.com/44999219/144535212-db16314d-885d-462e-8967-3528bf9c7104.png)
![image](https://user-images.githubusercontent.com/44999219/144535788-1bbd982b-9fc4-44fa-9381-ff44cdd17f42.png)


解决方案：相对好优化的方向就是减少script的计算时间，排查在拖动画布的时候，vue组件的watch是否有深层次的更新，是否改所有画布元素的坐标的行为。

**Comment by brookylin** [comment]
打开缩略图卡顿问题，目前先在交互层面优化，点击缩略图按钮后直接展示弹层，然后加上loading动画。

**Comment by luofann** [comment]
#4745 已优化画布组件的watch逻辑，去掉深层嵌套的监听；改写了vue组件的移动时画布位置变更的方式，之前画布外层的移动会导致所有节点slot重新渲染，现修改为通过改变dom的style属性来渲染整体位置。
变更前：
![image](https://user-images.githubusercontent.com/44999219/146703393-afe7d036-32e6-4ec1-b7ef-2c10a2dda974.png)
