### ISSUE TITLE
浏览器 tab icon 中，支持区分执行中的任务和已经暂停（任务暂停，节点暂停）的任务

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4621]
![image](https://user-images.githubusercontent.com/26020997/147427976-3ea9adb0-2c0d-47d8-9870-ed8a509340b8.png)

目前浏览器 tab 中的任务状态展示没有办法区分【运行中】和【暂停中】的任务，需要对暂停中的任务提供对应的 icon 并展示

**Comment by normal-wls** [comment]
### 修改方案
1. 设计
依旧采用图标右下角颜色的方式来进行表示，需要设计师确定一个颜色来表示暂停状态，然后给到一份icon文件给到前端使用
目前表示的颜色：
灰色：未执行
绿色：已成功
黄色：执行中
红色：执行失败

2. 前端
前端需要增加对流程SUSPENDED的判断。
分为两种情况：
1. 任务暂停：status返回的状态树中，根节点的状态为SUSPENDED或者NODE_SUSPENDED，则标记当前任务为暂停状态。
2. 暂停节点：status返回的状态树中，需要收集状态为RUNNING的节点，同时记录下node_id之后，到流程树中寻找对应node_id的节点，判断该节点类型是否为暂停节点，如果是，则将当前任务状态标记为暂停状态。
