### ISSUE TITLE
下拉框支持手动新增输入值功能优化

### ISSUE THREAD

**Issue by normal-wls** [Tencent/bk-sops#4627]
问题描述
=======

目前下拉框支持手动新增输入值新增功能，有用户反馈只希望能基于现有配置在选项中进行筛选，新增输入值可能会导致填参输错问题。

基于master

**Comment by normal-wls** [comment]
目前有以下优化方向（图片只用于功能示例，非实现效果）：
1. 组件目前会在未匹配下拉框选项时将输入值作为一个选项展示，此时需要在输入值选项旁边添加对应提示。
![image](https://user-images.githubusercontent.com/9864577/143976021-abe7ca06-732a-4e71-8f0c-c643de3f2936.png)
2. 支持输入值选项添加配置，同时支持配置方、使用方进行配置，逻辑如下：
  - 下拉框配置方可以在下拉框配置页面配置“是否允许添加输入值”和对应的“输入值校验逻辑”，默认分别为“是”和“空”(不校验)。
  ![image](https://user-images.githubusercontent.com/9864577/143977071-d5a09d1c-cd56-4b72-9957-3c9de673811b.png)
  -  对于配置方允许添加输入值的下拉框，在使用时会展示“是否允许添加输入值”的切换按钮，使用方可以根据自己的使用场景进行切换。
    ![image](https://user-images.githubusercontent.com/9864577/143976840-87e176cd-1d01-4454-bc2e-7c4433fcc244.png)

**Comment by homholueng** [comment]
是否能够做到只在子流程表单中支持输入任意值
