### ISSUE TITLE
本地开发环境调试的话, 能否搭建paas和cmdb的docker单机版本来调试?

### ISSUE THREAD

**Issue by mmaotai** [Tencent/bk-sops#4660]
docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
docker run -d --name="bk-paas" -p 8000-8003:8000-8003 ccr.ccs.tencentyun.com/bk.io/paas-standalone:latest

本地环境搭建太麻烦了, sops依赖的应该只有paas和cmdb吧.  搭建了好长时间额, 还没搞好.

**Comment by homholueng** [comment]
sops 依赖的组件最小集理论上需要：paas，esb，cmdb

请详细描述一下目前存在的问题，以便我们提供建议和帮助🤝

**Comment by mmaotai** [comment]
我只想本地跑一下sops的代码，并不想花很多精力去搭建其他依赖组件（主要是电脑卡），有没有办法其它组件一键docker启动，sops就可以跑起来了。

**Comment by mmaotai** [comment]
cmdb和paas它们文档里都有极速体验的docker版，我发现它们并不能帮助我解决启动sops依赖问题   
我注释了sops的authentication中间件不想让去做复杂的认证了，但没法同步到项目，页面提示让去iam里授权，还要启一个iam吗
