### ISSUE TITLE
项目流程列表排序方式体验优化

### ISSUE THREAD

**Issue by DomineCore** [Tencent/bk-sops#4698]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

![image](https://user-images.githubusercontent.com/50765823/145369835-1f4160a3-6ac9-40af-8712-42d5a6ac3905.png)
![image](https://user-images.githubusercontent.com/50765823/145369854-27d2f991-7a78-441e-91f8-28d414528e2c.png)

重现方法
=======

**Comment by ecoli666** [comment]
公共流程管理页，支持默认排序表头设置，能力与普通流程管理保持一致
