### ISSUE TITLE
tastypie切换至drf方案梳理

### ISSUE THREAD

**Issue by DomineCore** [Tencent/bk-sops#4729]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======
项目中旧的app广泛使用tastypie来实现rest api，但是tastypie活跃度逐渐降低，未来可能会有潜在的风险，需要切换至drf来规避

重现方法
=======

**Comment by DomineCore** [comment]
#### 1、各app-API框架使用情况

使用tastypie的app数量：10

**gcloud下：**

- Analysis_statistics：None
- Apigw：django
- clocked_task：drf
- common_template：django+tastypie ✅
- contrib.admin：django
- contrib.analysis：django
- contrib.appmaker：django
- contrib.collection：tastypie ✅
- contrib.develop：django
- contrib.function：tastypie ✅
- contrib.operate_record：drf
- core：
  - gcloud.core.resources：tastypie ✅
- external_plugins：tastypie ✅
- iam_auth：django
- label：drf
- periodictask：tastypie ✅
- project_constants：drf
- Taskflow3：drf、django、tastypie ✅
- Tasktmpl3：drf、django、tastypie ✅
- template_base：drf、django、tastypie ✅
- user_custom_config：drf

**其他：**

- pipeline_service：drf
- weixin：tastypie ✅



#### 2、前端需要同步修改的

##### 2.1 交互协议的变化

请求参数和请求url保持不变

- 获取资源list类api：meta+objects--->result+data+code
- 新建资源类api：裸数据--->result+data+code
- 编辑资源类api：裸数据--->result+data+code

#### 3、权限混入 

1、统一使用gcloud.core.apis.drf.viewsets.utils.IAMMixin做viewset的权限管理

2、每个资源封装对应的IamResourceHelper，实现get_resources和get_resources_id（继承自iam.contrib.tastypie.resource.IAMResourceHelper)，作为IAMMinx的iam_resource_helper属性，和IAMMixin配合实现权限校验

73、每个viewset实现各自的permssion_class，实现has_permission和has_object_permission方法来完成权限校验（在方法中调用IAMMixin的iam_auth_check方法）

#### 4、过滤器

采用django-filter作为drf的filter_backends，并为每个resource给出一些filterset_fields，此处的filterset_fields与tastypie的filtering保持一致

#### 5、LimistOffset分页

统一使用drf内置LimitOffsetPagination来处理资源分页

#### 6、使用drf公共响应

使用gcloud.core.apis.drf.viewsets.APIMixin进行统一的响应结构处理

#### 7、序列化器

为每个resource实现若干序列化器处理请求和响应（要保证不改变原有的请求参数）

**Comment by normal-wls** [comment]
a. 2.1协议变化再细化一下，最好能以某个具体资源为例，展示字段的修改，对于前端需要修改的内容定义过于模糊，建议单独列出具体修改的点，最好给样例。
b. 从tastypie到drf的过程，需要细化各个tastypie的钩子函数(如alter_list_data_to_serialize、alter_detail_data_to_serialize、build_filters等)逻辑在drf中如何改造，是有通用化改造方案还是需要针对每个资源进行单独改造。
c. 需确认tastypie接口基类GCloudModelResource中定义的逻辑是否需要在DRF接口中用到，如果是需要给出方案。
d. 改动涉及到的资源类型较多，建议根据由易到难的顺序进行排序，计划好修改顺序。

**Comment by DomineCore** [comment]
### tastypie切换drf：以common_template为例



本文将以common_template（公共流程）为例，描述从tastypie切换至common_template所需改造的代码细节。

首先，使用ModelViewSet实现一个最简单的common_template接口：

```python
class CommonTemplateViewset(ModelViewSet):
    queryset = CommonTemplate.objects.all()
    serializer_class = CommonTemplateSerializer

```

```python
class CommonTemplateSerializer(serializers.ModelSerializer):
    
    class Meta:
        model = CommonTemplate
        fields = "__all__"
```

下面以list接口为例，从响应所需的字段来一步步完善它。

##### 1、为响应结果添加上name、create_time等位于pipeline_template外键的字段

所需的响应字段：id、name、category、creator_name、editor_name、create_time、edit_time、pipeline_tree、template_id、subprocess_info、version、subprocess_has_update、has_subprocess、description、notify_receivers、notify_type、time_out

**非属性字段序列化**

drf的序列化器Meta.fields属性不仅可以支持读取Model的字段属性，也支持读取Model的非字段属性property，上面的大部分字段在CommonTemplate的property中有相应的实现，所以直接写进fields就好。

**外键字段序列化**

在响应字段中存在一个description字段，并没有通过在CommonTemplate中实现property的方式来读取，在这里如果想实现对description的序列化，有两种方式可选：

1、新建一个description的property

```python
@property
def description(self):
  return self.pipeline_template.description
```

2、使用serializers.ReadOnlyField配合source属性读取

```python
class CommonTemplateSerializer(serializers.ModelSerializer):
    
    description = serializers.ReadOnlyField(source="pipeline_template.description")
    class Meta:
        model = CommonTemplate
        fields = [
            "id",
            "pipeline_template",
            "name",
            "category",
            ······
        ]
    
```

此时、已经具备了所有需要的响应字段。

##### 2、添加ViewSet过滤器

common_template要求使用以下字段进行过滤：

```python
"id"
"category"
"name"
"pipeline_template"
"subprocess_has_update"
"has_subprocess"
```

在这里选择使用django-filter作为filter_backend，由于django-fliter目前不支持对于非字段属性的过滤，此处以上字段划分为三类进行处理：

1、字段属性：id、category、pipeline_template

2、非字段属性：subprocess_has_update(既不是子类Model的字段也不是父类Model的)

3、外键字段：name、has_subprocess

其中字段属性(1)和外键字段(3)可以通过自定义FilterSet的方式实现过滤

```python
class CommonTemplateFilterSet(FilterSet):

    # 外键filter
    has_subprocess = filters.BooleanFilter(
        field_name="pipeline_template__has_subprocess",
        lookup_expr="exact"
    )
    name = filters.CharFilter(
        field_name="pipeline_template__name",
        lookup_expr="icontains"
    )

    class Meta:
        model = CommonTemplate
        # 直接filter
        fields = {
            "id": ["exact"], 
            "category": ["exact"], 
        }
```

外键字段定义在FilterSet的类属性中，字段属性定义在FilterSet.Meta.fields字段中

###### 对于非字段属性的特殊处理

对于非字段属性subprocess_has_update、由于不能直接在QuerySet中构建filters去数据库进行过滤，只能在查出目标数据集之后再进行一次过滤来实现，从请求开始到结束，数据的处理大致分为以下几个阶段：

过滤--->排序--->分页--->序列化

此处选择在分页之前增加一个非字段属性过滤的钩子，再次进行过滤，也就是以下的数据流：

过滤--->排序--->**非字段属性过滤**--->分页--->序列化

##### 3、非字段属性(property)过滤钩子设计(对应gcloud.commons.tastypie.paginators)

由于项目中所有的资源类api均使用limit+offset的形式来进行资源分页，此处选择在drf内置分页器LimitOffsetPagination的基础上进行改造实现非字段属性过滤的钩子

LimitOffsetPagination在它的paginate_queryset函数中处理分页，此处也可选择在paginate_queryset函数开始时添加钩子：

```python
    def paginate_queryset(self, queryset, request, view):
        
        self.limit = self.get_limit(request)
        if self.limit is None:
            return None
          
        # 非字段属性过滤↓↓↓
        filter_items = []
        for prop, field in self.properties().items():
            if prop in request.query_params.keys():
                prop_value = request.query_params[prop]
                filter_items.append({"p": prop, "v": field().to_python(value=prop_value)})

        queryset = self.filter_queryset_by_property(filter_items, queryset)
				# 非字段属性过滤↑↑↑
        self.count = self.get_count(queryset)
        self.offset = self.get_offset(request)
        self.request = request
        if self.count > self.limit and self.template is not None:
            self.display_page_controls = True

        if self.count == 0 or self.offset > self.count:
            return []
        return list(queryset[self.offset:self.offset + self.limit])
      
  def properties(self):
        return {"subprocess_has_update": BooleanField}
```

在此处添加的钩子负责从properties方法中获取到我们预先定义的要进行过滤的非字段属性及其FieldType，并根据请求内容构造出filter_items:

```python
filter_items：
{
  "p":"subprocess_has_update","v":True
}
```

接下来，将queryset和filter_items交给非字段属性过滤器filter_queryset_by_property来处理并得到过滤后的数据集queryset：

```python
def filter_queryset_by_property(self, filter_items, queryset):
        if not filter_items:
            return

        filtered = []

        for obj in queryset:

            for item in filter_items:
                # 防止脏数据引发异常
                if not hasattr(obj, item["p"]):
                    break
                if getattr(obj, item["p"]) != item["v"]:
                    break
            else:
              	# 将符合过滤条件的数据加入新的数据集filtered
                filtered.append(obj)

        return filtered
```

到此，已经实现了非字段属性+字段属性+外键字段属性的过滤。

以上对于非字段属性过滤的逻辑可以抽象为一个PropertyFilterPagination放置在gcloud.commons.drf.pagination中定义，以供所有的资源便捷地支持非字段属性过滤。

##### 4、操作鉴权和auth_actions注入(对应iam.contirb.tastypie)

**操作鉴权**

对于resource的鉴权，可以通过drf的permissions来实现：

实现has_permission和has_object_permission

```python
class ClockedTaskPermissions(IAMMixin, permissions.BasePermission):
    actions = {
        "list": IAMMeta.COMMON_FLOW_VIEW_ACTION,
        "create": IAMMeta.COMMON_FLOW_CREATE_ACTION
     		 ···
    }

    def has_permission(self, request, view):
        ······

    def has_object_permission(self, request, view, obj):
        ······

```

**auth_actions注入**

在list action中，可以通过重写list的方式在响应字段中注入auth_actions：

```python
def list(self, request, *args, **kwargs):
        # 注入auth_actions字段
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        data = serializer.data
        # 获取有权限的actions
        common_flow_id_list = []
        for common_flow in data:
            common_flow_id_list.append(common_flow["id"])
        common_templates_allowed_actions = get_common_flow_allowed_actions_for_user(
            request.user.username,
            COMMON_FLOW_ACTIONS,
            common_flow_id_list,
        )
        # 将auth_actions注入响应
        for common_flow in data:
            common_flow_id = common_flow["id"]
            common_flow.setdefault("auth_actions",[])
            for action, allowed in common_templates_allowed_actions.get(str(common_flow_id), {}).items():
                if allowed:
                    common_flow["auth_actions"].append(action)
        return Response(data)

```

 由于以上鉴权和注入auth_actions的方式通用性强，可抽象与权限中心iam-python-sdk的contrib里实现drf相关的iam-mixin：

在iam.contrib.resources中实现一些列drf操作的IamResourceMixin实现统一的auth_actions注入

#### 5、公共的时间和日期序列化器字段（对应gcloud.commons.tastypie.serializer)

在tastypie实现中，存在一个AppSerializer来处理所有resource的时间字段格式化，为了保持一致，方便各app处理时间字段序列化，结合drf的特点选择使用公共的时间和日期序列化器字段来实现：

```python
class GcloudDateTimeFiled(DateTimeFiled):
  def __init__(self, format=empty, input_formats=None, default_timezone=None, **kwargs):
    # 统一的时间和日期格式
    format="%Y-%m-%d %H:%M:%S"
    super().__init__(format=format, input_formats=None, default_timezone=None, **kwargs)
```

在后面的所有app中，如果有对时间字段的序列化处理，均使用此处定义的GcloudDateTimeField

**Comment by feifeizhao4754** [comment]
开发顺序
第一期：
BusinessResource -> GCloudModelResource
ProjectResource -> GCloudModelResource
ComponentModelResource -> GCloudModelResource
VariableModelResource -> GCloudModelResource
CommonProjectResource -> GCloudModelResource
LabelGroupModelResource -> GCloudModelResource
LabelModelResource -> GCloudModelResource
UserProjectResource -> GCloudModelResource
AdminPeriodicTaskHistoryResource -> GCloudModelResource
FunctionTaskResource -> GCloudModelResource
CollectionResources -> ModelResource
PackageSourceResource -> Resource
SyncTaskResource -> GCloudModelResource

第二期：
CommonTemplateResource -> GCloudModelResource
CommonTemplateSchemeResource -> GCloudModelResource
TaskTemplateResource -> GCloudModelResource
TaskFlowInstanceResource -> GCloudModelResource
AppMakerResource -> GCloudModelResource
PeriodicTaskResource -> GCloudModelResource
WxTaskTemplateResource -> TaskTemplateResource
WxTaskFlowInstanceResource -> TaskFlowInstanceResource
WxComponentModelResource -> ComponentModelResource
WxVariableModelResource -> VariableModelResource
WxTemplateSchemeResource -> TemplateSchemeResource
WxUserProjectResource -> UserProjectResource
WxProjectResource -> ProjectResource
WxCollectionResource -> CollectionResources
