### ISSUE TITLE
JOB 执行作业/脚本后 根据步骤执行标签获取 IP 分组

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4740]
## 描述

JOB 会根据传入 job_success 的参数对执行 IP 进行分组

![image](https://user-images.githubusercontent.com/26020997/146324355-203d151a-758a-46de-8a45-8dc543dee40c.png)

插件表单增加一个提取 IP 分组的开关，用户打开后，在作业执行完成时通过 `jobv3.get_job_instance_status` 返回的 `job_instance.step_ip_reult_list.tag` 来对本次执行的 IP 进行分组，输出到 `tagged_ip` 输出变量中，以 tag 为 key，`,` 连接的 ip 为值

**Comment by wheel-w** [comment]
#### 涉及变更插件
**这些插件都继承了JobService,需要确认是否都要进行该配置**
 - 执行作业
 - 全业务执行作业
 - 快速执行脚本
 - 全业务快速执行脚本
 - 分发本地文件
 - 快速分发文件
#### 前端表单实现加一个radio开关，默认打开
#### 后端方案
1. 新增一个函数,传入job_instance_id获取tagged_ip
```
def get_job_tagged_ip(bk_biz_id,job_instance_id):
     kwargs = {
        "job_instance_id": job_instance_id,
        "bk_biz_id": bk_biz_id,
        "return_ip_result": True,
    }
    result = client.jobv3.get_job_instance_status(kwargs)
    # 遍历`result.step_ip_result_list`
    tagged_ip_list = []
    for item in result.step_ip_result_lis:
         # 根据返回的exit_code拿到对应的状态描述和返回的tag还有IP拼成一个tagged_ip
        #  比如exit_code为0，则用执行成员拼接
          tagged_ip_list.append("{}({}),{}".format(item.exit_code,item.tag,item.ip)))
   
  return tagged_ip_list
```
2. 修改JobService的schedule方法
```
 def schedule(self, data, parent_data, callback_data=None):
        is_show_tagged_ip=data.get_one_of_inputs("is_show_tagged_ip",None)
        # 没有配置的不受影响
        if is_show_tagged_ip:
           get_job_tagged_ip()
           # 设置输出
```
3. 前端表单新增一个radio是否显示tagged_ip,默认展示

**Comment by homholueng** [comment]
> #### 涉及变更插件
> **这些插件都继承了JobService,需要确认是否都要进行该配置**
> 
> * 执行作业
> * 全业务执行作业
> * 快速执行脚本
> * 全业务快速执行脚本
> * 分发本地文件
> * 快速分发文件
> 
> #### 方案
> 1. 新增一个函数,传入job_instance_id获取tagged_ip
> 
> ```
> def get_job_tagged_ip(bk_biz_id,job_instance_id):
>      kwargs = {
>         "job_instance_id": job_instance_id,
>         "bk_biz_id": bk_biz_id,
>         "return_ip_result": True,
>     }
>     result = client.jobv3.get_job_instance_status(kwargs)
>     # 遍历`result.step_ip_result_list`
>     tagged_ip_list = []
>     for item in result.step_ip_result_lis:
>          # 根据返回的exit_code拿到对应的状态描述和返回的tag还有IP拼成一个tagged_ip
>         #  比如exit_code为0，则用执行成员拼接
>           tagged_ip_list.append("{}({}),{}".format(item.exit_code,item.tag,item.ip)))
>    
>   return tagged_ip_list
> ```
> 
> 2. 修改JobService的schedule方法
> 
> ```
>  def schedule(self, data, parent_data, callback_data=None):
>         is_show_tagged_ip=data.get_one_of_inputs("is_show_tagged_ip",None)
>         # 没有配置的不受影响
>         if is_show_tagged_ip:
>            get_job_tagged_ip()
>            # 设置输出
> ```
> 
> 3. 前端表单新增一个radio是否显示tagged_ip,默认展示

以下插件支持该功能即可

- 执行作业
- 全业务执行作业
- 快速执行脚本
- 全业务快速执行脚本

需要确认的问题：

tag ip 在标准输出变量提取前还是提取后？能否放到一起做？

其他

- 如果用户不使用该功能，也需要写入对应的输出字段，且值为空字典
- 该功能默认关闭
