### ISSUE TITLE
IAM SDK 升级至 APIGW 版本并进行兼容性调整

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#4940]
1. 蓝鲸权限中心 目前内部上云版已经全面对接了APIGateway, 容器化7.0 版本也会全面支持; 未来不会存在直连+走 ESB 调用的区分, 只需要对接 APIGateway  目前 python/go/php sdk已经做了兼容, 明年上半年可能会推各个接入方升级sdk, 并且做兼容(企业版 3.x 还是二进制部署, 没有新版 APIGateway)

**Comment by DomineCore** [comment]
目前已做：
1、注入APIGW环境变量
2、升级iam-python-sdk至1.1.20
3、可支持使用APIGW、ESB调用权限中心（APIGW优先级高于ESB）
