### ISSUE TITLE
项目流程允许引用公共流程模板

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#5142]

**Comment by normal-wls** [comment]
# 标准运维项目流程引用公共流程功能方案



## 背景&目标

目前，公共流程只能通过单一页面直接在对应项目中新建任务。用户希望能够直接在项目流程中引用公共流程，这样可以方便地完成对公共流程的复用，从而更加体现其”公共“的特性。

所以，希望公共流程能够做到以下两点：

1. 公共流程编辑者可以配置公共流程的使用范围（1期不做，暂时保持全体公开）
2. 公共流程可以直接在项目流程编辑页面被引用

## 方案

### 现有方案

现有方案中，如果一个方案引用子流程，流程树记录形式如下：

``` json
"node853c75da3b8ef5d608d936407e81": {
  "constants": {},
  "hooked_constants": [],
  "id": "node853c75da3b8ef5d608d936407e81",
  "incoming": [],
  "loop": null,
  "name": "new20220304071455",
  "optional": true,
  "outgoing": "",
  "stage_name": "",
  "template_id": 366,
  "version": "0ebcaafd5ad59c2a02eee099633932d6",
  "type": "SubProcess",
  "labels": [],
  "always_use_latest": false
}
```

可见，在通过pipeline_tree生成对应任务时，其通过template_id和version定位到对应的子流程流程树，合成生成的任务数据。

### 新方案调整

1. 流程树修改：为了能够在项目流程中引用公共流程，需要对流程树进行改造，记录引用的子流程是公共流程还是项目流程，所以，前端需要在子流程节点的流程树中添加流程类型的表示："template_type": "common"/"project"，对于没有该字段的旧数据，一律按照project处理。
2. 公共流程编辑过程修改（1期不做）：
   1. 支持编辑使用范围：增加一个新的模型CommonTemplateProjectRelationship，字段有common_template_id(int)和project_id(int)，两个字段分别建立索引，同时两个字段加上联合唯一约束
   2. 在创建或删除公共流程、修改使用范围时后端需要同时处理关系表数据
3. 子流程添加过程修改：
   1. 除了保持目前拉取同项目流程列表，前端需要增加拉取公共流程列表的请求逻辑，后端会提供一个新的拉取接口，支持根据project_id过滤出全部业务可见和该project_id下可见的公共流程（1期只需直接拉取公共流程列表即可）。此处前端需要置灰没有公共流程查看权限的公共流程。
4. 创建任务过程修改：
   1. 需要修改创建任务时子流程相关节点用到template_id从TaskTemplate模型中取值的函数，这些函数需要增加从子流程字段中获取template_type，然后从对应的Model中取值的逻辑，经过梳理有以下函数：
      1. gcloud.template_base.utils.replace_template_id
      2. Pipeline_web.wrapper.PipelineTemplateWebWrapper.unfold_subprocess
   2. 新建任务前需要进行子流程执行权限校验，需要先将流程树中所有的子流程节点遍历出来，并请求权限中心，校验是否有各个子流程（需要往下递归，包括项目流程和公共流程）的执行权限。这里后端会提供一个新的工具函数和对应接口，前端在手动创建任务填参之前需要先调用进行校验，在创建任务的相关api接口也需要加上。

### 新方案影响

因为目前会在新建任务前校验所有子流程的执行权限，所以用户之前部分可以新建执行的流程可能会因此新建任务失败，包括：手动新建的任务，api新建的任务，已创建未执行和新建的计划任务。

**Comment by homholueng** [comment]
子流程是否更新的判断逻辑也需要调整

**Comment by normal-wls** [comment]
> 1. 子流程是否更新的判断逻辑也需要调整
> 2. 流程导入/导出处理引用了公共流程模板的情况

已更新

**Comment by normal-wls** [comment]
## 前端部分调整
1. 流程编辑：
子节点插件选取列表增加公共流程（交互参考设计稿，接口沿用目前公共流程列表接口）
如果项目流程引用了公共流程，在流程树中对应的子节点需要添加"template_type": "common"进行标识

2. 流程列表：
根据设计稿调整公共流程入口和公共流程管理页交互

4. 流程导入导出：
导出暂时不需要进行修改
导入需要增加对只引用不导入子流程的支持（交互参考设计稿，接口需要在import_yaml_templates接口增加refer_mappings参数，具体参考swagger文档）
