### ISSUE TITLE
支持按变量的类型统计使用量

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5144]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======
目前代码层面不支持变量类型的统计
计划新增以下能力：
1. 使用了项目变量的项目（后续也需要针对项目变量统计类型）
2. 流程使用的全局变量的类型统计，便于后续针对性优化

**Comment by homholueng** [comment]
## 统计数据存储表设计

template_variables_statistics
- template_id：模板数字 ID
- template_type：模板类型（项目流程，公共流程
- var_key：变量 key
- var_type：变量类型（输入框，文本框，IP 选择器等）
- is_project_var：是否为项目变量

## 统计信息计算

- 补算
    - 功能第一次上线时，需要通过 API 触发一次补算
- 计算
    - 通过一个全局开关控制模板保存时是否需要触发变量引用数据统计计算
    - 模板保存时，触发一个 celery 异步任务来完成计算逻辑

**Comment by homholueng** [comment]
## WBS

- 模型设计
- 计算功能开发
- 补算功能开发
- 模板保存触发计算任务
- 模板导入触发计算任务
