### ISSUE TITLE
IP选择器（手动输入）选择静态IP模式时，输入当前业务不存在的IP时，输出的结果应该为空

### ISSUE THREAD

**Issue by MarinPeng** [Tencent/bk-sops#5235]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

IP选择器（手动输入）选择静态IP模式时，输入当前业务不存在的IP时，输出的结果为输入的筛选结果，并有error提示，预期结果应该为空值

重现方法
=======

**Comment by luofann** [comment]
手动输入模式目前在后端做的字符解析，前端未做校验，可以考虑加上。

**Comment by normal-wls** [comment]
1. 目前变量会将一些预期内的报错信息（如校验问题）作为变量值进行回填，方便用户查看报错
2. 存在另外一种处理方式：在变量渲染过程中如果存在预期内问题，则直接抛出异常，由上层处理。
两种处理方式的利弊：
1. 方式1会更加方便用户出错时查看报错，而且可以在用户进行变量值预览时候方便地定位错误问题
2. 方式2能够更及时终止任务，避免报错信息作为参数传到第三方系统且第三方系统没有校验的情况，如果使用方式2，变量值预览时如果有某个变量抛异常，可能导致预览失败

**Comment by ecoli666** [comment]
希望优化方式1的处理
1. 变量渲染报错时，渲染为空值
2. 报错信息额外突出展示在表单下方
