### ISSUE TITLE
系统变量引用未能正确的统计到

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#5266]
## 背景

`${_system.xxx}` 格式的变量在调用 `template/api/analysis_constants_ref/` API 进行 mako 模板变量引用分析时，只返回了对 `_system` 的引用信息，没有返回对其属性的引用信息

<img width="767" alt="image" src="https://user-images.githubusercontent.com/26020997/158926175-c8aa6631-1c40-4969-96f6-1bb646b4edd9.png">

**Comment by wheel-w** [comment]
https://github.com/TencentBlueKing/bamboo-engine/pull/67/files
