### ISSUE TITLE
有计划升级 Python 版本吗？

### ISSUE THREAD

**Issue by vvoody** [Tencent/bk-sops#5296]
关键信息
=======

- [ ] bk-sops 版本：3

问题描述
=======

您好。我们额外用了一些包，因为 bk-sops 还在用 Python 3.6.7 的关系，只能限定在某些低版本。

鉴于 Python 3.6 已于 2021 年底 end of life，今年有计划升级吗？谢谢。

**Comment by homholueng** [comment]
预计 Q2 中旬会进行升级

**Comment by vvoody** [comment]
谢谢。

**Comment by moonlightysh** [comment]
请问下，python升级计划确定了吗？谢谢
