### ISSUE TITLE
社区版7.0 APIGW 对接

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#5298]
## 背景

社区版7.0后 APIGW 已经正式对外发布，需要完成 APIGW 社区版的对接工作，并输出社区版 SaaS 对接 APIGW 的标准方案

## 需要完成的工作

1. 标准运维对接 APIGW（在部署时完成网关创建，资源同步，环境同步的操作）
2. 标准运维需要同时兼容来自 APIGW 和 ESB 的接口调用（同为 JWT 方案，公钥，payload 不同）

**Comment by wheel-w** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/61050624/160412142-4fbae1b2-a8ee-41b9-983a-4b0be72da505.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/61050624/160412248-a78d0bcc-3253-4905-882c-95b0159bf446.png">
