### ISSUE TITLE
第三方插件表单集成 JSON Schema Form 方案

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#5342]

**Comment by homholueng** [comment]
需要梳理
- 表单渲染策略及方案
- 表单项勾选到全局变量后进行部分渲染（参数填写页面，子流程渲染页面）的方案
- 表单项勾选到全局变量后存储到 pipeline tree 中的数据格式

**Comment by ywywZhou** [comment]
1.  表单渲染策略及方案
    -- Json schema类型数据用bkui-form来进行渲染，通过import导入
 2. 表单项勾选到全局变量后存储到 pipeline tree 中的数据格式
    -- 全局变量和表单渲染是两种东西，所以可以沿用之前的实现逻辑，只不过需要对bkui-form勾选的变量添加个标识字段form-type之类的
 3. 变量的一些特殊逻辑（渲染豁免、参数复用）的处理
    -- 可以沿用之前的逻辑，针对schema变量进行特殊处理
 4. 全局变量中的配置项（正则校验、显示/隐藏、自动隐藏）的功能兼容
    -- 变量的正则配置可以不用回填到变量编辑页的正则选择中，因为勾选的变量配置可以很复杂有多个正则，这时候不知道回填哪个
    --  显示/隐藏在bkui-form中有对应的配置，支持函数通过返回值动态设置
    --  自动隐藏需要将 ”使隐藏“ 变量和 ”被隐藏“ 变量筛选出来，两个表单的数据变化时可以依据筛选出来字典对某个表单项进行隐藏
 5. 表单项勾选到全局变量后进行部分渲染（参数填写页面，子流程渲染页面）的方案
    -- 通过form-type字段可以将全局变量筛选成两部分，一部分用renderform渲染，一部分用bkui-form渲染，提交校验的时候需要对两个变单都进行校验

**Comment by luofann** [comment]
针对上面第5点，标准运维新增jsonschema form类型的插件，并同时支持原有的renderform类型插件，如果用户有勾选jsonschema form表单项为全局变量，由于vue组件使用方式的限制，可能会导致在子流程节点参数配置和任务的参数填写的地方，出现两个独立表单插件情况，变量不能按照原有的排序进行渲染，所以考虑将renderform插件迁移到 jsonschema form插件，使用统一的一套插件配置协议以及前端组件。

使用jsonschema form组件渲染标准运维现有使用的插件，主要需要做两个部分的事情：
1. 将现有插件的js配置按照jsonschema form的协议进行转换，需要开发一个转换器脚本来处理
2. jsonschema form对renderform表单组件以及定制化功能的支持，比如ip选择器、集群资源筛选等特有业务组件，代码编辑器、分组、密码等通用组件，或者下拉框的输入选项标记，表格组件的导入导出、行拖拽等

### 协议转换问题

renderform类型插件的js配置中，tag_code、type和attrs里的静态属性比较好处理，大部分都可以在jsonschema form协议中找到对应的配置项，主要的难点在于validation和events配置中涉及到插件开发者写的函数内容的转换，jsonschema form目前只在特定的配置项能够支持表达式，不支持函数特性。

因此转换器的开发可能只能做静态属性部分的转换，**涉及到插件配置里的函数部分，需要人工确认函数里的逻辑**，并且renderform插件支持函数的地方，逻辑执行自由度比较高，为支持原插件的逻辑，**jsonschema form可能需要开发新的功能去适配**。


### renderform现有组件和功能支持

以renderform支持的现有组件为维度，来一一对应的梳理jsonschema form的支持情况：

- [ ] **button**   
    支持

- [ ] **cascader**
    支持

- [ ] **checkbox**
    支持

- [ ] **datatable**
    需要单独开发业务插件
      1. 添加自定义按钮
      2. 导入、导出
      3. 上传
      4. 行拖拽
      5. 兼容job_execute_task标准插件动态添加输出参数

- [ ] **datetime**
    支持
- [ ] **time**
    支持

- [ ] **input**
    需要支持输入时匹配当前全局变量下拉框的交互

- [ ] **int**
    支持

- [ ] **ipSelector**
    开发业务插件

- [ ] **password**
    开发业务插件

- [ ] **radio**
    支持

- [ ] **select**
    开发业务插件
      1. 搜索功能支持大小写匹配
      2. 支持用户输入高亮

- [ ] **text**
    开发业务插件

- [ ] **textarea**
    支持

- [ ] **tree**
    开发业务插件
      1. 内置自定义搜索
      2. 远程加载
      3. 节点选中逻辑
      
- [ ] **upload**
    开发业务插件

- [ ] **memberSelector**
    开发业务插件

- [ ] **setAllocation**
    开发业务插件

- [ ] **section**
    开发业务插件

- [ ] **codeEditor**
    开发业务插件

**Comment by luofann** [comment]
根据实际上线的插件，挑选统计出前端逻辑相对复杂的几类，所涉及到使用函数以及函数的具体用法，大概分为为以下情况：
1. 自定义校验方法：
  - 调用获取其他表单值的方法getParent、_get_value（jsonschema form 支持）
  - 单个表单或者多个表单值之间的逻辑判断（大部分可以用表达式代替，少数需要用到jsonschema提供的函数执行的方法）
  
2. 表单生命周期钩子函数（主要是init、change事件）：
  - 调用获取其他表单值的方法
  - 设置表单值_set_value、this.value = x（jsonschema form 支持）
  - 发送异步请求
  - 设置请求参数
  **单个调用或者只是发送固定请求的简单场景可以用表达式代替，组合类型的函数需要用jsonschema函数执行**

3. 远程数据源函数成功和失败回调函数：
  - 同上
  - 成功回调函数还会增加接口返回的数据处理逻辑

### 结论
从技术实现上，函数部分是可以100%迁移的。renderform 插件函数部分的逻辑，如果只是简单的获取表单值、设置表单值、发送请求、数值间的逻辑判断等用法的话，可以直接迁移，如果是组合的用法，比如获取表单值后，设置请求参数，然后在请求参数里做数据处理，最后赋值属性这样的逻辑，就需要用jsonschema的函数执行来替换

### 风险点
每个插件函数里可能的用法不是固定的，开发通用的函数部分的迁移脚本成本比较高，并且需要人工的对每个插件做迁移验证

**Comment by luofann** [comment]
把表单变量单独拆出来，一个表单对应一个renderform或者json schema from的组件容器渲染，可以解决变量无法按照实际顺序排列的问题。

### 方案的优点：

这样相比于插件迁移的方案，没有存量插件转换的成本，原有的插件可以继续迭代更新使用。jsonschema form 增加对renderform现有组件和功能支持即可。

### 缺点

- 一个表单使用一个form组件容器，渲染性能相比于一个容器渲染多个表单会差一些，考虑到实际的使用时基本不会有几十个量级的场景，性能问题影响较小
- 如果后续增加表单间的交互或者逻辑关联，容器和容器之间的关联开发要比容器内开发复杂程度更高一些
