### ISSUE TITLE
流程执行时支持整个子流程步骤的重试、跳过功能

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5365]
现状
==========
当前标准运维流程执行时，步骤可能为嵌套的子流程。但子流程中的步骤失败时，当前只支持对当前步骤进行重试或跳过，而不能对整个子流程进行处理。
<img width="904" alt="image" src="https://user-images.githubusercontent.com/42025090/176368405-fdf278ec-0eb6-4b5c-9ada-0e594f3e1933.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/42025090/176368710-1b605314-b47b-45a9-bd83-e81082b7b254.png">

问题
=============
**子流程某个步骤失败很可能影响到整个子流程后续步骤的执行。此时需要废弃当前子流程的执行。
当前平台未提供这个能力，用户只能新建一次任务，取消掉已经执行过的前序步骤**

解决
=============
考虑提供两个平台能力：
1. 重试  --- 重新发起整个子流程，可支持修改子流程的执行入口参数
2. 跳过整个子流程 --- 该子流程非必须，可以延后处理

详细功能点
=============
1. 子流程节点编辑时，添加同普通节点一致的失败处理和超时控制能力
![image](https://user-images.githubusercontent.com/42025090/183356405-4c8bae51-3a92-4fcc-882c-3a6ff70bf3ae.png)

2. 子流程节点执行时，添加同普通节点拥有的重试、跳过能力，使子流程和普通节点行为保持一致
<img width="807" alt="image" src="https://user-images.githubusercontent.com/42025090/177777276-ef68cfa5-9b18-4301-a353-2e47a503ff3c.png">

3. 子流程执行时，应该拥有子流程自己的执行记录。与独立执行行为保持一致
4. 在父流程的任务添加展开按钮，以树形结构方式展示子任务
![image](https://user-images.githubusercontent.com/42025090/177749674-d820bc24-6166-485e-a130-557716dc6406.png)

5. 增加和普通节点一致的基础信息、输入参数、执行记录展示。点击执行详情可新窗口跳转子任务执行详情
![image](https://user-images.githubusercontent.com/42025090/183374728-cd7e7a9c-5d55-44ad-9e49-df211003bd96.png)

**Comment by homholueng** [comment]
- 完全跳过：成本一般，功能通用性需要考虑
- 完全重试：成本高，功能通用性需要考虑

**Comment by ecoli666** [comment]
补充：
1. 当前版本优先支持跳过子流程
2. 调整子流程点击交互，当前为进入子流程步骤详情。修改为查看子流程执行信息，额外提供一个按钮进入子流程步骤详情
3. 子流程执行信息增加展示输入参数

**Comment by ecoli666** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/42025090/174939817-7dd8856e-856e-4810-99d0-c0b78480d2a0.png">


<img width="565" alt="image" src="https://user-images.githubusercontent.com/42025090/174939909-1b4533de-7c24-43e9-8c21-41a91448bc7c.png">

**Comment by homholueng** [comment]
如果允许子流程跳过的话，需要解决以下问题：

1. 如何处理子流程中失败节点的状态
2. 如果流程中存在循环结构，再次循环执行到子流程节点内部是，之前失败的节点要如何处理

**Comment by zyxazhang** [comment]
实现简括
1. 选择子流程模板时，通过接口判断展示失败处理和超时控制，对应渲染出表单
2. 子流程处理失败时添加测试和跳过以及对应的角标，与普通流程节点一致，具体实现参考普通流程节点
3-4，任务记录table 展示树形结构，点击展来通过名称跳转到对应的执行任务详情，以下是处理数据方法
![image](https://user-images.githubusercontent.com/86033636/184340755-cb36e647-ca48-4513-9866-6610b2988e04.png)

**Comment by ecoli666** [comment]
### 补充

1. 需要区分子流程重试、跳过这两类操作。 重试将产生执行记录（因为重新发起了一次子任务的执行）和对应的操作记录，而跳过只会产生操作记录
2. 子流程内部节点失败，通过跳过、重试等方式处理后子任务成功完成。子任务需回调通知父任务，父任务执行页面需监听子流程节点状态，并实时刷新
