### ISSUE TITLE
分支网关、条件并行网关支持配置默认分支

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5378]
# 背景&目标

当前分支网关/条件并行网关约束必须有一条分支被命中，如果无分支命中会产生异常。实际场景中，用户希望有一个兜底的默认分支来实现例外情况的配置。即：switch语句里面的default分支`。

**Comment by ecoli666** [comment]
![image](https://user-images.githubusercontent.com/42025090/166899658-1dbd16e6-c2ce-429a-ab02-62b1d3a6c816.png)

**Comment by normal-wls** [comment]
![企业微信截图_a1a86767-6665-40ec-abc1-931cebcdbeb9](https://user-images.githubusercontent.com/9864577/168226180-b3754eab-1e2a-4aa4-909f-c6102ae99da4.png)
前端对默认分支的配置

**Comment by normal-wls** [comment]
https://github.com/TencentBlueKing/bamboo-engine/pull/84
