### ISSUE TITLE
节点管理新增插件支持传递IP来获取agent状态

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5417]
背景
=======

gse agent是蓝鲸管理的基石。agent在线，用户才能通过标准运维、job等平台进行管控。当前需要提供一种能力，让用户能获取到agent不在线的IP，以便后续对这些ip进行消费（重装agent等）

输入：   "云区域：IP"
输出：agent在线的IP列表，agent不在线的IP列表

**Comment by wheel-w** [comment]
新增一个插件去判断ip的agent是否正常的，由于节点管理插件的ip输入是个表格，用户输入判断完不好直接作为变量引用
是否考虑，在节点管理新建任务插件参加一个检查ip agent是否正常的按钮
用户填完表单后，点击下按钮，会输出agent不正常的ip
<img width="782" alt="image" src="https://user-images.githubusercontent.com/61050624/164004363-704d55b9-5f6f-4384-a34e-3893b42af1ed.png">

**Comment by ecoli666** [comment]
调整方案为，新增一个变量类型 "IP过滤器"来支持这类IP过滤的诉求，当前仅支持按GSE agent状态过滤，后续可考虑支持其他方式过滤

![image](https://user-images.githubusercontent.com/42025090/164164248-709f4246-7b1b-45df-8e8a-ce5fdf0c6e25.png)

**Comment by normal-wls** [comment]
需要考虑是否支持多条件同时过滤的情况

**Comment by ecoli666** [comment]
调整为支持多条件同时过滤的形态

![image](https://user-images.githubusercontent.com/42025090/164216361-5711121a-1090-4297-a2cd-0301d0727187.png)
