### ISSUE TITLE
公共流程勾选插件的业务字段为全局变量时，执行时字段值没有被赋值为关联的业务

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5489]
公共流程勾选插件的业务字段为全局变量时，执行时字段值没有被赋值为关联的业务
=======

重现方法
=======

公共流程编辑流程先选择某个业务A，勾选插件的业务字段为全局变量，然后在B业务下执行
此时发现业务字段为A，预期是B

**Comment by normal-wls** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/9864577/166084654-f5d1528d-50c9-4e38-98d3-bec580f30bf0.png">
业务字段在项目流程下不可修改，这种情况在公共流程编辑过程中不应指定业务后再勾选全局变量，应该直接勾选全局变量，业务字段会随着创建任务所在的项目自动替换业务id。
非bug，可从交互层面考虑优化

**Comment by homholueng** [comment]
非 BUG，暂时关闭
