### ISSUE TITLE
进入公共流程管理页缺少鉴权

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5505]
进入公共流程管理页缺少鉴权页面，普通用户误入会引起干扰和困惑
=======

1:   公共流程TAB只允许公共流程管理者进入（拥有公共流程新建、编辑和删除其中一个权限即可） 
2：点击去申请，跳转权限中心，申请公共流程的新建权限。（自己新建的流程会拥有编辑和删除的权限）

![image](https://user-images.githubusercontent.com/42025090/165512980-fa00370c-e77c-4857-bdc8-4c9ccbe83c6f.png)

**Comment by homholueng** [comment]
拥有【公共流程新建】或任意公共流程的【编辑】或【删除】权限即可进入，需要注意的点

- 任意公共流程的【编辑】或【删除】权限的判断不要通过资源遍历的方式实现，而是通过表达式判断的方式实现

**Comment by homholueng** [comment]
通过 iam "/api/v1/policy/query_by_actions" 接口可以查询用户关于某些权限的权限策略，可以根据是否有策略去判断，但是，【有策略】不等于【有任一资源的权限】

**Comment by homholueng** [comment]
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/26020997/168513632-12c9c8b0-0c5b-4421-8a5a-16fba919859a.png">
