### ISSUE TITLE
报错展示优化

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#5776]
问题
=======
### 当前报错展示不友好，重复弹窗、直接展示接口报错等
1. 接口报错、无权限报错。直接将错误代码扔到了界面上
2. 重复点击时对弹窗数量没有处理，导致满屏报错
3. 部分插件重复调用接口、以及前端和插件各自报错，一个错误会导致多个报错弹窗

![image](https://user-images.githubusercontent.com/42025090/175255612-90095b71-9f28-4bf1-9af8-e91cd23a67bf.png)

标准运维的几大类报错
==================
1. 前端校验不通过（如画布数据校验不通过）
![image](https://user-images.githubusercontent.com/42025090/176409710-ed83ebf3-8650-4e8f-8bd3-3edcf8f0b4e2.png)
2. 接口500等预期外错误
![image](https://user-images.githubusercontent.com/42025090/176410267-449a4073-b473-4e39-9409-4c36d2e99532.png)

4. 调用第三方接口无权限、无数据等预期内错误
![image](https://user-images.githubusercontent.com/42025090/176411849-5fe2274c-d43f-406f-aa6c-52cdd5aaff30.png)

解决方案
=======
1. 统一第三方调用错误弹窗样式，默认仅展示可读的文字信息，将代码层面的报错隐藏，提供一个展开按钮可查看详细报错
大标题：调用外部接口发生错误
展开：分两行展示traceid和message信息
![image](https://user-images.githubusercontent.com/42025090/179923102-b3ecd2a3-4f7f-4f19-a7bd-db5b4b0b31d5.png)
2. 内部接口500报错
标题：内部错误
展开：分两行展示traceid和报错信息
![image](https://user-images.githubusercontent.com/42025090/179923270-67d33f3e-7593-4646-8e64-5cc1cf05ee42.png)
3. 无权限499报错时，直接弹出权限申请弹窗
![image](https://user-images.githubusercontent.com/42025090/176419289-defdc26b-a769-4eb1-a7b8-24ffd75ec332.png)

~~4. 重复点击导致报错时，应关闭前序弹窗后再展示~~

~~5. 多个接口导致报错时，需要有一种方案整合报错信息再展示。如触发第二个报错时，如第一个报错弹窗还未消失，能包含前序报错信息~~

**Comment by normal-wls** [comment]
所有的报错信息归纳，可以参考以下规则：
1. 如果命中一下状态码：1. 400：弹出测框，从response中读message信息；401：重定向登录页；499：弹出登陆弹框；500：弹出异常弹框
2. 如果接口返回格式为result=False，则弹出测框，并渲染返回message信息。

**Comment by normal-wls** [comment]
报错优化结论：
1. 设计稿增加多条弹窗折叠交互逻辑 
2. 对于插件和系统各弹一次报错问题，通过message+trace_id进行去重和展示 
3. 无权限情况下弹框非侧边通知，后端先处理，后续需补充前端交互方案 
4. 个别插件重复调用接口问题排查&确认，如全业务快速执行脚本

**Comment by ecoli666** [comment]
> 设计稿增加多条弹窗折叠交互逻辑

暂时不考虑此方案，多个弹窗合并会引入其它一些问题（无法直观看到报错、弹窗变化等），优化弹窗样式、减少重复弹窗后。直接平铺多条message在页面可以接受
