### ISSUE TITLE
子流程节点支持查看输入/输出数据

### ISSUE THREAD

**Issue by homholueng** [Tencent/bk-sops#5791]
1. 调整子流程点击交互，当前为进入子流程步骤详情。修改为查看子流程执行信息，额外提供一个按钮进入子流程步骤详情
2. 子流程执行信息增加展示输入参数

![image](https://user-images.githubusercontent.com/26020997/176159693-180ac984-43de-4706-bb4a-5b1fda9f6f1e.png)

![image](https://user-images.githubusercontent.com/26020997/176159743-4de37068-d4bb-4ad5-b093-1f8f80fe674d.png)

**Comment by homholueng** [comment]
https://github.com/TencentBlueKing/bamboo-engine/pull/99

**Comment by ecoli666** [comment]
@ywywZhou 

> 调整子流程点击交互，当前为进入子流程步骤详情。修改为查看子流程执行信息，额外提供一个按钮进入子流程步骤详情

这一条暂时不做，和子流程跳过/重试功能一起开发

> 子流程执行信息增加展示输入参数

当前版本完成此功能即可，参考普通流程节点增加输入参数展示
