### ISSUE TITLE
新引擎任务数据清理

### ISSUE THREAD

**Issue by normal-wls** [Tencent/bk-sops#5874]

**Comment by normal-wls** [comment]
根据不同的清理粒度，对任务数据有不同程度的影响，需要在交互上做不同的调整：
1. 仅清理节点执行相关数据，如状态、日志等。
![image](https://user-images.githubusercontent.com/9864577/181410507-3a0918ca-d4ef-484c-999a-b6f721878db2.png)
![image](https://user-images.githubusercontent.com/9864577/181410613-6a5a6838-d30e-4087-8c48-153f75bfbb40.png)
2. 在清理节点执行数据的同时清除任务数据。
![image](https://user-images.githubusercontent.com/9864577/181415228-0cc5795f-6b14-4a3c-8554-a53b6977e0c0.png)
此时用户无法查看过期任务数据详情，需要设计专门页面，在用户通过拼接url访问任务详情时进行展示和提示。

**Comment by ecoli666** [comment]
1. 超过6个月的任务数据自动归档，前端限制只能筛选6个月内的任务记录
2. 归档的数据需要保存2年
3. 技术实现上需要考虑后续产品层面提供归档数据查看的功能
