### ISSUE TITLE
【产品-无需评审会】公共流程支持标签

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#6073]
背景
=======
当前普通的项目流程早已支持设置标签，但公共流程因为所有的公共流程共享了一个空间，这个空间被多个平台团队在一起使用。所以一直没有标签能力给公共流程的管理者使用。
公共流程目前虽然仅有分类字段，字段来源于PaaS。但目前平台无法自己定义此分类，且分类过于宽泛已基本被用户弃用
![image](https://user-images.githubusercontent.com/42025090/191880913-54232760-600e-4edd-8939-e2447ea2fd36.png)

### 用户诉求：
当前各蓝鲸产品在标准运维建设的公共流程越来越多，用户和公共团队都希望用户可以快速筛选自己平台提供的公共流程，例如BCS、BKDATA、SA等。但当前只能强依赖流程的名称去辨识流程的作用。
<img width="399" alt="image" src="https://user-images.githubusercontent.com/42025090/192112131-f8cfa124-b651-4b18-b040-47fe5d09788d.png">

### 方案

一期：计划由平台提供默认标签，提供给公共流程使用
- 默认标签：由平台进行定义和管理，取代分类的作用。例如平台可定义BCS、BKDATA、SA等平台类型标签，公共流程管理者仅能选择默认标签，不能管理默认标签。平台可在显著位置提供基于标签的筛选能力
![image](https://user-images.githubusercontent.com/42025090/191889302-222ac4e6-1ec3-42de-a9ad-46bdaffd84a3.png)
二期：支持公共流程管理者在自己的空间下管理标签
- 自定义标签：公共流程管理者能自定义流程的标签，用来体现流程的作用或特征等。当前所有公共流程共用了一个空间，没有子空间概念给各平台维护自己的标签，所以这期暂不支持自定义标签

**Comment by normal-wls** [comment]
建议通过默认标签来实现该功能。

基于以下几点理由：
1. 分类项算是基于历史原因留下来的一个功能字段，仅支持单选且没有办法快速筛选。目前在项目流程中，该字段的使用率已比较低；在考虑公共流程添加分类问题上，是否需要把平台添加的新分类同步到项目流程选项中，如果同步，则项目流程的用户会困惑到底推荐用标签还是分类，如果不同步，则项目流程的用户会困惑两边的分类选项不一致。
2. 目前虽然只考虑公共流程的平台属性来进行分类，但是本质上分类是一种一维的方式，如果后面有其他维度的分类需求，如【高危】【日常】等则无法满足。
3. 目前的标签实现中支持默认标签，由平台自定义，用户无法定义，能满足上述平台分类的属性。同时添加之后，项目流程和公共流程均可使用和多选，这两种流程的编辑者共用的是同一套默认标签，会更加统一。
