### ISSUE TITLE
代码编辑组件默认支持全屏功能

### ISSUE THREAD

**Issue by luofann** [Tencent/bk-sops#6079]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/44999219/191930983-797e2b70-7eaa-474d-ac5c-f297cf5bd517.png">

**Comment by ywywZhou** [comment]
https://github.com/Tencent/bk-sops/pull/6201/commits/dc5977e6a78ff3c2120022a0e47858dae75fd777

**Comment by ywywZhou** [comment]
done
