### ISSUE TITLE
支持删除“未启动”的任务

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#6122]
背景
=======

![image](https://user-images.githubusercontent.com/42025090/195068202-4f77bacc-d090-4c70-9de8-d8d0278eaf1f.png)

新版本废除了【任务记录】的**删除**功能，本意是**防止“任务记录”被删除后无法追溯和审计**。该功能变更引发了较多用户反馈，主要集中在一个场景：

某些时候已经创建了任务，但是创建后发现不满足需求（如步骤勾选错误，流程需要修改等等）
此时需要重新创建任务，为了**确保操作的安全性**（尤其是创建任务和执行任务为不同人时），希望删除“已创建”的任务

### 解决方案：
对还**未执行**的任务记录，支持**删除**操作。未执行的任务还没有产生任何实际效果，所以删除也不会影响对于操作的追溯和审计。
![image](https://user-images.githubusercontent.com/42025090/195070842-58d97ef1-dacd-42ec-bb41-7e5d0c47e51c.png)

**Comment by EchoQT** [comment]
ok
