### ISSUE TITLE
GSEKit 执行命令插件增加检查配置选项

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [Tencent/bk-sops#6146]
关键信息
=======

 执行命令插件增加检查配置选项
- [ ] bk-sops 版本：

问题描述
=======
检查配置(diffcfg)
传入参数:
* job_action: `diff`
* job_object：`configfile`

交互同 `生成配置(createcfg)` `下发配置(pushcfg)` 

重现方法
=======

**Comment by normal-wls** [comment]
已支持
