### ISSUE TITLE
运营数据流程&任务面板显示异常问题

### ISSUE THREAD

**Issue by normal-wls** [Tencent/bk-sops#6172]

**Comment by guanjianqiang0408** [comment]
![image](https://user-images.githubusercontent.com/103730408/196330478-f6ee0a7c-f5cc-4798-8d36-6edf7743bd3a.png)
流程统计、任务统计展示模板中的百分比错误，现在后端提供了百分比的响应结果，获取dimension_percent属性值即可
![image](https://user-images.githubusercontent.com/103730408/196330665-93490566-128a-4eea-98f6-c72aab934b7b.png)
