### ISSUE TITLE
子流程搜索特殊字符转义后 搜索缺陷

### ISSUE THREAD

**Issue by MarinPeng** [Tencent/bk-sops#6377]
关键信息
=======

- [ ] bk-sops 版本：

问题描述
=======

![企业微信截图_16697925621124](https://user-images.githubusercontent.com/50908315/204960998-4e6e3a2f-9bfb-4eac-b245-f598960c7cc5.png)

重现方法
=======

**Comment by ywywZhou** [comment]
c0686200f2e6a1323957fa6c47021368bbcde8f8
