### ISSUE TITLE
【hawk】子流程节点重试后，成功跑完节点状态不刷新

### ISSUE THREAD

**Issue by ecoli666** [Tencent/bk-sops#6428]
- [ ] bk-sops 版本：hawk

问题描述
=======

### 子任务已跑完
![image](https://user-images.githubusercontent.com/42025090/207291425-428eed54-4b28-43e3-b5f8-c79ea762b9bf.png)

### 子流程节点状态不刷新
![image](https://user-images.githubusercontent.com/42025090/207291218-e8dd4d47-ce23-4a2c-a8cd-16b200bf2e76.png)

###  刷新页面节点状态可以更新
![image](https://user-images.githubusercontent.com/42025090/207291278-279de6f2-ae67-4832-bf8f-5841e40ef3b8.png)

重现方法
=======
让子流程节点重试，然后跑完子任务

**Comment by normal-wls** [comment]
无法复现，先close
