### ISSUE TITLE
引入了并行、汇聚网关，会导致汇聚网关以后的节点参数无法展示

### ISSUE THREAD

**Issue by kevinpersist** [Tencent/bk-sops#760]
# 问题描述

标准运维-任务执行
如果引入了**并行、汇聚**网关，会导致**汇聚网关**以后的节点参数无法展示

# 重现方法

可重现

# 关键信息

![image](https://user-images.githubusercontent.com/10846583/61507542-a3780680-aa18-11e9-97d1-100c0f572e1c.png)

请提供以下信息:

- [ ] bk-sops   版本 (发布版本号 或 git tag)： bk_sops_V3.3.13-ce
- [ ] 蓝鲸PaaS   版本：PaaS 3.2.511、PaaSAgent 3.1.0202
- [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
和这个Issue(https://github.com/Tencent/bk-sops/issues/362)重复，问题在V3.3.14版本已解决，推荐升级到最新版本V3.3.18

**Comment by kevinpersist** [comment]
ok
