### ISSUE TITLE
编辑流程时复制节点内容信息不全

### ISSUE THREAD

**Issue by yeguangfang** [Tencent/bk-sops#850]
问题描述
=======
编辑流程时复制节点内容信息不全，如当节点为执行作业平台作业时，只能将节点名称和类型复制过去，具体的作业信息、参数信息未能复制，需要重新选择填写。

重现方法
=======
编辑流程，选择相关作业节点，Ctrl+C，Ctrl+V

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本  3.3.13
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
目前未实现参数复制，只能复制拓扑；参数复制的功能还在调研设计阶段，下半年会推出

**Comment by pagezhou** [comment]
https://github.com/Tencent/bk-sops/pull/1528
V3.4.X 以上版本已支持，社区版等待蓝鲸整体出包
