### ISSUE TITLE
我在标准运维里面开发遇到问题 如果选择输入框的类型为密码类型 那么怎么取值？我取到的值是加密的 本地运行能正常取值  线上部署之后取到的值是加密的

### ISSUE THREAD

**Issue by Linuxlovers** [Tencent/bk-sops#882]
问题描述
=======

![image](https://user-images.githubusercontent.com/23232806/62758327-a4003c00-bab0-11e9-80a2-4f5fc7de0777.png)

我在标准运维里面开发遇到问题 如果选择输入框的类型为密码类型 那么怎么取值？我取到的值是加密的 本地运行能正常取值  线上部署之后取到的值是加密的
重现方法
=======

参考图片即可

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
from pipeline.utils.crypt import rsa_decrypt_password

# 如果是密码类型则解密，否则保持原值
value = data.inputs.XXX
try:
    value = rsa_decrypt_password(value, settings.RSA_PRIV_KEY)
except Exception:
    pass
