### ISSUE TITLE
文件流的处理时   能否取消这个警告

### ISSUE THREAD

**Issue by Linuxlovers** [Tencent/bk-sops#894]
问题描述
=======

![image](https://user-images.githubusercontent.com/23232806/62852525-36f0de80-bd1c-11e9-8b1a-1b33d62b7bdf.png)

![image](https://user-images.githubusercontent.com/23232806/62852515-2a6c8600-bd1c-11e9-9bd3-837159115cb7.png)

重现方法
=======

这个是处理文件流的时候 
怎么取消这个警告

![image](https://user-images.githubusercontent.com/23232806/62852470-0e68e480-bd1c-11e9-9977-6f5f29173d42.png)

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
你好，感谢你的反馈。这个报错表示你在流程模板配置中，使用了形如 ${key} 的变量引用语法，但是变量引擎未在全局变量中找到 key 这个变量，变量尝试解析失败并原样返回 ${key} 后告警。
