### ISSUE TITLE
变量引用块 ${xxx}，xxx中不允许 $、{、}、# 四个字符

### ISSUE THREAD

**Issue by fengweiyuan** [Tencent/bk-sops#905]
问题描述
=======
变量引用块 ${xxx}，xxx中不允许 $、{、}、# 四个字符

重现方法
=======
这么写，在标准运维中，无法引用到iplist和state。
{"ip_stat" : ${[{'ip': val, 'state': state} for val in iplist]}  , "systemid": ${systemid}}
如果这么写，发现是不可的，因为变量引用快不能用$字符。
{"ip_stat" : ${[{""ip"": val, "state": ${state}} for val in iplist]}  , "systemid": ${systemid}}

**Comment by pagezhou** [comment]
标准运维变量引擎使用正则匹配合法的mako语法，目前不支持语法中包含关键字 $、{、}、# ，但是可以提供替代方案：
1、构造字典不使用 {}，通过 `dict(a='1', b='2')` 方式
2、$、# 可以设置全局变量，然后引用在需要赋值特殊字符的地方
![image](https://user-images.githubusercontent.com/8849151/70108819-24146800-1685-11ea-8334-97034741fe01.png)
