### ISSUE TITLE
[GSE] Log Output Exceeds Maxsize(1MB) 

### ISSUE THREAD

**Issue by pangzhiguo** [Tencent/bk-sops#906]
问题描述
=======

标准运维中作业执行输出日志超过1MB就中断报错！
[GSE] Log Output Exceeds Maxsize(1MB) 

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
请确认是作业平台报错还是标准运维问题，如果是作业平台报错，请在社区群通过蓝鲸助手联系作业平台负责人处理；如果作业平台执行成功，标准运维报错，请提供错误截图和关键信息

**Comment by Langni** [comment]
我也遇到了一样的问题,任务执行成功,但是日志打印不全
