### ISSUE TITLE
标准运维下拉框提供实例格式有错

### ISSUE THREAD

**Issue by pangzhiguo** [Tencent/bk-sops#907]
问题描述
=======

列表中嵌套字典，每个字典作为一个列表元素，蓝鲸给出的格式不对。
![image](https://user-images.githubusercontent.com/25121085/62993504-18a8f100-be8a-11e9-812c-20a2c70f8305.png)

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
已知问题，已经开发完成，等待出包 https://github.com/Tencent/bk-sops/pull/887/files
