### ISSUE TITLE
sops3.3.19部署，访问Bad Request (400)

### ISSUE THREAD

**Issue by chainingning** [Tencent/bk-sops#915]
问题描述
=======
部署开源版sops3.3.19的时候，最后访问http://dev.www.bking.com:8088/ 出现Bad Request (400)

重现方法
=======
centos7单独部署sops，配置好hosts为192.168.10.222 dev.www.bking.com，运行监听8088端口，然后访问，出现400

关键信息
=======
 - [x] bk-sops   版本 (发布版本号 或 git tag)：3.3.19
 - [ ] 蓝鲸PaaS   版本：PaaS 3.3.19
 - [ ] bk_sops 异常日志：WARNING "GET / HTTP/1.1" 400 26

**Comment by pagezhou** [comment]
标准运维依赖蓝鲸PaaS和CMDB，请确认依赖平台的版本号，并查看标准运维后台错误日志。

**Comment by chainingning** [comment]
> 标准运维依赖蓝鲸PaaS和CMDB，请确认依赖平台的版本号，并查看标准运维后台错误日志。

PaaS版本：3.2.521   
CMDB版本：3.2.17

**Comment by pagezhou** [comment]
bk_sops 异常日志是否有更详细的日志，除了 uwsgi.log ，再看下 bk_sops.log、mysql.log等是否有详细的错误；另外看下配置平台是否存在以你为运维角色的业务
