### ISSUE TITLE
开发标准运维的问题

### ISSUE THREAD

**Issue by Linuxlovers** [Tencent/bk-sops#932]
问题描述
=======

无法进行debug调试  ，无法打印输入值  输出值，logger.exception(xxx)也不管用
要怎么进行调试和开发

重现方法
=======

关键信息
=======

请提供以下信息:

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by pagezhou** [comment]
麻烦提供一下版本号和操作步骤，logger会打印到和项目根目录平级的 logs/bk_sops 下的文件中，麻烦确认下是否存在
