### ISSUE TITLE
pipeline 支持批量查询节点总状态

### ISSUE THREAD

**Issue by jayjiahua** [Tencent/bk-sops#953]
问题描述
=======
目前 pipeline 只能通过 `task_service.get_state(pipeline_id)` 去获取单个pipeline的总状态。

要同时查询多个pipeline，只能通过DB操作

```
from pipeline.engine.models import Status
Status.objects.filter(id__in=pipeline_id_set)
```

希望能够提供一个接口进行批量查询

**Comment by homholueng** [comment]
现有 `task_service.get_state` 接口已经满足需求
