### ISSUE TITLE
部署标准运维开发环境页面打开是空白

### ISSUE THREAD

**Issue by damondengxin** [Tencent/bk-sops#956]
问题描述
=======

1，按https://github.com/Tencent/bk-sops/blob/master/docs/install/dev_deploy.md步骤操作后，打开后是一片空白
2，浏览器console输出错误如下图
![Uploading QQ图片20190821110756.jpg…]()

重现方法
=======

1，https://github.com/Tencent/bk-sops/blob/master/docs/install/dev_deploy.md操作
2，蓝鲸paas是4.16升级到5.1社区版

关键信息
=======

请提供以下信息:
1, bk-sops-v3.3.20.tar.gz
2,paas是4.16升级到5.1社区版

 - [x] bk-sops   版本 (发布版本号 或 git tag)： 
 - [ ] 蓝鲸PaaS   版本：
 - [ ] bk_sops 异常日志：

**Comment by homholueng** [comment]
这边看不到您提供的 console 错误截图，麻烦重新提供错误信息。

**Comment by damondengxin** [comment]
js文件都在对应的目录下


------------------ 原始邮件 ------------------
发件人: "homholueng"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 中午12:10
收件人: "Tencent/bk-sops"<bk-sops@noreply.github.com>;
抄送: "damon"<304749970@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/bk-sops] 部署标准运维开发环境页面打开是空白 (#956)




这边看不到您提供的 console 错误截图，麻烦重新提供错误信息。

**Comment by damondengxin** [comment]
![bksops](https://user-images.githubusercontent.com/19447869/63412146-ac9a3000-c429-11e9-8c3c-881b121b6a19.jpg)

**Comment by pagezhou** [comment]
看起来是静态资源未找到返回了 404 的 index.html 问题，请确认本地执行了以下命令
```
打包并收集前端静态资源
1）安装依赖包
进入 frontend/desktop/，执行以下命令安装

npm install
2）本地打包 在 frontend/desktop/ 目录下，继续执行以下命令打包前端静态资源

npm run build -- --STATIC_ENV=dev
3）收集静态资源 回到项目根目录，执行以下命令收集前端静态资源到 static 目录下

python manage.py collectstatic --noinput
前端资源文件需要单独拷贝收集，执行如下命令

rm -rf static/dev static/images
mv frontend/desktop/static/dev static/
mv frontend/desktop/static/images static/
```

**Comment by damondengxin** [comment]
(bksops5-env) [god@devel desktop]$ npm run build -- --STATIC_ENV=dev


> blueflow@1.0.0 build /apps/server/bksops5/frontend/desktop
> cross-env NODE_ENV=production webpack --config ./builds/webpack.prod.config.js "--STATIC_ENV=dev"


build mode: production
SITE_URL: 
publicPath: /static/
clean-webpack-plugin: /apps/server/bksops5/frontend/desktop/static/dev has been removed.
Hash: 20ad14992974d9350995
Version: webpack 4.28.4
Time: 823838ms
Built at: 08/21/2019 11:00:19 AM
PublicPath: /static/
                             Asset       Size  Chunks                    Chunk Names
                dev/dist/css/1.css  342 bytes       1  [emitted]         
            dev/dist/css/1.css.map  575 bytes       1  [emitted]         
               dev/dist/css/11.css   25.8 KiB      11  [emitted]         
           dev/dist/css/11.css.map   32.2 KiB      11  [emitted]         
               dev/dist/css/12.css   22.3 KiB      12  [emitted]         
           dev/dist/css/12.css.map   27.3 KiB      12  [emitted]         
               dev/dist/css/13.css     19 KiB      13  [emitted]         
           dev/dist/css/13.css.map   23.8 KiB      13  [emitted]         
               dev/dist/css/14.css     13 KiB      14  [emitted]         
           dev/dist/css/14.css.map   16.3 KiB      14  [emitted]         
               dev/dist/css/15.css   10.8 KiB      15  [emitted]         
           dev/dist/css/15.css.map   13.7 KiB      15  [emitted]         
               dev/dist/css/16.css     13 KiB      16  [emitted]         
           dev/dist/css/16.css.map   16.4 KiB      16  [emitted]         
               dev/dist/css/17.css   7.61 KiB      17  [emitted]         
           dev/dist/css/17.css.map   9.79 KiB      17  [emitted]         
               dev/dist/css/18.css   7.87 KiB      18  [emitted]         
           dev/dist/css/18.css.map   9.89 KiB      18  [emitted]         
               dev/dist/css/19.css   2.39 KiB      19  [emitted]         
           dev/dist/css/19.css.map    3.4 KiB      19  [emitted]         
                dev/dist/css/2.css   16.6 KiB       2  [emitted]         
            dev/dist/css/2.css.map   22.9 KiB       2  [emitted]         
               dev/dist/css/20.css   2.48 KiB      20  [emitted]         
           dev/dist/css/20.css.map   3.47 KiB      20  [emitted]         
               dev/dist/css/21.css   2.55 KiB      21  [emitted]         
           dev/dist/css/21.css.map   3.59 KiB      21  [emitted]         
               dev/dist/css/22.css   7.64 KiB      22  [emitted]         
           dev/dist/css/22.css.map   9.43 KiB      22  [emitted]         
               dev/dist/css/23.css   4.75 KiB      23  [emitted]         
           dev/dist/css/23.css.map   6.06 KiB      23  [emitted]         
               dev/dist/css/24.css    2.3 KiB      24  [emitted]         
           dev/dist/css/24.css.map   3.21 KiB      24  [emitted]         
               dev/dist/css/25.css   1.49 KiB      25  [emitted]         
           dev/dist/css/25.css.map   2.06 KiB      25  [emitted]         
               dev/dist/css/26.css  131 bytes      26  [emitted]         
           dev/dist/css/26.css.map  313 bytes      26  [emitted]         
               dev/dist/css/27.css    8.6 KiB      27  [emitted]         
           dev/dist/css/27.css.map   10.3 KiB      27  [emitted]         
               dev/dist/css/28.css  383 bytes      28  [emitted]         
           dev/dist/css/28.css.map  590 bytes      28  [emitted]         
                dev/dist/css/3.css   26.3 KiB       3  [emitted]         
            dev/dist/css/3.css.map   33.2 KiB       3  [emitted]         
                dev/dist/css/5.css   19.7 KiB       5  [emitted]         
            dev/dist/css/5.css.map   24.8 KiB       5  [emitted]         
                dev/dist/css/6.css   4.69 KiB       6  [emitted]         
            dev/dist/css/6.css.map   6.31 KiB       6  [emitted]         
             dev/dist/css/main.css    244 KiB       8  [emitted]         main
         dev/dist/css/main.css.map    309 KiB       8  [emitted]         main
          dev/dist/css/vendors.css    326 KiB      10  [emitted]  [big]  vendors
      dev/dist/css/vendors.css.map    383 KiB      10  [emitted]         vendors
     dev/dist/fonts/commonicon.eot     16 KiB          [emitted]         
     dev/dist/fonts/commonicon.svg     51 KiB          [emitted]         
     dev/dist/fonts/commonicon.ttf   15.8 KiB          [emitted]         
    dev/dist/fonts/commonicon.woff   15.9 KiB          [emitted]         
  dev/dist/fonts/element-icons.ttf   54.6 KiB          [emitted]         
 dev/dist/fonts/element-icons.woff   27.5 KiB          [emitted]         
        dev/dist/fonts/icomoon.eot   47.3 KiB          [emitted]         
        dev/dist/fonts/icomoon.svg    166 KiB          [emitted]         
        dev/dist/fonts/icomoon.ttf   47.1 KiB          [emitted]         
       dev/dist/fonts/icomoon.woff   47.2 KiB          [emitted]         
               dev/dist/index.html   2.04 KiB          [emitted]         
                  dev/dist/js/1.js   60.1 KiB       1  [emitted]         
              dev/dist/js/1.js.map    234 KiB       1  [emitted]         
                 dev/dist/js/11.js    209 KiB      11  [emitted]         
             dev/dist/js/11.js.map    536 KiB      11  [emitted]         
                 dev/dist/js/12.js    195 KiB      12  [emitted]         
             dev/dist/js/12.js.map    603 KiB      12  [emitted]         
                 dev/dist/js/13.js   93.5 KiB      13  [emitted]         
             dev/dist/js/13.js.map    235 KiB      13  [emitted]         
                 dev/dist/js/14.js   58.8 KiB      14  [emitted]         
             dev/dist/js/14.js.map    124 KiB      14  [emitted]         
                 dev/dist/js/15.js   65.6 KiB      15  [emitted]         
             dev/dist/js/15.js.map    154 KiB      15  [emitted]         
                 dev/dist/js/16.js   51.9 KiB      16  [emitted]         
             dev/dist/js/16.js.map    112 KiB      16  [emitted]         
                 dev/dist/js/17.js   34.5 KiB      17  [emitted]         
             dev/dist/js/17.js.map   77.2 KiB      17  [emitted]         
                 dev/dist/js/18.js   37.5 KiB      18  [emitted]         
             dev/dist/js/18.js.map   85.4 KiB      18  [emitted]         
                 dev/dist/js/19.js   46.5 KiB      19  [emitted]         
             dev/dist/js/19.js.map    120 KiB      19  [emitted]         
                  dev/dist/js/2.js    267 KiB       2  [emitted]  [big]  
              dev/dist/js/2.js.map    663 KiB       2  [emitted]         
                 dev/dist/js/20.js   40.5 KiB      20  [emitted]         
             dev/dist/js/20.js.map    109 KiB      20  [emitted]         
                 dev/dist/js/21.js   37.3 KiB      21  [emitted]         
             dev/dist/js/21.js.map     96 KiB      21  [emitted]         
                 dev/dist/js/22.js   35.3 KiB      22  [emitted]         
             dev/dist/js/22.js.map   85.9 KiB      22  [emitted]         
                 dev/dist/js/23.js     23 KiB      23  [emitted]         
             dev/dist/js/23.js.map   46.1 KiB      23  [emitted]         
                 dev/dist/js/24.js   32.1 KiB      24  [emitted]         
             dev/dist/js/24.js.map   83.4 KiB      24  [emitted]         
                 dev/dist/js/25.js     14 KiB      25  [emitted]         
             dev/dist/js/25.js.map   24.7 KiB      25  [emitted]         
                 dev/dist/js/26.js   5.31 KiB      26  [emitted]         
             dev/dist/js/26.js.map   6.44 KiB      26  [emitted]         
                 dev/dist/js/27.js    5.9 KiB      27  [emitted]         
             dev/dist/js/27.js.map   10.8 KiB      27  [emitted]         
                 dev/dist/js/28.js   5.67 KiB      28  [emitted]         
             dev/dist/js/28.js.map   8.07 KiB      28  [emitted]         
                 dev/dist/js/29.js   2.99 KiB      29  [emitted]         
             dev/dist/js/29.js.map   3.81 KiB      29  [emitted]         
                  dev/dist/js/3.js    297 KiB       3  [emitted]  [big]  
              dev/dist/js/3.js.map    975 KiB       3  [emitted]         
                 dev/dist/js/30.js   2.51 KiB      30  [emitted]         
             dev/dist/js/30.js.map   3.05 KiB      30  [emitted]         
                 dev/dist/js/31.js   2.56 KiB      31  [emitted]         
             dev/dist/js/31.js.map   3.81 KiB      31  [emitted]         
                 dev/dist/js/32.js   2.51 KiB      32  [emitted]         
             dev/dist/js/32.js.map    3.8 KiB      32  [emitted]         
                 dev/dist/js/33.js   2.56 KiB      33  [emitted]         
             dev/dist/js/33.js.map   3.81 KiB      33  [emitted]         
                  dev/dist/js/5.js   84.3 KiB       5  [emitted]         
              dev/dist/js/5.js.map    197 KiB       5  [emitted]         
                  dev/dist/js/6.js   28.9 KiB       6  [emitted]         
              dev/dist/js/6.js.map   54.2 KiB       6  [emitted]         
             dev/dist/js/jquery.js   87.9 KiB       7  [emitted]         jquery
         dev/dist/js/jquery.js.map    433 KiB       7  [emitted]         jquery
               dev/dist/js/main.js    722 KiB       8  [emitted]  [big]  main
           dev/dist/js/main.js.map    2.2 MiB       8  [emitted]         main
    dev/dist/js/moment-timezone.js    182 KiB       0  [emitted]         moment-timezone
dev/dist/js/moment-timezone.js.map   26.5 KiB       0  [emitted]         moment-timezone
             dev/dist/js/plotly.js    834 KiB       4  [emitted]  [big]  plotly
         dev/dist/js/plotly.js.map   1.95 MiB       4  [emitted]         plotly
       dev/dist/js/runtime~main.js   3.13 KiB       9  [emitted]         runtime~main
   dev/dist/js/runtime~main.js.map   15.2 KiB       9  [emitted]         runtime~main
            dev/dist/js/vendors.js    605 KiB      10  [emitted]  [big]  vendors
        dev/dist/js/vendors.js.map   1.77 MiB      10  [emitted]         vendors
               images/building.png   25.1 KiB          [emitted]         
              images/expre_401.png   31.4 KiB          [emitted]         
              images/expre_403.png   37.4 KiB          [emitted]         
              images/expre_500.png   30.8 KiB          [emitted]         
        images/loading_circle1.png   14.8 KiB          [emitted]         
        images/loading_circle2.png   14.4 KiB          [emitted]         
         images/switch-icon-on.png   14.7 KiB          [emitted]         
                images/task-en.png   53.9 KiB          [emitted]         
                images/task-zh.png   27.7 KiB          [emitted]         
           images/time-icon-on.png   14.6 KiB          [emitted]         


WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  dev/dist/js/2.js (267 KiB)
  dev/dist/js/3.js (297 KiB)
  dev/dist/js/plotly.js (834 KiB)
  dev/dist/js/main.js (722 KiB)
  dev/dist/css/vendors.css (326 KiB)
  dev/dist/js/vendors.js (605 KiB)


WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.94 MiB)
      dev/dist/js/runtime~main.js
      dev/dist/css/vendors.css
      dev/dist/js/vendors.js
      dev/dist/js/jquery.js
      dev/dist/css/main.css
      dev/dist/js/main.js




(bksops5-env) [god@devel bksops5]$ python manage.py  collectstatic


You have requested to collect static files at the destination
location as specified in your settings:


    /apps/server/bksops5/static


This will overwrite existing files!
Are you sure you want to do this?


Type 'yes' to continue, or 'no' to cancel: yes
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/cancel.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/change_form.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/popup_response.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/guardian/static/guardian/img/icon-yes.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/guardian/static/guardian/img/icon-no.svg'
Copying '/apps/server/bksops5-env/lib/python2.7/site-packages/djcelery/static/djcelery/style.css'


64 static files copied to '/apps/server/bksops5/static', 34 unmodified.




(bksops5-env) [god@devel bksops5]$ rm -rf static/dev static/images  #源代码没有这两个目录
(bksops5-env) [god@devel bksops5]$ mv frontend/desktop/static/dev static/
(bksops5-env) [god@devel bksops5]$ mv frontend/desktop/static/images/ static/









------------------ 原始邮件 ------------------
发件人: "pagezz"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午3:56
收件人: "Tencent/bk-sops"<bk-sops@noreply.github.com>;
抄送: "damon"<304749970@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/bk-sops] 部署标准运维开发环境页面打开是空白 (#956)




看起来是静态资源未找到返回了 404 的 index.html 问题，请确认本地执行了以下命令
 打包并收集前端静态资源 1）安装依赖包 进入 frontend/desktop/，执行以下命令安装 npm install 2）本地打包 在 frontend/desktop/ 目录下，继续执行以下命令打包前端静态资源 npm run build -- --STATIC_ENV=dev 3）收集静态资源 回到项目根目录，执行以下命令收集前端静态资源到 static 目录下 python manage.py collectstatic --noinput 前端资源文件需要单独拷贝收集，执行如下命令 rm -rf static/dev static/images mv frontend/desktop/static/dev static/ mv frontend/desktop/static/images static/

**Comment by damondengxin** [comment]
在npm build 已经出现warning，不知道是不是这里导致的问题？

**Comment by pagezhou** [comment]
warning不影响，看起来一切正常，请问脚本执行完成后 static 目录是和我上面贴的图一致吗？另外，之前有没有部署过标准运维呢，如果有的话尝试清理一下浏览器缓存后再访问

**Comment by damondengxin** [comment]
![clipboard](https://user-images.githubusercontent.com/19447869/63415050-ab6c0180-c42f-11e9-8161-df3f5f86d1ed.png)
目录是一样的，之前是旧版的开发环境可以跑起来，现在paas升级了后，就下载新版的测试之前的标准运维插件，然后开发环境就跑不起来，缓存有清理的。

**Comment by chainingning** [comment]
我也遇到了类似的问题，方便加个好友嘛

**Comment by damondengxin** [comment]
304749970




------------------ 原始邮件 ------------------
发件人: "智慧的钉子"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午5:05
收件人: "Tencent/bk-sops"<bk-sops@noreply.github.com>;
抄送: "damon"<304749970@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/bk-sops] 部署标准运维开发环境页面打开是空白 (#956)




我也遇到了类似的问题，方便加个好友嘛

**Comment by homholueng** [comment]
@damondengxin 麻烦提供一下加载静态文件时浏览器 network 的状态，确认一下静态文件是否有成功加载。

**Comment by damondengxin** [comment]
![bksops](https://user-images.githubusercontent.com/19447869/63658215-70751f80-c7db-11e9-87f6-8202c9930ec3.jpg)

**Comment by pagezhou** [comment]
你们都加一下QQ群878501914，我们在群里跟进下

**Comment by damondengxin** [comment]
我已经以群里了，304749970


------------------ 原始邮件 ------------------
发件人: "pagezz"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 上午10:03
收件人: "Tencent/bk-sops"<bk-sops@noreply.github.com>;
抄送: "damon"<304749970@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Tencent/bk-sops] 部署标准运维开发环境页面打开是空白 (#956)




你们都加一下QQ群878501914，我们在群里跟进下
