### ISSUE TITLE
pipeline 进程异常退出恢复后，需要将僵死任务的状态置为一个最终状态，而不是RUNNING

### ISSUE THREAD

**Issue by jayjiahua** [Tencent/bk-sops#978]
问题描述
=======
若任务处于RUNNING状态时进程被意外kill掉，在下次重启后，该任务就变成了僵死任务，永远处于RUNNING状态。但上层调用方并没有办法检测出这个任务是实际在跑还是已经僵死。所以希望流程引擎提供一个检测机制，自动更新僵死任务状态。

**Comment by homholueng** [comment]
已实现
